export const products = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    category: 'earrings',
    price: 42,
    description: 'A stunning gold ear cuff adorned with a delicate crystal accent. Designed to catch the light and frame your face with effortless elegance.',
    material: '18K Gold Plated Brass with Cubic Zirconia',
    rating: 4.8,
    reviews: 124,
    variants: ['gold', 'silver'],
    imgId: 'vivid-aura-jewels-main-a1b2c3',
    imgId2: 'vivid-aura-jewels-hover-d4e5f6',
    titleId: 'product-vivid-aura-jewels-title',
    descId: 'product-vivid-aura-jewels-desc',
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    category: 'necklaces',
    price: 68,
    description: 'A multicolor floral crystal necklace that brings garden-inspired beauty to any neckline. Each crystal is hand-set for maximum sparkle.',
    material: '18K Gold Plated Sterling Silver with Swarovski Crystals',
    rating: 4.9,
    reviews: 89,
    variants: ['gold', 'silver'],
    imgId: 'majestic-flora-nectar-main-g7h8i9',
    imgId2: 'majestic-flora-nectar-hover-j1k2l3',
    titleId: 'product-majestic-flora-nectar-title',
    descId: 'product-majestic-flora-nectar-desc',
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    category: 'huggies',
    price: 38,
    description: 'Chunky gold dome huggie earrings with a satisfying click closure. Bold yet refined — the everyday statement piece.',
    material: '18K Gold Plated Brass, Nickel-Free',
    rating: 4.7,
    reviews: 203,
    variants: ['gold', 'silver'],
    imgId: 'golden-sphere-huggies-main-m4n5o6',
    imgId2: 'golden-sphere-huggies-hover-p7q8r9',
    titleId: 'product-golden-sphere-huggies-title',
    descId: 'product-golden-sphere-huggies-desc',
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    category: 'earrings',
    price: 54,
    description: 'Textured gold filigree drop earrings inspired by vintage lace patterns. Lightweight and graceful for day-to-night wear.',
    material: '18K Gold Plated Brass with Amber Resin',
    rating: 4.6,
    reviews: 67,
    variants: ['gold', 'silver'],
    imgId: 'amber-lace-earrings-main-s1t2u3',
    imgId2: 'amber-lace-earrings-hover-v4w5x6',
    titleId: 'product-amber-lace-earrings-title',
    descId: 'product-amber-lace-earrings-desc',
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    category: 'necklaces',
    price: 95,
    description: 'A gift-boxed earring and necklace set crafted for those who appreciate timeless beauty. The perfect present for someone special.',
    material: '18K Gold Plated Sterling Silver, Gift Box Included',
    rating: 5.0,
    reviews: 42,
    variants: ['gold', 'silver'],
    imgId: 'royal-heirloom-set-main-y7z8a9',
    imgId2: 'royal-heirloom-set-hover-b1c2d3',
    titleId: 'product-royal-heirloom-set-title',
    descId: 'product-royal-heirloom-set-desc',
  },
]

export const categories = [
  { id: 'earrings', name: 'Earrings', descId: 'cat-earrings-desc', imgId: 'cat-earrings-img-e4f5g6' },
  { id: 'necklaces', name: 'Necklaces', descId: 'cat-necklaces-desc', imgId: 'cat-necklaces-img-h7i8j9' },
  { id: 'huggies', name: 'Huggies', descId: 'cat-huggies-desc', imgId: 'cat-huggies-img-k1l2m3' },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sarah M.',
    text: 'The quality is incredible for the price. I wear my Vivid Aura ear cuff every single day — it still looks brand new after months.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Jessica L.',
    text: 'Bought the Royal Heirloom Set as a gift for my sister. She cried when she opened it. The packaging alone feels so luxurious.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Amanda K.',
    text: 'Finally found jewelry that doesn\'t irritate my sensitive skin. The hypoallergenic gold plating is a game-changer. Obsessed!',
    rating: 5,
  },
]
