export const products = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    description: 'Gold ear cuff with crystal accent — an effortless statement piece that wraps the ear in warm gold and shimmering detail.',
    price: 42,
    category: 'Earrings',
    material: '18K Gold Plated',
    tone: ['Gold', 'Silver'],
    rating: 4.8,
    reviews: 124,
    imgId: 'product-vivid-aura-a1b2c3',
    titleId: 'product-vivid-aura-title',
    descId: 'product-vivid-aura-desc',
    images: [
      { imgId: 'vivid-aura-1-d4e5f6', ratio: '3x4', width: '600' },
      { imgId: 'vivid-aura-2-g7h8i9', ratio: '3x4', width: '600' },
      { imgId: 'vivid-aura-3-j0k1l2', ratio: '3x4', width: '600' },
    ],
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    description: 'Multicolor floral crystal necklace — a garden of color captured in gold, with delicate crystal petals that catch the light.',
    price: 68,
    category: 'Necklaces',
    material: '18K Gold Plated',
    tone: ['Gold'],
    rating: 4.9,
    reviews: 89,
    imgId: 'product-majestic-flora-m3n4o5',
    titleId: 'product-majestic-flora-title',
    descId: 'product-majestic-flora-desc',
    images: [
      { imgId: 'majestic-flora-1-p6q7r8', ratio: '3x4', width: '600' },
      { imgId: 'majestic-flora-2-s9t0u1', ratio: '3x4', width: '600' },
      { imgId: 'majestic-flora-3-v2w3x4', ratio: '3x4', width: '600' },
    ],
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    description: 'Chunky gold dome huggie earrings — bold yet refined, these dome huggies sit close to the ear with a satisfying weight.',
    price: 38,
    category: 'Huggies',
    material: '18K Gold Plated',
    tone: ['Gold', 'Silver'],
    rating: 4.7,
    reviews: 203,
    imgId: 'product-golden-sphere-y5z6a7',
    titleId: 'product-golden-sphere-title',
    descId: 'product-golden-sphere-desc',
    images: [
      { imgId: 'golden-sphere-1-b8c9d0', ratio: '3x4', width: '600' },
      { imgId: 'golden-sphere-2-e1f2g3', ratio: '3x4', width: '600' },
      { imgId: 'golden-sphere-3-h4i5j6', ratio: '3x4', width: '600' },
    ],
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    description: 'Textured gold filigree drop earrings — intricate lace-like patterns in warm gold that sway with every turn.',
    price: 54,
    category: 'Earrings',
    material: '18K Gold Plated',
    tone: ['Gold'],
    rating: 4.6,
    reviews: 67,
    imgId: 'product-amber-lace-k7l8m9',
    titleId: 'product-amber-lace-title',
    descId: 'product-amber-lace-desc',
    images: [
      { imgId: 'amber-lace-1-n0o1p2', ratio: '3x4', width: '600' },
      { imgId: 'amber-lace-2-q3r4s5', ratio: '3x4', width: '600' },
      { imgId: 'amber-lace-3-t6u7v8', ratio: '3x4', width: '600' },
    ],
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    description: 'Gift-boxed earring + necklace set — a coordinated pairing of elegance, presented in a signature Velmora box ready for gifting.',
    price: 95,
    category: 'Sets',
    material: '18K Gold Plated',
    tone: ['Gold', 'Silver'],
    rating: 5.0,
    reviews: 42,
    imgId: 'product-royal-heirloom-w9x0y1',
    titleId: 'product-royal-heirloom-title',
    descId: 'product-royal-heirloom-desc',
    images: [
      { imgId: 'royal-heirloom-1-z2a3b4', ratio: '3x4', width: '600' },
      { imgId: 'royal-heirloom-2-c5d6e7', ratio: '3x4', width: '600' },
      { imgId: 'royal-heirloom-3-f8g9h0', ratio: '3x4', width: '600' },
    ],
  },
]

export const categories = [
  {
    id: 'earrings',
    name: 'Earrings',
    imgId: 'cat-earrings-i1j2k3',
    titleId: 'cat-earrings-title',
    ratio: '4x5',
    width: '500',
  },
  {
    id: 'necklaces',
    name: 'Necklaces',
    imgId: 'cat-necklaces-l4m5n6',
    titleId: 'cat-necklaces-title',
    ratio: '4x5',
    width: '500',
  },
  {
    id: 'huggies',
    name: 'Huggies',
    imgId: 'cat-huggies-o7p8q9',
    titleId: 'cat-huggies-title',
    ratio: '4x5',
    width: '500',
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sarah M.',
    text: 'The quality is incredible for the price. My Golden Sphere Huggies look just like solid gold — I wear them every day.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Priya K.',
    text: 'Bought the Royal Heirloom Set as a gift and the packaging alone made it feel so special. She absolutely loved it.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Emma L.',
    text: 'I\'m obsessed with the Amber Lace Earrings. They\'re delicate but make such a statement. Already planning my next order.',
    rating: 5,
  },
]

export const ugcSlides = [
  { id: 'ugc-1', imgId: 'ugc-ear-cuff-r1s2t3', caption: 'Everyday elegance', titleId: 'ugc-1-title' },
  { id: 'ugc-2', imgId: 'ugc-necklace-u4v5w6', caption: 'Golden hour glow', titleId: 'ugc-2-title' },
  { id: 'ugc-3', imgId: 'ugc-huggies-x7y8z9', caption: 'Stacked & styled', titleId: 'ugc-3-title' },
  { id: 'ugc-4', imgId: 'ugc-drop-a0b1c2', caption: 'Date night ready', titleId: 'ugc-4-title' },
  { id: 'ugc-5', imgId: 'ugc-set-d3e4f5', caption: 'Gift-worthy', titleId: 'ugc-5-title' },
  { id: 'ugc-6', imgId: 'ugc-gold-g6h7i8', caption: 'Minimal luxury', titleId: 'ugc-6-title' },
]
