export const products = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    category: 'Earrings',
    price: 42,
    rating: 4.8,
    reviews: 24,
    description: 'A delicate gold ear cuff featuring a radiant crystal accent for a touch of effortless sparkle.',
    materials: '18K Gold Plated over Sterling Silver, Lab-grown Crystal.',
    images: ['vivid-aura-1', 'vivid-aura-2'],
    slug: 'vivid-aura-jewels',
    isBestseller: true,
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    category: 'Necklaces',
    price: 68,
    rating: 4.9,
    reviews: 18,
    description: 'An editorial statement piece featuring multicolor flora crystal clusters on a refined gold chain.',
    materials: '18K Gold Plated Brass, Zirconia Crystals.',
    images: ['majestic-flora-1', 'majestic-flora-2'],
    slug: 'majestic-flora-nectar',
    isBestseller: true,
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    category: 'Earrings',
    price: 38,
    rating: 4.7,
    reviews: 42,
    description: 'Chunky gold dome huggies that provide a bold yet minimalist aesthetic for everyday wear.',
    materials: '18K Gold Plated Sterling Silver.',
    images: ['golden-sphere-1', 'golden-sphere-2'],
    slug: 'golden-sphere-huggies',
    isBestseller: true,
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    category: 'Earrings',
    price: 54,
    rating: 4.6,
    reviews: 12,
    description: 'Intricately textured gold filigree drop earrings inspired by vintage lace patterns.',
    materials: '18K Gold Plated Brass.',
    images: ['amber-lace-1', 'amber-lace-2'],
    slug: 'amber-lace-earrings',
    isBestseller: true,
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    category: 'Sets',
    price: 95,
    rating: 5.0,
    reviews: 8,
    description: 'A curated gift set featuring our best-selling earrings and a matching pendant necklace, elegantly gift-boxed.',
    materials: '18K Gold Plated, Luxury Gift Box included.',
    images: ['royal-heirloom-1', 'royal-heirloom-2'],
    slug: 'royal-heirloom-set',
    isBestseller: true,
  }
];
