export const featuredGenerators = [
  { name: 'AI Website Generator', description: 'Describe your business, get a full site', category: 'Website', slug: 'ai-website-generator' },
  { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', category: 'Portfolio', slug: 'free-portfolio-generator' },
  { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', category: 'Landing Page', slug: 'ai-landing-page-maker' },
  { name: 'Online Store Builder', description: 'Start selling without writing code', category: 'Store', slug: 'online-store-builder' },
  { name: 'Link-in-Bio Generator', description: 'One link for all your channels', category: 'Link-in-Bio', slug: 'link-in-bio-generator' },
  { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', category: 'Website', slug: 'one-page-website-builder' },
  { name: 'Wedding Website Generator', description: 'Share your day with guests', category: 'Website', slug: 'wedding-website-generator' },
  { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', category: 'Website', slug: 'restaurant-website-builder' },
  { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', category: 'Blog', slug: 'blog-generator-for-beginners' },
];

export const categories = [
  { name: 'WEBSITES', slug: 'websites', description: 'AI-built business and personal sites for any goal.' },
  { name: 'LANDING PAGES', slug: 'landing-pages', description: 'Single-page sites built to convert visitors fast.' },
  { name: 'PORTFOLIOS', slug: 'portfolios', description: 'Showcase your work with a clean, focused site.' },
  { name: 'BLOGS', slug: 'blogs', description: 'Publish-ready blogs with built-in SEO basics.' },
  { name: 'ONLINE STORES', slug: 'stores', description: 'Sell products online with payments built in.' },
  { name: 'LINK-IN-BIO', slug: 'link-in-bio', description: 'One link, all your places. Made for creators.' },
];

export const allGenerators = {
  websites: [
    { name: 'AI Website Generator', description: 'Describe your business, get a full site', slug: 'ai-website-generator' },
    { name: 'Free Website Builder for Photographers', description: 'Showcase your portfolio online', slug: 'free-website-builder-photographers' },
    { name: 'One-Page Wedding Website Builder', description: 'Share your day with guests', slug: 'one-page-wedding-website-builder' },
    { name: 'Restaurant Website Generator', description: 'Menu, hours, reservations, done', slug: 'restaurant-website-generator' },
    { name: 'AI Business Website Maker', description: 'Professional sites for any industry', slug: 'ai-business-website-maker' },
    { name: 'Free Website Builder for Yoga Instructors', description: 'Book classes, share your practice', slug: 'free-website-builder-yoga-instructors' },
    { name: 'No-Code Website Builder for Consultants', description: 'Land clients with a pro site', slug: 'no-code-website-builder-consultants' },
    { name: 'Beautiful Website Generator for Artists', description: 'Display your work beautifully', slug: 'beautiful-website-generator-artists' },
    { name: 'AI Website Builder for Coaches', description: 'Attract clients, book sessions', slug: 'ai-website-builder-coaches' },
    { name: 'Free One-Page Website for Freelancers', description: 'Simple, fast, professional', slug: 'free-one-page-website-freelancers' },
    { name: 'Website Generator for Nonprofits', description: 'Share your mission, get donations', slug: 'website-generator-nonprofits' },
    { name: 'AI Website Builder for Real Estate', description: 'Listings, agents, leads, done', slug: 'ai-website-builder-real-estate' },
  ],
  'landing-pages': [
    { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', slug: 'ai-landing-page-maker' },
    { name: 'Free Landing Page Generator for SaaS', description: 'Convert visitors to signups', slug: 'free-landing-page-generator-saas' },
    { name: 'Product Launch Landing Page Builder', description: 'Launch day, one page, done', slug: 'product-launch-landing-page-builder' },
    { name: 'AI Landing Page for Webinars', description: 'Register attendees in minutes', slug: 'ai-landing-page-webinars' },
    { name: 'Free Landing Page for Ebooks', description: 'Capture leads with a download', slug: 'free-landing-page-ebooks' },
    { name: 'Landing Page Generator for Agencies', description: 'Showcase services, get inquiries', slug: 'landing-page-generator-agencies' },
    { name: 'AI Landing Page for Events', description: 'Promote your event, sell tickets', slug: 'ai-landing-page-events' },
    { name: 'Free Landing Page for Apps', description: 'Drive downloads with one page', slug: 'free-landing-page-apps' },
    { name: 'Landing Page Builder for Courses', description: 'Enroll students, fast', slug: 'landing-page-builder-courses' },
    { name: 'AI Landing Page for Consultants', description: 'Book calls, grow your pipeline', slug: 'ai-landing-page-consultants' },
    { name: 'Free Landing Page for Newsletters', description: 'Grow your subscriber list', slug: 'free-landing-page-newsletters' },
    { name: 'Landing Page Generator for Startups', description: 'Validate your idea in a day', slug: 'landing-page-generator-startups' },
  ],
  portfolios: [
    { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', slug: 'free-portfolio-generator' },
    { name: 'Portfolio Generator for Designers', description: 'Showcase your best work', slug: 'portfolio-generator-designers' },
    { name: 'AI Portfolio Builder for Photographers', description: 'Let your images speak', slug: 'ai-portfolio-builder-photographers' },
    { name: 'Free Portfolio for Architects', description: 'Present projects beautifully', slug: 'free-portfolio-architects' },
    { name: 'Portfolio Generator for Writers', description: 'Publish your clips, get hired', slug: 'portfolio-generator-writers' },
    { name: 'AI Portfolio for Videographers', description: 'Showreel, projects, contact', slug: 'ai-portfolio-videographers' },
    { name: 'Free Portfolio for Musicians', description: 'Share your sound, book gigs', slug: 'free-portfolio-musicians' },
    { name: 'Portfolio Builder for Illustrators', description: 'Gallery-style, minimal layout', slug: 'portfolio-builder-illustrators' },
    { name: 'AI Portfolio for Models', description: 'Comp cards, galleries, bookings', slug: 'ai-portfolio-models' },
    { name: 'Free Portfolio for Developers', description: 'Projects, skills, resume, done', slug: 'free-portfolio-developers' },
    { name: 'Portfolio Generator for Filmmakers', description: 'Screen your work online', slug: 'portfolio-generator-filmmakers' },
    { name: 'AI Portfolio for Artists', description: 'Gallery, about, contact, shop', slug: 'ai-portfolio-artists' },
  ],
  blogs: [
    { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', slug: 'blog-generator-for-beginners' },
    { name: 'AI Blog Builder for Travelers', description: 'Share your journeys online', slug: 'ai-blog-builder-travelers' },
    { name: 'Free Blog Generator for Foodies', description: 'Recipes, photos, stories', slug: 'free-blog-generator-foodies' },
    { name: 'Blog Builder for Tech Writers', description: 'Code snippets, tutorials, SEO', slug: 'blog-builder-tech-writers' },
    { name: 'AI Blog Generator for Marketers', description: 'Content that ranks and converts', slug: 'ai-blog-generator-marketers' },
    { name: 'Free Blog for Personal Journals', description: 'Write, reflect, share', slug: 'free-blog-personal-journals' },
    { name: 'Blog Generator for Small Businesses', description: 'Attract customers with content', slug: 'blog-generator-small-businesses' },
    { name: 'AI Blog Builder for Lifestyle', description: 'Fashion, wellness, daily life', slug: 'ai-blog-builder-lifestyle' },
    { name: 'Free Blog for Book Reviews', description: 'Read, review, recommend', slug: 'free-blog-book-reviews' },
    { name: 'Blog Generator for Educators', description: 'Share knowledge, build authority', slug: 'blog-generator-educators' },
    { name: 'AI Blog for Fitness Coaches', description: 'Workouts, tips, client stories', slug: 'ai-blog-fitness-coaches' },
    { name: 'Free Blog for Hobbyists', description: 'Passion projects, community', slug: 'free-blog-hobbyists' },
  ],
  stores: [
    { name: 'Online Store Builder', description: 'Start selling without writing code', slug: 'online-store-builder' },
    { name: 'Online Store Builder for Restaurants', description: 'Take orders, deliver locally', slug: 'online-store-builder-restaurants' },
    { name: 'AI Store Builder for Fashion', description: 'Lookbooks, sizes, checkout', slug: 'ai-store-builder-fashion' },
    { name: 'Free Online Store for Handmade Goods', description: 'Craft, list, sell, ship', slug: 'free-online-store-handmade-goods' },
    { name: 'Store Builder for Digital Products', description: 'Ebooks, courses, downloads', slug: 'store-builder-digital-products' },
    { name: 'AI Store for Beauty Brands', description: 'Products, reviews, subscriptions', slug: 'ai-store-beauty-brands' },
    { name: 'Free Store for Artists', description: 'Sell prints, originals, merch', slug: 'free-store-artists' },
    { name: 'Store Builder for Subscription Boxes', description: 'Recurring revenue, happy customers', slug: 'store-builder-subscription-boxes' },
    { name: 'AI Store for Pet Supplies', description: 'Food, toys, accessories, done', slug: 'ai-store-pet-supplies' },
    { name: 'Free Store for Musicians', description: 'Merch, albums, tickets', slug: 'free-store-musicians' },
    { name: 'Store Builder for Home Decor', description: 'Catalog, cart, checkout', slug: 'store-builder-home-decor' },
    { name: 'AI Store for Fitness Gear', description: 'Equipment, apparel, supplements', slug: 'ai-store-fitness-gear' },
  ],
  'link-in-bio': [
    { name: 'Link-in-Bio Generator', description: 'One link for all your channels', slug: 'link-in-bio-generator' },
    { name: 'Free Link-in-Bio for Instagram Creators', description: 'All your links, one place', slug: 'free-link-in-bio-instagram-creators' },
    { name: 'AI Link-in-Bio for Musicians', description: 'Streams, merch, tour dates', slug: 'ai-link-in-bio-musicians' },
    { name: 'Link-in-Bio for Podcasters', description: 'Episodes, sponsors, subscribe', slug: 'link-in-bio-podcasters' },
    { name: 'Free Link-in-Bio for Photographers', description: 'Portfolio, bookings, shop', slug: 'free-link-in-bio-photographers' },
    { name: 'AI Link-in-Bio for Coaches', description: 'Book calls, sell courses, connect', slug: 'ai-link-in-bio-coaches' },
    { name: 'Link-in-Bio for YouTubers', description: 'Videos, merch, community', slug: 'link-in-bio-youtubers' },
    { name: 'Free Link-in-Bio for Fitness Trainers', description: 'Programs, bookings, social', slug: 'free-link-in-bio-fitness-trainers' },
    { name: 'AI Link-in-Bio for Authors', description: 'Books, events, newsletter', slug: 'ai-link-in-bio-authors' },
    { name: 'Link-in-Bio for Chefs', description: 'Recipes, classes, catering', slug: 'link-in-bio-chefs' },
    { name: 'Free Link-in-Bio for Artists', description: 'Gallery, shop, commissions', slug: 'free-link-in-bio-artists' },
    { name: 'AI Link-in-Bio for Entrepreneurs', description: 'Ventures, speaking, contact', slug: 'ai-link-in-bio-entrepreneurs' },
  ],
};
