// Mock data for the GameVault site

export const PLATFORMS = {
  Steam: { label: 'Steam', color: '#1b9aaa', bg: 'bg-[#1b2838]', border: 'border-[#1b9aaa]', text: 'text-[#66c0f4]' },
  Epic: { label: 'Epic Games', color: '#0078f2', bg: 'bg-[#2d2d2d]', border: 'border-[#0078f2]', text: 'text-[#0078f2]' },
  Nintendo: { label: 'Nintendo', color: '#e4000f', bg: 'bg-[#e4000f]', border: 'border-[#e4000f]', text: 'text-[#e4000f]' },
  PlayStation: { label: 'PlayStation', color: '#0070d1', bg: 'bg-[#003087]', border: 'border-[#0070d1]', text: 'text-[#0070d1]' },
  Xbox: { label: 'Xbox', color: '#52b043', bg: 'bg-[#107c10]', border: 'border-[#52b043]', text: 'text-[#52b043]' },
};

export const STORE_PRODUCTS = [
  {
    id: 1,
    title: 'Cyberpunk 2077',
    description: 'An open-world action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification.',
    price: 29.99,
    original_price: 59.99,
    discount_percent: 50,
    platform: 'PC',
    genre: 'RPG',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    release_date: '2020-12-10',
    rating: 4.2,
    stock: 999,
    is_featured: true,
    is_active: true,
    tags: ['Open World', 'RPG', 'Cyberpunk', 'Action'],
    cover_color: 'from-yellow-900 to-yellow-600',
  },
  {
    id: 2,
    title: 'Elden Ring',
    description: 'A fantasy action-RPG adventure set within a world created by Hidetaka Miyazaki and George R. R. Martin.',
    price: 49.99,
    original_price: 59.99,
    discount_percent: 17,
    platform: 'Multi-Platform',
    genre: 'Action RPG',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    release_date: '2022-02-25',
    rating: 4.8,
    stock: 500,
    is_featured: true,
    is_active: true,
    tags: ['Souls-like', 'RPG', 'Fantasy', 'Open World'],
    cover_color: 'from-amber-900 to-amber-600',
  },
  {
    id: 3,
    title: 'God of War Ragnarök',
    description: 'Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle.',
    price: 39.99,
    original_price: 69.99,
    discount_percent: 43,
    platform: 'PlayStation',
    genre: 'Action Adventure',
    developer: 'Santa Monica Studio',
    publisher: 'Sony Interactive Entertainment',
    release_date: '2022-11-09',
    rating: 4.9,
    stock: 300,
    is_featured: true,
    is_active: true,
    tags: ['Action', 'Adventure', 'Norse Mythology', 'Story Rich'],
    cover_color: 'from-blue-900 to-blue-600',
  },
  {
    id: 4,
    title: 'The Legend of Zelda: Tears of the Kingdom',
    description: 'An epic adventure across the land and skies of Hyrule awaits in this sequel to Breath of the Wild.',
    price: 59.99,
    original_price: 59.99,
    discount_percent: 0,
    platform: 'Nintendo Switch',
    genre: 'Action Adventure',
    developer: 'Nintendo EPD',
    publisher: 'Nintendo',
    release_date: '2023-05-12',
    rating: 4.9,
    stock: 200,
    is_featured: true,
    is_active: true,
    tags: ['Open World', 'Adventure', 'Puzzle', 'Fantasy'],
    cover_color: 'from-green-900 to-green-600',
  },
  {
    id: 5,
    title: 'Halo Infinite',
    description: 'When all hope is lost and humanity\'s fate hangs in the balance, the Master Chief is ready to confront the most ruthless foe he\'s ever faced.',
    price: 19.99,
    original_price: 59.99,
    discount_percent: 67,
    platform: 'Xbox',
    genre: 'FPS',
    developer: '343 Industries',
    publisher: 'Xbox Game Studios',
    release_date: '2021-12-08',
    rating: 4.0,
    stock: 750,
    is_featured: false,
    is_active: true,
    tags: ['FPS', 'Sci-Fi', 'Multiplayer', 'Action'],
    cover_color: 'from-teal-900 to-teal-600',
  },
  {
    id: 6,
    title: 'Baldur\'s Gate 3',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.',
    price: 59.99,
    original_price: 59.99,
    discount_percent: 0,
    platform: 'PC',
    genre: 'RPG',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    release_date: '2023-08-03',
    rating: 4.9,
    stock: 999,
    is_featured: true,
    is_active: true,
    tags: ['RPG', 'Turn-Based', 'Fantasy', 'Co-op'],
    cover_color: 'from-purple-900 to-purple-600',
  },
  {
    id: 7,
    title: 'Spider-Man 2',
    description: 'Peter Parker and Miles Morales face the ultimate test of strength inside and outside the mask as they fight to save Marvel\'s New York.',
    price: 49.99,
    original_price: 69.99,
    discount_percent: 29,
    platform: 'PlayStation',
    genre: 'Action Adventure',
    developer: 'Insomniac Games',
    publisher: 'Sony Interactive Entertainment',
    release_date: '2023-10-20',
    rating: 4.7,
    stock: 400,
    is_featured: false,
    is_active: true,
    tags: ['Action', 'Superhero', 'Open World', 'Story Rich'],
    cover_color: 'from-red-900 to-red-600',
  },
  {
    id: 8,
    title: 'Starfield',
    description: 'In this next generation role-playing game set amongst the stars, create any character you want and explore with unparalleled freedom.',
    price: 39.99,
    original_price: 69.99,
    discount_percent: 43,
    platform: 'Xbox',
    genre: 'RPG',
    developer: 'Bethesda Game Studios',
    publisher: 'Bethesda Softworks',
    release_date: '2023-09-06',
    rating: 3.8,
    stock: 600,
    is_featured: false,
    is_active: true,
    tags: ['RPG', 'Space', 'Open World', 'Sci-Fi'],
    cover_color: 'from-slate-900 to-slate-600',
  },
];

export const BLOG_ARTICLES = [
  {
    id: 1,
    title: 'GTA VI Release Date Confirmed: Everything We Know',
    slug: 'gta-vi-release-date-confirmed',
    excerpt: 'Rockstar Games has officially confirmed the release window for Grand Theft Auto VI, and the gaming world is buzzing with excitement.',
    category: 'News',
    author: 'Alex Chen',
    published_at: '2026-05-15T10:00:00Z',
    is_published: true,
    is_featured: true,
    read_time_minutes: 5,
    views: 48200,
    platform_tags: ['PC', 'PlayStation', 'Xbox'],
    tags: ['GTA VI', 'Rockstar', 'Open World'],
    cover_color: 'from-orange-900 via-red-900 to-pink-900',
  },
  {
    id: 2,
    title: 'Epic Games Free Games This Month: Full List',
    slug: 'epic-games-free-games-may-2026',
    excerpt: 'Epic Games Store is giving away some incredible titles this month. Here\'s the complete list of free games you can claim right now.',
    category: 'Deals',
    author: 'Sarah Kim',
    published_at: '2026-05-12T08:00:00Z',
    is_published: true,
    is_featured: true,
    read_time_minutes: 3,
    views: 32100,
    platform_tags: ['Epic'],
    tags: ['Free Games', 'Epic', 'Deals'],
    cover_color: 'from-blue-900 via-indigo-900 to-purple-900',
  },
  {
    id: 3,
    title: 'Review: Hollow Knight: Silksong — Worth the Wait?',
    slug: 'hollow-knight-silksong-review',
    excerpt: 'After years of anticipation, Silksong is finally here. We spent 40 hours with the game to bring you our definitive verdict.',
    category: 'Review',
    author: 'Marcus Webb',
    published_at: '2026-05-10T14:00:00Z',
    is_published: true,
    is_featured: false,
    read_time_minutes: 8,
    views: 21500,
    platform_tags: ['Steam', 'Nintendo', 'Xbox'],
    tags: ['Review', 'Indie', 'Metroidvania'],
    cover_color: 'from-slate-900 via-gray-800 to-zinc-900',
  },
  {
    id: 4,
    title: 'Steam Summer Sale 2026: Best Deals Under $10',
    slug: 'steam-summer-sale-2026-best-deals',
    excerpt: 'The Steam Summer Sale is live! We\'ve curated the absolute best deals you can grab for under $10 this year.',
    category: 'Deals',
    author: 'Priya Patel',
    published_at: '2026-05-08T09:00:00Z',
    is_published: true,
    is_featured: true,
    read_time_minutes: 6,
    views: 55800,
    platform_tags: ['Steam'],
    tags: ['Steam Sale', 'Deals', 'Budget Gaming'],
    cover_color: 'from-cyan-900 via-teal-900 to-emerald-900',
  },
  {
    id: 5,
    title: 'Nintendo Direct June 2026: All Announcements',
    slug: 'nintendo-direct-june-2026-announcements',
    excerpt: 'Nintendo\'s latest Direct packed in a ton of surprises. Here\'s every game announced and what you need to know.',
    category: 'News',
    author: 'Yuki Tanaka',
    published_at: '2026-05-06T18:00:00Z',
    is_published: true,
    is_featured: false,
    read_time_minutes: 7,
    views: 38900,
    platform_tags: ['Nintendo'],
    tags: ['Nintendo', 'Direct', 'Announcements'],
    cover_color: 'from-red-900 via-rose-900 to-pink-900',
  },
  {
    id: 6,
    title: 'PS5 Pro vs Xbox Series X: Which Should You Buy in 2026?',
    slug: 'ps5-pro-vs-xbox-series-x-2026',
    excerpt: 'With the PS5 Pro now widely available, we compare it head-to-head with the Xbox Series X to help you decide which console is right for you.',
    category: 'Feature',
    author: 'Jordan Lee',
    published_at: '2026-05-03T12:00:00Z',
    is_published: true,
    is_featured: false,
    read_time_minutes: 10,
    views: 29400,
    platform_tags: ['PlayStation', 'Xbox'],
    tags: ['Console Wars', 'PS5 Pro', 'Xbox'],
    cover_color: 'from-violet-900 via-purple-900 to-indigo-900',
  },
];

export const PLATFORM_DEALS = [
  {
    id: 1,
    game_title: 'Cyberpunk 2077',
    platform: 'Steam',
    original_price: 59.99,
    sale_price: 17.99,
    discount_percent: 70,
    genre: 'RPG',
    is_free: false,
    is_active: true,
    is_featured: true,
    expires_at: '2026-06-01T23:59:59Z',
    cover_color: 'from-yellow-800 to-orange-900',
  },
  {
    id: 2,
    game_title: 'Satisfactory',
    platform: 'Epic',
    original_price: 29.99,
    sale_price: 0,
    discount_percent: 100,
    genre: 'Simulation',
    is_free: true,
    is_active: true,
    is_featured: true,
    expires_at: '2026-05-25T23:59:59Z',
    cover_color: 'from-blue-800 to-indigo-900',
  },
  {
    id: 3,
    game_title: 'Mario Kart 8 Deluxe',
    platform: 'Nintendo',
    original_price: 59.99,
    sale_price: 41.99,
    discount_percent: 30,
    genre: 'Racing',
    is_free: false,
    is_active: true,
    is_featured: true,
    expires_at: '2026-05-28T23:59:59Z',
    cover_color: 'from-red-800 to-rose-900',
  },
  {
    id: 4,
    game_title: 'God of War',
    platform: 'PlayStation',
    original_price: 49.99,
    sale_price: 19.99,
    discount_percent: 60,
    genre: 'Action Adventure',
    is_free: false,
    is_active: true,
    is_featured: true,
    expires_at: '2026-05-30T23:59:59Z',
    cover_color: 'from-blue-900 to-slate-900',
  },
  {
    id: 5,
    game_title: 'Forza Horizon 5',
    platform: 'Xbox',
    original_price: 59.99,
    sale_price: 23.99,
    discount_percent: 60,
    genre: 'Racing',
    is_free: false,
    is_active: true,
    is_featured: true,
    expires_at: '2026-06-05T23:59:59Z',
    cover_color: 'from-green-800 to-emerald-900',
  },
  {
    id: 6,
    game_title: 'Half-Life: Alyx',
    platform: 'Steam',
    original_price: 59.99,
    sale_price: 29.99,
    discount_percent: 50,
    genre: 'VR FPS',
    is_free: false,
    is_active: true,
    is_featured: false,
    expires_at: '2026-06-01T23:59:59Z',
    cover_color: 'from-orange-800 to-amber-900',
  },
  {
    id: 7,
    game_title: 'Alan Wake 2',
    platform: 'Epic',
    original_price: 49.99,
    sale_price: 29.99,
    discount_percent: 40,
    genre: 'Horror',
    is_free: false,
    is_active: true,
    is_featured: false,
    expires_at: '2026-05-26T23:59:59Z',
    cover_color: 'from-gray-800 to-zinc-900',
  },
  {
    id: 8,
    game_title: 'Splatoon 3',
    platform: 'Nintendo',
    original_price: 59.99,
    sale_price: 35.99,
    discount_percent: 40,
    genre: 'Shooter',
    is_free: false,
    is_active: true,
    is_featured: false,
    expires_at: '2026-05-29T23:59:59Z',
    cover_color: 'from-purple-800 to-violet-900',
  },
  {
    id: 9,
    game_title: 'Returnal',
    platform: 'PlayStation',
    original_price: 59.99,
    sale_price: 29.99,
    discount_percent: 50,
    genre: 'Roguelike',
    is_free: false,
    is_active: true,
    is_featured: false,
    expires_at: '2026-05-31T23:59:59Z',
    cover_color: 'from-cyan-900 to-teal-900',
  },
  {
    id: 10,
    game_title: 'Sea of Thieves',
    platform: 'Xbox',
    original_price: 39.99,
    sale_price: 15.99,
    discount_percent: 60,
    genre: 'Adventure',
    is_free: false,
    is_active: true,
    is_featured: false,
    expires_at: '2026-06-03T23:59:59Z',
    cover_color: 'from-sky-800 to-blue-900',
  },
];
