export const PLATFORMS = {
  steam: {
    key: 'steam',
    name: 'Steam',
    tagline: "The World's Largest PC Gaming Platform",
    description: 'Discover thousands of PC games — from epic AAA blockbusters to indie gems. Buy, play, and connect with millions of gamers worldwide.',
    stats: [
      { value: '50,000+', label: 'Games' },
      { value: '132M', label: 'Active Users' },
      { value: '30+', label: 'Languages' },
    ],
    pageBg: '#0f1923',
    heroBg: '#1b2838',
    accent: '#1a9fff',
    accentDark: '#1178cc',
    cardBg: '#16202d',
    cardBorder: '#2a475e',
    textMuted: '#8f98a0',
    textSecondary: '#c6d4df',
    badgeBg: '#1b2838',
    badgeText: '#66c0f4',
    badgeBorder: '#2a475e',
    navDot: '#1a9fff',
  },
  playstation: {
    key: 'playstation',
    name: 'PlayStation',
    tagline: 'Play Has No Limits',
    description: 'Experience the best of PlayStation gaming with exclusive titles, PS Plus benefits, and the power of PS5.',
    stats: [
      { value: '5,000+', label: 'PS5 Games' },
      { value: '100M+', label: 'PS Plus Members' },
      { value: '4K HDR', label: 'Ultra HD' },
    ],
    pageBg: '#00194a',
    heroBg: '#00439C',
    accent: '#4db8ff',
    accentDark: '#0070d1',
    cardBg: '#001a3a',
    cardBorder: '#003080',
    textMuted: '#7ab0e0',
    textSecondary: '#a0c4ff',
    badgeBg: '#003080',
    badgeText: '#7ab0e0',
    badgeBorder: '#004db3',
    navDot: '#0070d1',
  },
  xbox: {
    key: 'xbox',
    name: 'Xbox',
    tagline: 'Power Your Dreams',
    description: 'Play hundreds of high-quality games with Xbox Game Pass. Day one releases, classics, and more — all in one subscription.',
    stats: [
      { value: '100+', label: 'Day One Games' },
      { value: '25M+', label: 'Game Pass Members' },
      { value: '4K/120fps', label: 'Performance' },
    ],
    pageBg: '#0a0a0a',
    heroBg: '#107C10',
    accent: '#52B043',
    accentDark: '#0d6b0d',
    cardBg: '#111111',
    cardBorder: '#1a3a1a',
    textMuted: '#6a9a6a',
    textSecondary: '#a0c8a0',
    badgeBg: '#0d2a0d',
    badgeText: '#52B043',
    badgeBorder: '#1a4a1a',
    navDot: '#107C10',
  },
  epic: {
    key: 'epic',
    name: 'Epic Games',
    tagline: 'Free Games Every Week',
    description: 'Get free games every week, discover exclusive titles, and enjoy the Epic Games Store with no subscription required.',
    stats: [
      { value: '1,000+', label: 'Games' },
      { value: '230M+', label: 'Players' },
      { value: 'Weekly', label: 'Free Games' },
    ],
    pageBg: '#0d0d0d',
    heroBg: '#1a1a1a',
    accent: '#ffffff',
    accentDark: '#aaaaaa',
    cardBg: '#1a1a1a',
    cardBorder: '#2a2a2a',
    textMuted: '#888888',
    textSecondary: '#cccccc',
    badgeBg: '#2a2a2a',
    badgeText: '#ffffff',
    badgeBorder: '#444444',
    navDot: '#ffffff',
  },
  nintendo: {
    key: 'nintendo',
    name: 'Nintendo',
    tagline: 'Play Anywhere, Anytime',
    description: 'Enjoy iconic Nintendo franchises and indie gems on Nintendo Switch. Play at home or on the go with a library of 4,000+ games.',
    stats: [
      { value: '4,000+', label: 'Switch Games' },
      { value: '140M+', label: 'Switch Units Sold' },
      { value: '3 Modes', label: 'TV / Tabletop / Handheld' },
    ],
    pageBg: '#1a0005',
    heroBg: '#e60012',
    accent: '#ff6677',
    accentDark: '#cc0010',
    cardBg: '#2a0008',
    cardBorder: '#5a0015',
    textMuted: '#cc6677',
    textSecondary: '#ffb3bb',
    badgeBg: '#3a0010',
    badgeText: '#ff9aaa',
    badgeBorder: '#6a0020',
    navDot: '#e60012',
  },
};

export const PLATFORM_ORDER = ['steam', 'playstation', 'xbox', 'epic', 'nintendo'];
