export const products = [
  {
    id: "ad-720",
    slug: "ad-720-double-folder",
    name: "AD-720 Double Folder",
    tagline: "Double folding machine",
    summary:
      "The flagship double folding machine engineered for symmetric up-and-down bends without flipping the workpiece. Built for production runs that demand consistent geometry.",
    capacity: "2,500 mm × 2.0 mm",
    bendType: "Up & down (double)",
    productivity: "Up to 18 panels / min",
    cncAxes: "5-axis CNC",
    imgId: "product-ad-720-9f2a1c",
    titleId: "product-ad-720-title",
    descId: "product-ad-720-desc",
    features: [
      "Bidirectional bending without flipping",
      "Pneumatic blank holder, 14 ton clamping",
      "Self-calibrating back gauge",
      "Touchscreen HMI with offline programming",
    ],
  },
  {
    id: "df-2500",
    slug: "df-2500-sheet-metal-folder",
    name: "DF-2500 Sheet Metal Folder",
    tagline: "Sheet metal folder",
    summary:
      "An everyday workhorse sheet metal folder for fabricators. Crisp, repeatable folds on stainless, aluminium and mild steel up to 2.5 mm.",
    capacity: "2,500 mm × 2.5 mm",
    bendType: "Single (up)",
    productivity: "Up to 22 panels / min",
    cncAxes: "3-axis CNC",
    imgId: "product-df-2500-7be4d2",
    titleId: "product-df-2500-title",
    descId: "product-df-2500-desc",
    features: [
      "Sectional upper beam for box folding",
      "Servo-driven back gauge",
      "Manual or programmed mode",
      "Footprint optimised for small workshops",
    ],
  },
  {
    id: "mf-3200",
    slug: "mf-3200-metal-folding-machine",
    name: "MF-3200 Metal Folding Machine",
    tagline: "Metal folding machine",
    summary:
      "Wide-format metal folding machine for architectural cladding, façade panels and HVAC ducting. 3.2 m bed, heavy 4 mm capacity.",
    capacity: "3,200 mm × 4.0 mm",
    bendType: "Up & down (double)",
    productivity: "Up to 14 panels / min",
    cncAxes: "6-axis CNC",
    imgId: "product-mf-3200-2e8a3f",
    titleId: "product-mf-3200-title",
    descId: "product-mf-3200-desc",
    features: [
      "Reinforced welded frame, low deflection",
      "Crowning compensation across full bed",
      "Tool library with 200+ stored profiles",
      "Industrial Ethernet & ERP integration",
    ],
  },
  {
    id: "mfx-1600",
    slug: "mfx-1600-metal-folder",
    name: "MFX-1600 Metal Folder",
    tagline: "Metal folder",
    summary:
      "A compact metal folder for prototyping, signage and short-run fabrication. Easy to learn, precise enough for production.",
    capacity: "1,600 mm × 1.5 mm",
    bendType: "Single (up)",
    productivity: "Up to 28 panels / min",
    cncAxes: "2-axis CNC",
    imgId: "product-mfx-1600-c7d319",
    titleId: "product-mfx-1600-title",
    descId: "product-mfx-1600-desc",
    features: [
      "Single-operator workflow",
      "Quick-change tooling",
      "Energy-efficient servo drive",
      "Optional rear-stacking table",
    ],
  },
  {
    id: "df-pro-4000",
    slug: "df-pro-4000-double-folder",
    name: "DF-PRO 4000 Double Folder",
    tagline: "Double folder",
    summary:
      "Long-bed double folder for industrial roofing, cladding contractors and HVAC fabricators. 4 m capacity, hands-off automation.",
    capacity: "4,000 mm × 3.0 mm",
    bendType: "Up & down (double)",
    productivity: "Up to 12 panels / min",
    cncAxes: "7-axis CNC",
    imgId: "product-df-pro-4000-a51b08",
    titleId: "product-df-pro-4000-title",
    descId: "product-df-pro-4000-desc",
    features: [
      "Robotic sheet handling ready",
      "Auto-tool change between profiles",
      "Closed-loop quality monitoring",
      "Full safety enclosure & light curtains",
    ],
  },
  {
    id: "smf-2000",
    slug: "smf-2000-sheet-metal-folding-machine",
    name: "SMF-2000 Sheet Metal Folding Machine",
    tagline: "Sheet metal folding machine",
    summary:
      "Balanced sheet metal folding machine for kitchen, ventilation and electrical enclosure manufacturers. The middle ground between hand brake and full CNC.",
    capacity: "2,000 mm × 2.0 mm",
    bendType: "Single (up)",
    productivity: "Up to 24 panels / min",
    cncAxes: "3-axis CNC",
    imgId: "product-smf-2000-3d4e21",
    titleId: "product-smf-2000-title",
    descId: "product-smf-2000-desc",
    features: [
      "Intuitive 10\" touchscreen",
      "Step-by-step folding sequencer",
      "Sectional clamping fingers included",
      "Quiet operation under 72 dB",
    ],
  },
]

export const productsBySlug = Object.fromEntries(
  products.map((p) => [p.slug, p])
)
