const products = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    category: 'Earrings',
    subcategory: 'Cuffs & Climbers',
    price: 42,
    material: '18K Gold Plated',
    rating: 4.8,
    reviewCount: 124,
    description: 'A sculptural ear cuff with a single brilliant crystal accent that catches the light from every angle. Designed to be worn solo or stacked alongside other earrings for a curated look.',
    details: 'This demi-fine ear cuff is crafted from 18K gold-plated brass with a genuine cubic zirconia crystal accent. The open-back design allows for comfortable all-day wear without pinching.',
    care: 'Avoid contact with water, perfumes, and lotions. Store in the included Velmora pouch and polish gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Standard delivery: 5-7 business days. Express delivery: 2-3 business days. 30-day returns on all unworn jewelry.',
    images: [
      'https://placehold.co/800x1000/1a1512/d4a853?text=Vivid+Aura+01',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Vivid+Aura+02',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Vivid+Aura+03',
    ],
    colors: ['Gold', 'Silver'],
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    category: 'Necklaces',
    subcategory: 'Statement',
    price: 68,
    material: '18K Gold Plated',
    rating: 4.9,
    reviewCount: 87,
    description: 'A show-stopping floral necklace featuring a cascade of multicolor crystals set in warm gold plating. Designed to sit elegantly along the collarbone.',
    details: 'This statement necklace is crafted from 18K gold-plated brass with hand-set cubic zirconia crystals in amber, topaz, and clear. Adjustable chain: 40cm + 5cm extender.',
    care: 'Avoid contact with water, perfumes, and lotions. Store in the included Velmora pouch and polish gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Standard delivery: 5-7 business days. Express delivery: 2-3 business days. 30-day returns on all unworn jewelry.',
    images: [
      'https://placehold.co/800x1000/1a1512/d4a853?text=Flora+Nectar+01',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Flora+Nectar+02',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Flora+Nectar+03',
    ],
    colors: ['Gold', 'Silver'],
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    category: 'Earrings',
    subcategory: 'Huggies',
    price: 38,
    material: '18K Gold Plated',
    rating: 4.7,
    reviewCount: 203,
    description: 'Chunky dome huggie earrings with a smooth, rounded profile that hugs the earlobe beautifully. The ultimate everyday staple with an elevated feel.',
    details: 'These huggie earrings are crafted from 18K gold-plated brass with a high-polish finish. Inner diameter: 9mm. Secure click-back closure.',
    care: 'Avoid contact with water, perfumes, and lotions. Store in the included Velmora pouch and polish gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Standard delivery: 5-7 business days. Express delivery: 2-3 business days. 30-day returns on all unworn jewelry.',
    images: [
      'https://placehold.co/800x1000/1a1512/d4a853?text=Golden+Huggies+01',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Huggies+02',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Huggies+03',
    ],
    colors: ['Gold', 'Silver'],
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    category: 'Earrings',
    subcategory: 'Drop',
    price: 54,
    material: '18K Gold Plated',
    rating: 4.6,
    reviewCount: 98,
    description: 'Intricate filigree drop earrings with a textured lace-like pattern in warm gold. Lightweight yet substantial, they frame the face with effortless elegance.',
    details: 'These drop earrings are crafted from 18K gold-plated brass with a hand-engraved filigree texture. Length: 4.5cm. Push-back closure.',
    care: 'Avoid contact with water, perfumes, and lotions. Store in the included Velmora pouch and polish gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Standard delivery: 5-7 business days. Express delivery: 2-3 business days. 30-day returns on all unworn jewelry.',
    images: [
      'https://placehold.co/800x1000/1a1512/d4a853?text=Amber+Lace+01',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Amber+Lace+02',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Amber+Lace+03',
    ],
    colors: ['Gold', 'Silver'],
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    category: 'Sets',
    subcategory: 'Gift Sets',
    price: 95,
    material: '18K Gold Plated',
    rating: 5.0,
    reviewCount: 56,
    description: 'A perfectly paired earring and necklace set presented in a gift-ready Velmora box. The coordinated design makes it the ultimate elevated gifting choice.',
    details: 'This gift set includes one pair of stud earrings and a matching pendant necklace, both crafted from 18K gold-plated brass with crystal accents. Presented in a velvet-lined Velmora gift box.',
    care: 'Avoid contact with water, perfumes, and lotions. Store in the included Velmora pouch and polish gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Standard delivery: 5-7 business days. Express delivery: 2-3 business days. 30-day returns on all unworn jewelry.',
    images: [
      'https://placehold.co/800x1000/1a1512/d4a853?text=Royal+Heirloom+01',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Heirloom+02',
      'https://placehold.co/800x1000/1a1512/d4a853?text=Heirloom+03',
    ],
    colors: ['Gold', 'Silver'],
  },
];

export default products;
