export const PRODUCTS = [
  {
    id: "af-2500",
    slug: "double-folding-machine-af-2500",
    name: "AF-2500 Double Folder",
    category: "Double Folding Machine",
    tagline: "Bidirectional precision for complex profiles",
    description:
      "Our flagship double folding machine produces up and down bends without flipping the workpiece. Ideal for architectural panels, ductwork, and high-mix sheet metal production.",
    capacity: "2500 mm length · 1.5 mm mild steel",
    bend: "Up & down · ±145°",
    drive: "Servo-electric",
    titleId: "product-af2500-title",
    descId: "product-af2500-desc",
    imgId: "product-af2500-img-7c1f3a",
  },
  {
    id: "af-3200",
    slug: "double-folder-af-3200",
    name: "AF-3200 Double Folder",
    category: "Double Folder",
    tagline: "Wide-format double bending for industrial workshops",
    description:
      "Built for fabricators handling longer panels, the AF-3200 combines a heavy steel frame with our signature dual-blade folding head for repeatable, mirror-clean bends.",
    capacity: "3200 mm length · 2.0 mm mild steel",
    bend: "Up & down · ±145°",
    drive: "Servo-hydraulic hybrid",
    titleId: "product-af3200-title",
    descId: "product-af3200-desc",
    imgId: "product-af3200-img-9b2e44",
  },
  {
    id: "sf-1600",
    slug: "sheet-metal-folder-sf-1600",
    name: "SF-1600 Sheet Metal Folder",
    category: "Sheet Metal Folder",
    tagline: "Compact studio folder for fine work",
    description:
      "A refined sheet metal folder for jewelry-grade architectural detailing. Quiet, accurate, and beautifully proportioned for smaller workshops and design studios.",
    capacity: "1600 mm length · 1.2 mm mild steel",
    bend: "Single direction · ±135°",
    drive: "Manual + electric assist",
    titleId: "product-sf1600-title",
    descId: "product-sf1600-desc",
    imgId: "product-sf1600-img-5d8a12",
  },
  {
    id: "sf-2050",
    slug: "sheet-metal-folding-machine-sf-2050",
    name: "SF-2050 Sheet Metal Folding Machine",
    category: "Sheet Metal Folding Machine",
    tagline: "The everyday workhorse, refined",
    description:
      "Our most popular folder. Programmable backgauge, touchscreen control, and a precision-ground beam deliver consistent results shift after shift.",
    capacity: "2050 mm length · 1.5 mm mild steel",
    bend: "Single direction · ±145°",
    drive: "Servo-electric",
    titleId: "product-sf2050-title",
    descId: "product-sf2050-desc",
    imgId: "product-sf2050-img-2f7c91",
  },
  {
    id: "mf-2500",
    slug: "metal-folder-mf-2500",
    name: "MF-2500 Metal Folder",
    category: "Metal Folder",
    tagline: "Engineered for stainless and aluminum",
    description:
      "A specialist metal folder calibrated for stainless, aluminum, and coated panels. Anti-marking tooling protects finished surfaces from start to finish.",
    capacity: "2500 mm length · 2.0 mm stainless steel",
    bend: "Single direction · ±150°",
    drive: "Servo-electric",
    titleId: "product-mf2500-title",
    descId: "product-mf2500-desc",
    imgId: "product-mf2500-img-c4e631",
  },
  {
    id: "mf-3200x",
    slug: "metal-folding-machine-mf-3200x",
    name: "MF-3200X Metal Folding Machine",
    category: "Metal Folder Machine",
    tagline: "Heavy-gauge precision at scale",
    description:
      "When projects demand thicker plate and longer panels, the MF-3200X delivers. CNC backgauge, automatic crowning, and a rigid welded frame for production environments.",
    capacity: "3200 mm length · 2.5 mm mild steel",
    bend: "Single direction · ±145°",
    drive: "Servo-hydraulic",
    titleId: "product-mf3200x-title",
    descId: "product-mf3200x-desc",
    imgId: "product-mf3200x-img-a91b08",
  },
];

export const PRODUCT_INTEREST_OPTIONS = [
  { value: "double-folding-machine", label: "Double folding machine" },
  { value: "sheet-metal-folder", label: "Sheet metal folder" },
  { value: "metal-folder-machine", label: "Metal folder / metal folding machine" },
  { value: "custom-solution", label: "Custom solution" },
  { value: "general-inquiry", label: "General inquiry" },
];
