export const STORIES = [
  {
    id: 'yanomami',
    slug: 'yanomami',
    chapter: 'Chapter I',
    title: 'The Yanomami',
    subtitle: 'Guardians of the Amazon',
    location: 'Amazon Basin, Brazil & Venezuela',
    region: 'South America',
    year: '2023',
    heroDesc: 'Yanomami indigenous people Amazon rainforest Brazil portrait',
    coverDesc: 'Amazon rainforest aerial canopy green lush Brazil',
    quote: 'The sky is our ceiling, the river our road, the forest our home.',
    attribution: 'Yanomami Elder',
    body: [
      'Deep within the Amazon Basin, the Yanomami people have lived in harmony with one of the world\'s most biodiverse ecosystems for thousands of years. Their villages, called shabonos, are circular communal structures that mirror the shape of the forest canopy above.',
      'The Yanomami\'s relationship with the forest is not one of ownership but of kinship. Every plant, animal, and river spirit is considered a relative. Their shamans, the xapiri, communicate with these spirits to maintain the balance between the human and natural worlds.',
      'Today, illegal gold mining threatens both the Yanomami people and the Amazon itself. Mercury contamination poisons rivers, and deforestation fractures the ancient web of life that has sustained this civilization for millennia.',
    ],
    images: [
      { id: 'yanomami-1', desc: 'Yanomami shaman ritual ceremony Amazon forest', ratio: '3x2', width: 900 },
      { id: 'yanomami-2', desc: 'Amazon river reflection canoe indigenous', ratio: '16x9', width: 1200 },
      { id: 'yanomami-3', desc: 'Yanomami child face portrait close-up', ratio: '3x4', width: 700 },
      { id: 'yanomami-4', desc: 'Amazon rainforest floor plants macro green', ratio: '4x3', width: 800 },
    ],
    color: '#4A6741',
    bgColor: '#C8DFC4',
  },
  {
    id: 'maasai',
    slug: 'maasai',
    chapter: 'Chapter II',
    title: 'The Maasai',
    subtitle: 'Children of the Savanna',
    location: 'Rift Valley, Kenya & Tanzania',
    region: 'East Africa',
    year: '2023',
    heroDesc: 'Maasai warrior Kenya savanna landscape portrait',
    coverDesc: 'African savanna sunset acacia tree Kenya landscape',
    quote: 'The cattle are our heartbeat. The land is our memory.',
    attribution: 'Maasai Elder, Amboseli',
    body: [
      'Across the vast savannas of Kenya and Tanzania, the Maasai people have maintained a semi-nomadic pastoral lifestyle for centuries. Their deep knowledge of the land — its seasons, its animals, its hidden water sources — is encoded in oral traditions passed from generation to generation.',
      'The Maasai\'s relationship with cattle is sacred. Cattle are not merely livestock but a living currency, a spiritual connection, and a measure of a family\'s wealth and status. The health of the herd mirrors the health of the community.',
      'Climate change is reshaping the savanna. Droughts grow longer, rains more unpredictable. The Maasai are adapting, blending ancient knowledge with new conservation practices to protect both their way of life and the ecosystems they have stewarded for generations.',
    ],
    images: [
      { id: 'maasai-1', desc: 'Maasai warrior jumping ceremony red shuka', ratio: '3x4', width: 700 },
      { id: 'maasai-2', desc: 'African savanna elephant herd sunset golden', ratio: '16x9', width: 1200 },
      { id: 'maasai-3', desc: 'Maasai woman beaded jewelry portrait close-up', ratio: '3x2', width: 900 },
      { id: 'maasai-4', desc: 'Kenya savanna grass plains wide landscape', ratio: '4x3', width: 800 },
    ],
    color: '#8B6F5E',
    bgColor: '#E8D5C4',
  },
  {
    id: 'inuit',
    slug: 'inuit',
    chapter: 'Chapter III',
    title: 'The Inuit',
    subtitle: 'Voices of the Melting Ice',
    location: 'Nunavut, Canada & Greenland',
    region: 'Arctic',
    year: '2024',
    heroDesc: 'Inuit elder Arctic ice landscape portrait Canada',
    coverDesc: 'Arctic ice landscape aurora borealis Greenland',
    quote: 'The ice speaks. We have always known how to listen.',
    attribution: 'Inuit Hunter, Nunavut',
    body: [
      'In the Arctic, the Inuit people have developed one of the most sophisticated relationships with a harsh environment in human history. Their language contains dozens of words for different types of snow and ice — a vocabulary born from millennia of careful observation.',
      'The Inuit\'s traditional knowledge, called Inuit Qaujimajatuqangit, encompasses everything from weather prediction to animal behavior, navigation to medicinal plants. This knowledge system is as complex and nuanced as any scientific discipline.',
      'The Arctic is warming four times faster than the global average. Sea ice that Inuit hunters have relied upon for generations is becoming unpredictable and dangerous. The loss of ice is not just an environmental crisis — it is a cultural one.',
    ],
    images: [
      { id: 'inuit-1', desc: 'Inuit hunter Arctic sea ice polar landscape', ratio: '16x9', width: 1200 },
      { id: 'inuit-2', desc: 'Arctic polar bear ice floe ocean', ratio: '3x2', width: 900 },
      { id: 'inuit-3', desc: 'Inuit child face portrait fur hood close-up', ratio: '3x4', width: 700 },
      { id: 'inuit-4', desc: 'Arctic tundra landscape snow ice blue sky', ratio: '4x3', width: 800 },
    ],
    color: '#4A7A8A',
    bgColor: '#C8DFC4',
  },
  {
    id: 'hmong',
    slug: 'hmong',
    chapter: 'Chapter IV',
    title: 'The Hmong',
    subtitle: 'Weavers of Mountain and Sky',
    location: 'Northern Vietnam & Laos',
    region: 'Southeast Asia',
    year: '2024',
    heroDesc: 'Hmong woman traditional costume Vietnam mountain',
    coverDesc: 'Vietnam mountain terraced rice fields mist fog',
    quote: 'Our embroidery is a map of the mountains we carry inside us.',
    attribution: 'Hmong Weaver, Sapa',
    body: [
      'High in the mountains of northern Vietnam and Laos, the Hmong people have cultivated terraced rice fields for centuries, transforming steep hillsides into cascading gardens that feed both body and spirit. Their agricultural knowledge is inseparable from their spiritual practice.',
      'Hmong textile art is a form of environmental storytelling. The intricate patterns embroidered on clothing and ceremonial objects encode knowledge about plants, animals, and landscapes — a visual language that preserves ecological memory across generations.',
      'Rapid modernization and climate-driven changes in rainfall patterns are challenging traditional farming practices. Yet the Hmong continue to adapt, finding ways to honor ancestral knowledge while navigating a changing world.',
    ],
    images: [
      { id: 'hmong-1', desc: 'Hmong woman embroidery textile traditional Vietnam', ratio: '3x4', width: 700 },
      { id: 'hmong-2', desc: 'Vietnam rice terraces aerial Sapa green', ratio: '16x9', width: 1200 },
      { id: 'hmong-3', desc: 'Hmong market colorful traditional dress', ratio: '3x2', width: 900 },
      { id: 'hmong-4', desc: 'Mountain mist fog forest Vietnam landscape', ratio: '4x3', width: 800 },
    ],
    color: '#6B8F5E',
    bgColor: '#A8C5A0',
  },
];
