export const products = [
  {
    id: "double-folding-machine",
    name: "Double Folding Machine",
    tagline: "Two-stage bending for complex profiles in a single setup.",
    capacity: "Up to 6 mm mild steel",
    length: "2,000 – 4,000 mm",
    features: ["Synchronized upper & lower beams", "CNC back-gauge option", "Hydraulic crowning"],
  },
  {
    id: "double-folder",
    name: "Double Folder",
    tagline: "Compact, high-speed folder for small-to-medium profiles.",
    capacity: "Up to 4 mm mild steel",
    length: "1,250 – 2,500 mm",
    features: ["Finger-safe design", "Quick-change tooling", "Foot pedal control"],
  },
  {
    id: "sheet-metal-folder",
    name: "Sheet Metal Folder",
    tagline: "Reliable manual and powered folders for every shop.",
    capacity: "Up to 3 mm mild steel",
    length: "1,000 – 3,000 mm",
    features: ["Segmented bending fingers", "Adjustable jaw opening", "Low maintenance"],
  },
  {
    id: "metal-folder",
    name: "Metal Folder",
    tagline: "Versatile entry-level folder with professional results.",
    capacity: "Up to 2.5 mm mild steel",
    length: "1,000 – 2,000 mm",
    features: ["Lightweight frame", "Precision depth stops", "Ideal for prototyping"],
  },
  {
    id: "metal-folder-machine",
    name: "Metal Folder Machine",
    tagline: "Heavy-duty folder built for continuous production.",
    capacity: "Up to 5 mm mild steel",
    length: "2,000 – 3,200 mm",
    features: ["Industrial gearbox drive", "Reinforced table", "Programmable angles"],
  },
  {
    id: "sheet-metal-folding-machine",
    name: "Sheet Metal Folding Machine",
    tagline: "Automated folding with repeatable accuracy.",
    capacity: "Up to 6 mm mild steel",
    length: "2,500 – 4,000 mm",
    features: ["Servo-electric bending", "Automatic tool changer", "Industry 4.0 ready"],
  },
]
