export const products = [
  {
    id: 'd-series',
    slug: 'd-series-double-folder',
    name: 'Artitect D-Series Double Folder',
    tagline: 'Up & down folding in one elegant cycle',
    category: 'Double folding machine',
    description:
      'Our flagship double folder forms positive and negative bends without ever flipping the sheet. Twin servo-driven beams move in perfect symmetry for tight box panels, façade cassettes, and complex profiles.',
    specs: [
      { label: 'Max sheet length', value: '3,200 mm' },
      { label: 'Max bend thickness', value: '2.0 mm steel' },
      { label: 'Bend angle range', value: '–145° to +145°' },
      { label: 'Repeatability', value: '±0.05 mm' },
    ],
    titleId: 'product-d-series-title',
    descId: 'product-d-series-desc',
    imgId: 'product-d-series-img-7c2a9b',
    accent: 'Flagship',
  },
  {
    id: 's-series',
    slug: 's-series-sheet-metal-folder',
    name: 'Artitect S-Series Sheet Metal Folder',
    tagline: 'Workshop staple for clean, repeatable bends',
    category: 'Sheet metal folder',
    description:
      'A versatile single-beam folder built for daily fabrication work. The S-Series pairs an oversized welded frame with intuitive touchscreen control for confident, repeatable bends in mild steel, stainless, and aluminum.',
    specs: [
      { label: 'Max sheet length', value: '2,500 mm' },
      { label: 'Max bend thickness', value: '1.5 mm steel' },
      { label: 'Bend angle range', value: '0° to 135°' },
      { label: 'Repeatability', value: '±0.08 mm' },
    ],
    titleId: 'product-s-series-title',
    descId: 'product-s-series-desc',
    imgId: 'product-s-series-img-b14e7d',
    accent: 'Best Seller',
  },
  {
    id: 'm-series',
    slug: 'm-series-metal-folder',
    name: 'Artitect M-Series Metal Folder',
    tagline: 'Heavy-gauge folding without compromise',
    category: 'Metal folder',
    description:
      'When the job calls for thicker material, the M-Series steps up. A reinforced clamping beam and high-torque drive deliver crisp 90° folds in 3 mm mild steel — quietly, and all day long.',
    specs: [
      { label: 'Max sheet length', value: '4,000 mm' },
      { label: 'Max bend thickness', value: '3.0 mm steel' },
      { label: 'Bend angle range', value: '0° to 140°' },
      { label: 'Repeatability', value: '±0.07 mm' },
    ],
    titleId: 'product-m-series-title',
    descId: 'product-m-series-desc',
    imgId: 'product-m-series-img-3f9c12',
    accent: 'Heavy Duty',
  },
  {
    id: 'a-series',
    slug: 'a-series-metal-folding-machine',
    name: 'Artitect A-Series Metal Folding Machine',
    tagline: 'Automation, ready out of the box',
    category: 'Metal folding machine',
    description:
      'Programmable backgauges, automatic crowning, and recipe storage turn complex parts into a one-button operation. Built for series production where every cycle has to look like the first.',
    specs: [
      { label: 'Max sheet length', value: '3,200 mm' },
      { label: 'Max bend thickness', value: '2.5 mm steel' },
      { label: 'Stored programs', value: '500+' },
      { label: 'Repeatability', value: '±0.05 mm' },
    ],
    titleId: 'product-a-series-title',
    descId: 'product-a-series-desc',
    imgId: 'product-a-series-img-58d041',
    accent: 'Automated',
  },
  {
    id: 'c-series',
    slug: 'c-series-compact-folder',
    name: 'Artitect C-Series Compact Folder',
    tagline: 'Studio-friendly, workshop-tough',
    category: 'Sheet metal folding machine',
    description:
      'A compact folder that slides into smaller shops without losing the Artitect feel. Quiet operation, intuitive controls, and the same hardened tooling as our larger machines.',
    specs: [
      { label: 'Max sheet length', value: '1,600 mm' },
      { label: 'Max bend thickness', value: '1.2 mm steel' },
      { label: 'Footprint', value: '2.2 × 1.4 m' },
      { label: 'Repeatability', value: '±0.08 mm' },
    ],
    titleId: 'product-c-series-title',
    descId: 'product-c-series-desc',
    imgId: 'product-c-series-img-aa7b29',
    accent: 'Compact',
  },
  {
    id: 'x-series',
    slug: 'x-series-double-folder',
    name: 'Artitect X-Series Long Double Folder',
    tagline: 'Architectural lengths, architectural detail',
    category: 'Double folder',
    description:
      'Engineered for façade panels and architectural cladding, the X-Series handles long sheets while preserving the crisp, sharp lines that designers demand.',
    specs: [
      { label: 'Max sheet length', value: '6,000 mm' },
      { label: 'Max bend thickness', value: '1.5 mm steel' },
      { label: 'Bend angle range', value: '–145° to +145°' },
      { label: 'Repeatability', value: '±0.06 mm' },
    ],
    titleId: 'product-x-series-title',
    descId: 'product-x-series-desc',
    imgId: 'product-x-series-img-d62fa8',
    accent: 'Architectural',
  },
]
