/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'accent-champagne',
    'bg-champagne',
    'bg-champagne/20',
    'bg-ivory',
    'bg-porcelain',
    'bg-velvet',
    'border-truffle/10',
    'border-truffle/15',
    'border-truffle/20',
    'border-velvet/20',
    'focus:border-champagne',
    'font-editorial',
    'from-velvet',
    'from-velvet/85',
    'hover:bg-velvet',
    'hover:border-champagne',
    'hover:border-champagne/40',
    'hover:text-champagne',
    'hover:text-porcelain',
    'hover:text-velvet',
    'placeholder:text-truffle',
    'placeholder:text-truffle/70',
    'shadow-card',
    'shadow-soft',
    'text-champagne',
    'text-ivory',
    'text-porcelain',
    'text-truffle',
    'text-velvet',
    'to-velvet/35',
    'via-velvet/10',
    'via-velvet/70',
    'via-velvet/75',
  ],
  theme: {
    extend: {
      colors: {
        velvet: '#211b18',
        espresso: '#4d4038',
        truffle: '#7b675b',
        champagne: '#b8925e',
        rosegold: '#d2b08d',
        porcelain: '#f6f1eb',
        bone: '#ede4da',
        ivory: '#fffdf9',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        editorial: ['Cormorant Garamond', 'serif'],
      },
      boxShadow: {
        soft: '0 20px 60px rgba(33, 27, 24, 0.08)',
        card: '0 16px 40px rgba(33, 27, 24, 0.08)',
      },
      letterSpacing: {
        luxe: '0.32em',
      },
    },
  },
  plugins: [],
}
