// Content data for the MicroCosmos single-page site.
// Each item carries explicit titleId / descId so image queries can reference
// the exact DOM ids that will be rendered.

export const specimens = [
  {
    id: 'tardigrade',
    slug: 'tardigrade',
    title: 'Tardigrade',
    latin: 'Hypsibius dujardini',
    desc: 'A near-indestructible micro-animal that survives freezing, boiling, and the vacuum of space by entering a desiccated tun state.',
    scale: '0.5 mm',
    habitat: 'Moss & lichen',
    imgId: 'spec-tardigrade-a1b2c3',
    titleId: 'spec-tardigrade-title',
    descId: 'spec-tardigrade-desc',
  },
  {
    id: 'diatom',
    slug: 'diatom',
    title: 'Diatom',
    latin: 'Coscinodiscus sp.',
    desc: 'Single-celled algae encased in glass shells of silica, forming intricate geometric lattice patterns visible only under magnification.',
    scale: '0.2 mm',
    habitat: 'Oceans & freshwater',
    imgId: 'spec-diatom-d4e5f6',
    titleId: 'spec-diatom-title',
    descId: 'spec-diatom-desc',
  },
  {
    id: 'rotifer',
    slug: 'rotifer',
    title: 'Rotifer',
    latin: 'Brachionus calyciflorus',
    desc: 'A tiny wheel-animalcule whose crown of beating cilia creates currents that sweep food into its mouth.',
    scale: '0.4 mm',
    habitat: 'Ponds & puddles',
    imgId: 'spec-rotifer-g7h8i9',
    titleId: 'spec-rotifer-title',
    descId: 'spec-rotifer-desc',
  },
  {
    id: 'paramecium',
    slug: 'paramecium',
    title: 'Paramecium',
    latin: 'Paramecium caudatum',
    desc: 'A slipper-shaped ciliate that glides through water on thousands of tiny oars, hunting bacteria with chemical senses.',
    scale: '0.25 mm',
    habitat: 'Freshwater',
    imgId: 'spec-paramecium-j1k2l3',
    titleId: 'spec-paramecium-title',
    descId: 'spec-paramecium-desc',
  },
  {
    id: 'water-bear-moss',
    slug: 'water-bear-moss',
    title: 'Water Bear in Moss',
    latin: 'Macrobiotus sp.',
    desc: 'Tardigrades roam the thin films of water clinging to moss leaves, an entire ecosystem in a dewdrop.',
    scale: '0.3 mm',
    habitat: 'Forest floor',
    imgId: 'spec-waterbear-moss-m4n5o6',
    titleId: 'spec-waterbear-moss-title',
    descId: 'spec-waterbear-moss-desc',
  },
  {
    id: 'volvox',
    slug: 'volvox',
    title: 'Volvox Colony',
    latin: 'Volvox aureus',
    desc: 'Thousands of green cells unite into a hollow rolling sphere, a bridge between single cells and multicellular life.',
    scale: '0.5 mm',
    habitat: 'Still ponds',
    imgId: 'spec-volvox-p7q8r9',
    titleId: 'spec-volvox-title',
    descId: 'spec-volvox-desc',
  },
]

export const habitats = [
  {
    id: 'pond-water',
    title: 'Pond Water',
    desc: 'A single drop teems with ciliates, rotifers, and algae, the most accessible window into the micro-world.',
    imgId: 'hab-pond-s1t2u3',
    titleId: 'hab-pond-title',
    descId: 'hab-pond-desc',
  },
  {
    id: 'soil',
    title: 'Forest Soil',
    desc: 'A handful of earth holds nematodes, mites, and fungal threads that recycle all fallen life.',
    imgId: 'hab-soil-v4w5x6',
    titleId: 'hab-soil-title',
    descId: 'hab-soil-desc',
  },
  {
    id: 'human-skin',
    title: 'Human Skin',
    desc: 'Our largest organ is a landscape of pores and flakes, home to a quiet civilization of microbes.',
    imgId: 'hab-skin-y7z8a9',
    titleId: 'hab-skin-title',
    descId: 'hab-skin-desc',
  },
  {
    id: 'ocean',
    title: 'Open Ocean',
    desc: 'Every milliliter of seawater carries plankton and bacteria that produce half the oxygen we breathe.',
    imgId: 'hab-ocean-b1c2d3',
    titleId: 'hab-ocean-title',
    descId: 'hab-ocean-desc',
  },
]

export const gallery = [
  {
    id: 'crystal-snowflake',
    title: 'Crystalline Symmetry',
    desc: 'A snowflake crystal under polarized light reveals nature hidden geometry.',
    imgId: 'gal-crystal-e4f5g6',
    titleId: 'gal-crystal-title',
    descId: 'gal-crystal-desc',
  },
  {
    id: 'pollen-grains',
    title: 'Pollen Grains',
    desc: 'Flower pollen sculpted into spiky spheres, each species carrying a unique fingerprint.',
    imgId: 'gal-pollen-h7i8j9',
    titleId: 'gal-pollen-title',
    descId: 'gal-pollen-desc',
  },
  {
    id: 'butterfly-scale',
    title: 'Butterfly Scales',
    desc: 'Iridescent scales tile a wing like a stained-glass roof, scattering light into color.',
    imgId: 'gal-scale-k1l2m3',
    titleId: 'gal-scale-title',
    descId: 'gal-scale-desc',
  },
  {
    id: 'spider-silk',
    title: 'Spider Silk',
    desc: 'A strand of silk stretched across a frame, stronger by weight than steel.',
    imgId: 'gal-silk-n4o5p6',
    titleId: 'gal-silk-title',
    descId: 'gal-silk-desc',
  },
  {
    id: 'insect-eye',
    title: 'Compound Eye',
    desc: 'Thousands of tiny lenses mosaic a fly view of the world.',
    imgId: 'gal-eye-q7r8s9',
    titleId: 'gal-eye-title',
    descId: 'gal-eye-desc',
  },
  {
    id: 'leaf-stomata',
    title: 'Leaf Stomata',
    desc: 'Breathing pores on a leaf surface open and close to trade gases with the air.',
    imgId: 'gal-stomata-t1u2v3',
    titleId: 'gal-stomata-title',
    descId: 'gal-stomata-desc',
  },
  {
    id: 'fungi-hyphae',
    title: 'Fungal Hyphae',
    desc: 'Branching threads of a fungus spread through soil, the hidden internet of the forest.',
    imgId: 'gal-fungi-w4x5y6',
    titleId: 'gal-fungi-title',
    descId: 'gal-fungi-desc',
  },
  {
    id: 'blood-cells',
    title: 'Red Blood Cells',
    desc: 'Biconcave discs crowd a capillary, ferrying oxygen to every corner of the body.',
    imgId: 'gal-blood-z7a8b9',
    titleId: 'gal-blood-title',
    descId: 'gal-blood-desc',
  },
]

export const stats = [
  { value: '1M+', label: 'Species unseen by the naked eye' },
  { value: '0.1mm', label: 'Where the micro-world begins' },
  { value: '50%', label: 'Of Earth oxygen made by microbes' },
  { value: '4B', label: 'Years life has lived at this scale' },
]
