export const strings = {
  en: {
    hero: {
      h1_line1: "BUILD ANY KIND OF SITE",
      h1_line2: "WITH AI, IN AN INSTANT",
      subheadline: "Browse the right generator for what you're building, or jump straight into our AI site builder.",
      cta_primary: "START BUILDING - IT'S FREE",
      cta_secondary: "BROWSE GENERATORS",
    },
    featured: {
      title: "FEATURED GENERATORS",
      subtitle: "A few common starting points.",
    },
    browseByCategory: {
      title: "BROWSE BY CATEGORY",
      categories: [
        { id: "websites", name: "Websites", description: "AI-built business and personal sites for any goal.", slug: "websites" },
        { id: "landing-pages", name: "Landing Pages", description: "Single-page sites built to convert visitors fast.", slug: "landing-pages" },
        { id: "portfolios", name: "Portfolios", description: "Showcase your work with a clean, focused site.", slug: "portfolios" },
        { id: "blogs", name: "Blogs", description: "Publish-ready blogs with built-in SEO basics.", slug: "blogs" },
        { id: "stores", name: "Online Stores", description: "Sell products online with payments built in.", slug: "stores" },
        { id: "link-in-bio", name: "Link-in-Bio", description: "One link, all your places. Made for creators.", slug: "link-in-bio" },
      ]
    },
    allGenerators: {
      title: "ALL GENERATORS",
      subtitle: "Sixty-plus generators, organized by what you're building.",
      searchPlaceholder: "Search generators...",
      matchCount: (count) => `${count} generators match`,
      noResults: "Can't find it? Start with our AI builder.",
      clearSearch: "Clear search",
      showAll: (count) => `Show all ${count} generators`,
    },
    howItWorks: {
      title: "HOW IT WORKS",
      steps: [
        { title: "PICK A GENERATOR", description: "Browse by category or search to find one that fits your goal." },
        { title: "DESCRIBE YOUR SITE", description: "Tell our AI builder about your business in a sentence or two." },
        { title: "GENERATE AND PUBLISH", description: "Get a fully built site in seconds. Customize anything, then go live." },
      ]
    },
    whyStrikingly: {
      title: "WHY STRIKINGLY",
      features: [
        { title: "LIVE IN SECONDS", description: "Describe your site, we build it. No setup, no learning curve." },
        { title: "MOBILE BY DEFAULT", description: "Every generator produces responsive sites that work on any device." },
        { title: "FREE TO START", description: "Generate, customize, and publish without a credit card." },
      ]
    },
    faq: {
      title: "FREQUENTLY ASKED QUESTIONS",
      questions: [
        { q: "What is an AI site generator?", a: "An AI site generator is a tool that uses artificial intelligence to create a complete website based on a simple text description. It handles the layout, design, and initial content, saving you hours of manual work." },
        { q: "How is a generator different from a template?", a: "While templates provide a static starting point, our AI generators build a custom site tailored specifically to your description. It picks the best components and arranges them in a way that makes sense for your specific goal." },
        { q: "Are these generators free to use?", a: "Yes, you can generate and customize your site for free. Strikingly offers a free tier that allows you to publish your site without a credit card." },
        { q: "What kinds of sites can I build?", a: "You can build almost anything! From business websites and portfolios to landing pages, blogs, and online stores. Our broad range of generators covers most common use cases." },
        { q: "Can I customize what the generator produces?", a: "Absolutely. Once the AI has generated the initial site, you can use our intuitive drag-and-drop editor to change text, images, colors, and layout until it's exactly how you want it." },
        { q: "Do generated sites work on mobile?", a: "Yes, every site generated by Strikingly is mobile-responsive by default. Your site will look great and function perfectly on desktops, tablets, and smartphones." },
      ]
    },
    closingCTA: {
      title: "READY TO BUILD?",
      subtitle: "Pick a generator above, or jump straight into our AI builder.",
      cta: "START WITH AI BUILDER",
    },
    footerPlaceholder: {
      about: "/about",
      pricing: "/pricing",
      templates: "/templates",
      support: "/support",
      blog: "/blog",
      terms: "/terms",
      privacy: "/privacy",
    }
  }
};

export const featuredGenerators = [
  { name: "AI Website Generator", description: "Describe your business, get a full site", category: "Website", slug: "ai-website-generator" },
  { name: "Free Portfolio Generator", description: "For creatives, in minutes, no fee", category: "Portfolio", slug: "free-portfolio-generator" },
  { name: "AI Landing Page Maker", description: "One-page sites built to convert", category: "Landing Page", slug: "ai-landing-page-maker" },
  { name: "Online Store Builder", description: "Start selling without writing code", category: "Store", slug: "online-store-builder" },
  { name: "Link-in-Bio Generator", description: "One link for all your channels", category: "Link-in-Bio", slug: "link-in-bio-generator" },
  { name: "One-Page Website Builder", description: "Simple sites, single scroll", category: "Website", slug: "one-page-website-builder" },
  { name: "Wedding Website Generator", description: "Share your day with guests", category: "Website", slug: "wedding-website-generator" },
  { name: "Restaurant Website Builder", description: "Menu, hours, reservations, done", category: "Website", slug: "restaurant-website-builder" },
  { name: "Blog Generator for Beginners", description: "Publish-ready in minutes", category: "Blog", slug: "blog-generator-for-beginners" },
];

export const allGeneratorsData = {
  websites: [
    { name: "AI Website Generator", description: "Get a full business website in seconds.", slug: "ai-website-generator" },
    { name: "Free Website Builder for Photographers", description: "Showcase your photos with a stunning site.", slug: "photographer-website" },
    { name: "Small Business Website Maker", description: "Build a professional presence for your company.", slug: "small-business-website" },
    { name: "Personal Website Generator", description: "Create your own corner of the internet.", slug: "personal-website" },
    { name: "One-Page Website Builder", description: "Simple, scrollable sites for any purpose.", slug: "one-page-website" },
    { name: "Wedding Website Generator", description: "Share details of your big day with loved ones.", slug: "wedding-website" },
    { name: "Restaurant Website Builder", description: "Menu, hours, and booking for your eatery.", slug: "restaurant-website" },
    { name: "Real Estate Website Maker", description: "List properties and capture leads easily.", slug: "real-estate-website" },
    { name: "Dental Practice Website Generator", description: "Professional sites for dental clinics.", slug: "dental-clinic-website" },
    { name: "Consultant Website Builder", description: "Display your expertise and book clients.", slug: "consultant-website" },
  ],
  "landing-pages": [
    { name: "AI Landing Page Maker", description: "Highly converting pages made in an instant.", slug: "ai-landing-page" },
    { name: "SaaS Landing Page Generator", description: "Perfect for software products and apps.", slug: "saas-landing-page" },
    { name: "Ebook Landing Page Builder", description: "Sell your digital books with ease.", slug: "ebook-landing-page" },
    { name: "Event RSVP Page Maker", description: "Collect registrations for your next event.", slug: "event-landing-page" },
    { name: "Product Launch Page Generator", description: "Build hype for your new product.", slug: "product-launch-page" },
    { name: "Webinar Lead Page Builder", description: "Get more signups for your online sessions.", slug: "webinar-landing-page" },
    { name: "Coming Soon Page Generator", description: "Capture interest before you launch.", slug: "coming-soon-page" },
    { name: "App Download Landing Page", description: "Promote your mobile app with a clean site.", slug: "app-landing-page" },
  ],
  portfolios: [
    { name: "Design Portfolio Generator", description: "Clean layouts for visual specialists.", slug: "designer-portfolio" },
    { name: "Photography Portfolio Maker", description: "Put your photos front and center.", slug: "photography-portfolio" },
    { name: "Writer Portfolio Builder", description: "Showcase your articles and stories.", slug: "writer-portfolio" },
    { name: "Developer Portfolio Generator", description: "Display your projects and code samples.", slug: "developer-portfolio" },
    { name: "Artist Portfolio Maker", description: "A digital gallery for your creative work.", slug: "artist-portfolio" },
    { name: "Architecture Portfolio Builder", description: "Present your structures and designs.", slug: "architect-portfolio" },
    { name: "Model Portfolio Generator", description: "Professional comp cards and galleries.", slug: "model-portfolio" },
    { name: "Student Portfolio Maker", description: "Land your first job with a great site.", slug: "student-portfolio" },
  ],
  blogs: [
    { name: "AI Blog Generator", description: "Start your writing journey with AI help.", slug: "ai-blog-generator" },
    { name: "Lifestyle Blog Maker", description: "Share your daily adventures and tips.", slug: "lifestyle-blog" },
    { name: "Tech Blog Builder", description: "Write about the latest in technology.", slug: "tech-blog" },
    { name: "Food Blog Generator", description: "Recipes and reviews made easy.", slug: "food-blog" },
    { name: "Travel Blog Maker", description: "Document your trips with beautiful posts.", slug: "travel-blog" },
    { name: "Fashion Blog Builder", description: "Showcase the latest trends and styles.", slug: "fashion-blog" },
    { name: "Professional Blog Generator", description: "Build thought leadership in your industry.", slug: "professional-blog" },
    { name: "Free Blog Builder for Beginners", description: "Simple setup for first-time bloggers.", slug: "beginner-blog" },
  ],
  stores: [
    { name: "AI Store Generator", description: "Start selling physical or digital goods.", slug: "ai-store-generator" },
    { name: "Clothing Store Builder", description: "Build your own fashion brand online.", slug: "clothing-store" },
    { name: "Digital Product Store Maker", description: "Sell files, courses, and more.", slug: "digital-product-store" },
    { name: "Jewelry Store Generator", description: "A sparkling showcase for your creations.", slug: "jewelry-store" },
    { name: "Furniture Store Builder", description: "Display your home decor and furniture.", slug: "furniture-store" },
    { name: "Subscription Box Site Maker", description: "Manage recurring orders easily.", slug: "subscription-store" },
    { name: "Beauty Product Store Generator", description: "Sell cosmetics and skincare products.", slug: "beauty-store" },
    { name: "Art Print Store Maker", description: "Sell your artworks as high-quality prints.", slug: "art-print-store" },
  ],
  "link-in-bio": [
    { name: "Link-in-Bio Generator", description: "One simple link for all your socials.", slug: "link-in-bio" },
    { name: "Instagram Bio Site Maker", description: "Perfect for IG creators and influencers.", slug: "instagram-bio" },
    { name: "TikTok Bio Landing Page Generator", description: "Drive TikTok traffic to your links.", slug: "tiktok-bio" },
    { name: "Creator Card Builder", description: "Your digital business card for the web.", slug: "creator-card" },
    { name: "Music Link Page Generator", description: "Share your tracks across all platforms.", slug: "music-bio" },
    { name: "Podcast Bio Site Maker", description: "Links to your latest episodes and shows.", slug: "podcast-bio" },
    { name: "YouTube Creator Bio Generator", description: "Promote your channel and merchandise.", slug: "youtube-bio" },
    { name: "Professional Bio Page Builder", description: "A polished landing page for your brand.", slug: "professional-bio" },
  ],
};
