import React from 'react'

export default function Footer() {
  return (
    <footer className="bg-muted py-12 border-t border-border mt-12">
      <div className="max-w-7xl mx-auto px-4 md:px-8 text-center text-muted-foreground">
        <h3 className="text-2xl font-bold mb-4 text-foreground">MicroCosmos</h3>
        <p className="mb-8 max-w-md mx-auto">
          Exploring the invisible world. All images on this site are generated by the Strikingly Stock System.
        </p>
        <div className="flex justify-center gap-6 text-sm">
          <a href="#" className="hover:text-primary transition-colors">Privacy Policy</a>
          <a href="#" className="hover:text-primary transition-colors">Terms of Service</a>
          <a href="#" className="hover:text-primary transition-colors">Contact</a>
        </div>
        <p className="mt-12 text-sm opacity-50">
          © {new Date().getFullYear()} MicroCosmos Explorer. All rights reserved.
        </p>
      </div>
    </footer>
  )
}
