import { useEffect, useRef } from 'react'
import { Cpu, Eye, Code2, Zap, RefreshCw, Lock } from 'lucide-react'
import { ImageHelper } from '@strikingly/sdk'
import strkImgConfig from '@/strk-img-config.json'

const capabilities = [
  {
    id: 'cap-nlp',
    icon: Cpu,
    title: 'Natural Language Processing',
    subtitle: 'Understands context, not just keywords',
    description:
      'Our NLP engine interprets your intent with nuance — understanding tone, industry context, and brand personality to generate content that truly resonates with your audience.',
    imgQuery: 'artificial intelligence natural language processing neural network',
    imgId: 'cap-nlp-img',
    reverse: false,
  },
  {
    id: 'cap-vision',
    icon: Eye,
    title: 'Visual Intelligence',
    subtitle: 'Design that thinks for itself',
    description:
      'NeuralBuild\'s visual AI analyzes thousands of top-performing websites in your industry to craft layouts, color systems, and typography hierarchies that convert.',
    imgQuery: 'modern UI design system minimalist interface',
    imgId: 'cap-vision-img',
    reverse: true,
  },
  {
    id: 'cap-code',
    icon: Code2,
    title: 'Clean Code Output',
    subtitle: 'Production-ready from day one',
    description:
      'Every site generated by NeuralBuild outputs semantic HTML, optimized CSS, and accessible markup — ready for developers to extend or deploy as-is.',
    imgQuery: 'clean code programming developer workspace',
    imgId: 'cap-code-img',
    reverse: false,
  },
]

const stats = [
  { value: '< 60s', label: 'Average generation time' },
  { value: '200+', label: 'Design templates' },
  { value: '98%', label: 'Accessibility score' },
  { value: '4.9/5', label: 'Customer satisfaction' },
]

const extras = [
  { icon: Zap, title: 'Instant previews', desc: 'See changes in real time as you describe them.' },
  { icon: RefreshCw, title: 'Iterative refinement', desc: 'Refine any section with follow-up prompts.' },
  { icon: Lock, title: 'Data privacy', desc: 'Your prompts and content are never used for training.' },
]

export default function AICapabilities() {
  const containerRef = useRef(null)

  useEffect(() => {
    ImageHelper.loadImages(strkImgConfig, containerRef.current)
  }, [])

  return (
    <section ref={containerRef} className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-20">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-indigo-50 border border-indigo-100 rounded-full text-indigo-600 text-xs font-semibold mb-4">
            Under the hood
          </div>
          <h2 id="capabilities-title" className="text-4xl font-bold text-slate-900 tracking-tight mb-4">
            AI capabilities built for the modern web
          </h2>
          <p id="capabilities-subtitle" className="text-slate-500 text-lg max-w-2xl mx-auto">
            NeuralBuild combines cutting-edge language models, visual AI, and web engineering to deliver sites that look handcrafted — at machine speed.
          </p>
        </div>

        {/* Stats bar */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-slate-100 rounded-2xl overflow-hidden mb-20 border border-slate-100">
          {stats.map((stat, i) => (
            <div key={i} className="bg-white px-6 py-6 text-center">
              <div className="text-3xl font-bold text-indigo-600 mb-1">{stat.value}</div>
              <div className="text-xs text-slate-500 font-medium">{stat.label}</div>
            </div>
          ))}
        </div>

        {/* Capability rows */}
        <div className="space-y-24">
          {capabilities.map((cap, i) => {
            const Icon = cap.icon
            return (
              <div
                key={cap.id}
                className={`grid lg:grid-cols-2 gap-12 items-center ${cap.reverse ? 'lg:grid-flow-dense' : ''}`}
              >
                {/* Text */}
                <div className={cap.reverse ? 'lg:col-start-2' : ''}>
                  <div className="inline-flex items-center gap-2 w-10 h-10 bg-indigo-50 rounded-xl mb-6 justify-center">
                    <Icon className="w-5 h-5 text-indigo-600" />
                  </div>
                  <p className="text-xs font-semibold text-indigo-500 uppercase tracking-widest mb-2">{cap.subtitle}</p>
                  <h3 id={cap.id} className="text-3xl font-bold text-slate-900 mb-4 leading-tight">{cap.title}</h3>
                  <p className="text-slate-500 leading-relaxed text-base">{cap.description}</p>

                  {/* Dashed divider */}
                  <div className="mt-8 pt-6 border-t border-dashed border-slate-200">
                    <div className="flex flex-wrap gap-2">
                      {['GPT-4 Turbo', 'DALL·E 3', 'Custom fine-tuning'].map(tag => (
                        <span key={tag} className="px-3 py-1 bg-slate-50 border border-slate-200 rounded-full text-xs font-medium text-slate-600">
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Image */}
                <div className={`relative ${cap.reverse ? 'lg:col-start-1 lg:row-start-1' : ''}`}>
                  <div className="rounded-2xl overflow-hidden shadow-xl border border-slate-100">
                    <img
                      alt={cap.title}
                      className="w-full object-cover"
                      data-strk-img-id={cap.imgId}
                      data-strk-img={`[${cap.id}] ${cap.imgQuery}`}
                      data-strk-img-ratio="4x3"
                      data-strk-img-width="700"
                      src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 3'/%3E"
                    />
                  </div>
                  {/* Dashed accent */}
                  <div className={`absolute -z-10 w-full h-full rounded-2xl border-2 border-dashed border-indigo-100 ${cap.reverse ? '-top-3 -left-3' : '-top-3 -right-3'}`} />
                </div>
              </div>
            )
          })}
        </div>

        {/* Extra features row */}
        <div className="mt-24 grid md:grid-cols-3 gap-6">
          {extras.map((item, i) => {
            const Icon = item.icon
            return (
              <div key={i} className="flex gap-4 p-6 bg-slate-50 rounded-2xl border border-slate-100">
                <div className="w-9 h-9 bg-white rounded-lg border border-slate-200 flex items-center justify-center flex-shrink-0">
                  <Icon className="w-4 h-4 text-indigo-600" />
                </div>
                <div>
                  <h4 className="font-semibold text-slate-900 text-sm mb-1">{item.title}</h4>
                  <p className="text-slate-500 text-sm">{item.desc}</p>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
