import { Cpu, Eye, RefreshCw, TrendingUp, Code2, MessageSquare } from 'lucide-react';

const capabilities = [
  {
    icon: Cpu,
    title: 'Neural Layout Engine',
    description: 'Our proprietary layout model analyzes thousands of high-converting site structures to generate optimal page architectures for your specific industry and goals.',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80&auto=format&fit=crop',
    tag: 'Core AI',
  },
  {
    icon: Eye,
    title: 'Visual Intelligence',
    description: 'Arcis understands visual hierarchy, whitespace, and typography at a deep level — producing designs that feel crafted by a senior designer, not generated by a machine.',
    image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80&auto=format&fit=crop',
    tag: 'Design AI',
  },
  {
    icon: RefreshCw,
    title: 'Continuous Optimization',
    description: 'After launch, Arcis monitors your site\'s performance metrics and automatically suggests A/B tests, copy improvements, and layout changes to maximize conversions.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop',
    tag: 'Growth AI',
  },
  {
    icon: TrendingUp,
    title: 'SEO Intelligence',
    description: 'Built-in semantic SEO analysis ensures every page is structured for maximum search visibility. Arcis tracks rankings and adapts content strategy in real time.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80&auto=format&fit=crop',
    tag: 'SEO AI',
  },
  {
    icon: Code2,
    title: 'Clean Code Output',
    description: 'Every site Arcis generates produces semantic, accessible HTML with optimized CSS. Export clean code at any time or integrate with your existing dev workflow.',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80&auto=format&fit=crop',
    tag: 'Dev Tools',
  },
  {
    icon: MessageSquare,
    title: 'Conversational Editing',
    description: 'Simply describe what you want to change in plain English. "Make the hero section more minimal" or "Add a pricing table" — Arcis understands and executes instantly.',
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800&q=80&auto=format&fit=crop',
    tag: 'Chat UI',
  },
];

export default function AICapabilities() {
  return (
    <section className="py-24 md:py-32 bg-white">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <div className="max-w-2xl mb-20">
          <p className="text-xs font-semibold text-indigo-600 uppercase tracking-widest mb-3">AI Capabilities</p>
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 leading-tight tracking-tight mb-5">
            Intelligence at every layer
          </h2>
          <p className="text-gray-500 text-lg leading-relaxed">
            Arcis isn't a template engine with AI sprinkled on top. It's AI-native from the ground up — every decision is driven by data and machine learning.
          </p>
        </div>

        {/* Capabilities */}
        <div className="space-y-0">
          {capabilities.map(({ icon: Icon, title, description, image, tag }, i) => (
            <div
              key={title}
              className={`grid grid-cols-1 md:grid-cols-2 gap-0 border border-dashed border-gray-200 ${
                i > 0 ? '-mt-px' : ''
              } group hover:bg-gray-50/50 transition-colors`}
            >
              {/* Text side */}
              <div className={`p-10 flex flex-col justify-center ${i % 2 === 1 ? 'md:order-2' : ''}`}>
                <div className="flex items-center gap-3 mb-5">
                  <div className="w-9 h-9 bg-gray-900 rounded-lg flex items-center justify-center group-hover:bg-indigo-600 transition-colors">
                    <Icon className="w-4 h-4 text-white" />
                  </div>
                  <span className="text-xs font-semibold text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-full">{tag}</span>
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-3">{title}</h3>
                <p className="text-gray-500 leading-relaxed">{description}</p>
              </div>

              {/* Image side */}
              <div className={`overflow-hidden ${i % 2 === 1 ? 'md:order-1' : ''}`}>
                <img
                  src={image}
                  alt={title}
                  className="w-full h-64 md:h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
