// Generator data - All generators organized by category
export const featuredGenerators = [
  { slug: 'ai-website-generator', name: 'AI Website Generator', description: 'Describe your business, get a full site', category: 'Website' },
  { slug: 'free-portfolio-generator', name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', category: 'Portfolio' },
  { slug: 'ai-landing-page-maker', name: 'AI Landing Page Maker', description: 'One-page sites built to convert', category: 'Landing Page' },
  { slug: 'online-store-builder', name: 'Online Store Builder', description: 'Start selling without writing code', category: 'Store' },
  { slug: 'link-in-bio-generator', name: 'Link-in-Bio Generator', description: 'One link for all your channels', category: 'Link-in-Bio' },
  { slug: 'one-page-website-builder', name: 'One-Page Website Builder', description: 'Simple sites, single scroll', category: 'Website' },
  { slug: 'wedding-website-generator', name: 'Wedding Website Generator', description: 'Share your day with guests', category: 'Website' },
  { slug: 'restaurant-website-builder', name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', category: 'Website' },
  { slug: 'blog-generator-for-beginners', name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', category: 'Blog' },
];

export const categories = [
  { id: 'websites', name: 'Websites', description: 'AI-built business and personal sites for any goal.', icon: 'globe' },
  { id: 'landing-pages', name: 'Landing Pages', description: 'Single-page sites built to convert visitors fast.', icon: 'target' },
  { id: 'portfolios', name: 'Portfolios', description: 'Showcase your work with a clean, focused site.', icon: 'image' },
  { id: 'blogs', name: 'Blogs', description: 'Publish-ready blogs with built-in SEO basics.', icon: 'edit' },
  { id: 'stores', name: 'Online Stores', description: 'Sell products online with payments built in.', icon: 'cart' },
  { id: 'link-in-bio', name: 'Link-in-Bio', description: 'One link, all your places. Made for creators.', icon: 'link' },
];

export const allGenerators = {
  websites: {
    heading: 'WEBSITES',
    description: 'Full websites for businesses, personal brands, and any online presence.',
    generators: [
      { slug: 'ai-website-generator', name: 'AI Website Generator', description: 'Describe your business, get a full site built instantly.' },
      { slug: 'one-page-website-builder', name: 'One-Page Website Builder', description: 'Simple, elegant sites in a single scroll.' },
      { slug: 'free-website-builder', name: 'Free Website Builder', description: 'No credit card required to get started.' },
      { slug: 'no-code-website-builder', name: 'No-Code Website Builder', description: 'Build professional sites without writing code.' },
      { slug: 'beautiful-website-maker', name: 'Beautiful Website Maker', description: 'Stunning designs made easy for everyone.' },
      { slug: 'business-website-generator', name: 'Business Website Generator', description: 'Professional sites for any industry.' },
      { slug: 'personal-website-builder', name: 'Personal Website Builder', description: 'Your online home, built for you.' },
      { slug: 'wedding-website-generator', name: 'Wedding Website Generator', description: 'Share your special day with guests.' },
      { slug: 'restaurant-website-builder', name: 'Restaurant Website Builder', description: 'Menu, hours, and reservations included.' },
      { slug: 'photographer-website-builder', name: 'Photographer Website Builder', description: 'Showcase your portfolio beautifully.' },
    ],
  },
  'landing-pages': {
    heading: 'LANDING PAGES',
    description: 'Single-page sites optimized for conversions and specific goals.',
    generators: [
      { slug: 'ai-landing-page-maker', name: 'AI Landing Page Maker', description: 'One-page sites built to convert visitors.' },
      { slug: 'free-landing-page-builder', name: 'Free Landing Page Builder', description: 'Create high-converting pages for free.' },
      { slug: 'product-launch-page', name: 'Product Launch Page', description: 'Build buzz before you launch.' },
      { slug: 'coming-soon-page', name: 'Coming Soon Page', description: 'Get emails while you build.' },
      { slug: 'lead-capture-page', name: 'Lead Capture Page', description: 'Collect leads with beautiful forms.' },
      { slug: 'event-landing-page', name: 'Event Landing Page', description: 'Promote events and sell tickets.' },
      { slug: 'webinar-landing-page', name: 'Webinar Landing Page', description: 'Drive registrations for online events.' },
      { slug: 'app-download-page', name: 'App Download Page', description: 'Showcase your app and drive installs.' },
      { slug: 'ebook-landing-page', name: 'Ebook Landing Page', description: 'Sell digital products with ease.' },
      { slug: 'consultation-booking-page', name: 'Consultation Booking Page', description: 'Fill your calendar with bookings.' },
    ],
  },
  portfolios: {
    heading: 'PORTFOLIOS',
    description: 'Clean, focused sites to showcase your creative work.',
    generators: [
      { slug: 'free-portfolio-generator', name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee.' },
      { slug: 'portfolio-generator-designers', name: 'Portfolio Generator for Designers', description: 'Show your design work beautifully.' },
      { slug: 'photographer-portfolio-builder', name: 'Photographer Portfolio Builder', description: 'Photo galleries that impress clients.' },
      { slug: 'artist-portfolio-maker', name: 'Artist Portfolio Maker', description: 'Art that speaks for itself.' },
      { slug: 'writer-portfolio-builder', name: 'Writer Portfolio Builder', description: 'Your writing, professionally presented.' },
      { slug: 'freelancer-portfolio', name: 'Freelancer Portfolio', description: 'Win clients with a professional site.' },
      { slug: 'creative-portfolio-template', name: 'Creative Portfolio Template', description: 'Stand out with unique layouts.' },
      { slug: 'video-portfolio-builder', name: 'Video Portfolio Builder', description: 'Showreels and video work showcased.' },
      { slug: 'illustrator-portfolio', name: 'Illustrator Portfolio', description: 'Draw attention to your illustrations.' },
      { slug: 'architect-portfolio', name: 'Architect Portfolio', description: 'Present your projects with precision.' },
    ],
  },
  blogs: {
    heading: 'BLOGS',
    description: 'Publish-ready blogs with built-in SEO and modern design.',
    generators: [
      { slug: 'blog-generator-for-beginners', name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes.' },
      { slug: 'free-blog-builder', name: 'Free Blog Builder', description: 'Start writing without spending a dime.' },
      { slug: 'personal-blog-generator', name: 'Personal Blog Generator', description: 'Share your thoughts with the world.' },
      { slug: 'travel-blog-builder', name: 'Travel Blog Builder', description: 'Document your adventures beautifully.' },
      { slug: 'food-blog-generator', name: 'Food Blog Generator', description: 'Recipes and food photography featured.' },
      { slug: 'fashion-blog-builder', name: 'Fashion Blog Builder', description: 'Style content that inspires.' },
      { slug: 'tech-blog-generator', name: 'Tech Blog Generator', description: 'Share your expertise in tech.' },
      { slug: 'business-blog-maker', name: 'Business Blog Maker', description: 'Content marketing made simple.' },
      { slug: 'newsletter-blog-builder', name: 'Newsletter Blog Builder', description: 'Grow subscribers with great content.' },
      { slug: 'multi-author-blog', name: 'Multi-Author Blog', description: 'Perfect for teams and publications.' },
    ],
  },
  stores: {
    heading: 'ONLINE STORES',
    description: 'Sell products online with payments, shipping, and more built in.',
    generators: [
      { slug: 'online-store-builder', name: 'Online Store Builder', description: 'Start selling without writing code.' },
      { slug: 'free-ecommerce-builder', name: 'Free Ecommerce Builder', description: 'No upfront costs to start selling.' },
      { slug: 'etsy-alternative-store', name: 'Etsy Alternative Store', description: 'Your own branded store, not a marketplace.' },
      { slug: 'product-landing-store', name: 'Product Landing Store', description: 'Single-product stores that convert.' },
      { slug: 'clothing-store-builder', name: 'Clothing Store Builder', description: 'Fashion retail made simple.' },
      { slug: 'artisan-shop-builder', name: 'Artisan Shop Builder', description: 'Handmade goods deserve a beautiful home.' },
      { slug: 'digital-products-store', name: 'Digital Products Store', description: 'Sell ebooks, courses, and downloads.' },
      { slug: 'print-on-demand-store', name: 'Print on Demand Store', description: 'Custom products without inventory.' },
      { slug: 'restaurant-takeout-store', name: 'Restaurant Takeout Store', description: 'Order food online from your restaurant.' },
      { slug: 'subscription-box-store', name: 'Subscription Box Store', description: 'Build recurring revenue with subscriptions.' },
    ],
  },
  'link-in-bio': {
    heading: 'LINK-IN-BIO',
    description: 'One link that leads to all your content, made for creators.',
    generators: [
      { slug: 'link-in-bio-generator', name: 'Link-in-Bio Generator', description: 'One link for all your channels.' },
      { slug: 'free-link-in-bio', name: 'Free Link-in-Bio', description: 'Linktree alternative, no cost.' },
      { slug: 'influencer-link-page', name: 'Influencer Link Page', description: 'Monetize your following.' },
      { slug: 'musician-link-page', name: 'Musician Link Page', description: 'Share music, shows, and merch.' },
      { slug: 'podcaster-link-page', name: 'Podcaster Link Page', description: 'Link to episodes and platforms.' },
      { slug: 'youtuber-link-page', name: 'Youtuber Link Page', description: 'Connect all your content.' },
      { slug: 'artist-link-page', name: 'Artist Link Page', description: 'Music, art, and tour dates.' },
      { slug: 'freelancer-link-page', name: 'Freelancer Link Page', description: 'Share your services and portfolio.' },
      { slug: 'creator-link-page', name: 'Creator Link Page', description: 'Everything you do, one link.' },
      { slug: 'small-business-link-page', name: 'Small Business Link Page', description: 'Local business social hub.' },
    ],
  },
};

export const faqData = [
  { question: 'What is an AI site generator?', answer: 'An AI site generator is a tool that uses artificial intelligence to help you create a website. Instead of building from scratch or using a pre-made template, you describe what you need, and the AI creates a custom site for you. With Strikingly\'s generators, you can create anything from personal portfolios to online stores in just a few clicks.' },
  { question: 'How is a generator different from a template?', answer: 'A template is a static design you fill in with your own content. A generator, on the other hand, actively helps you build. You provide information about your business or project, and the AI assembles pages, writes content, and sets up features based on what you tell it. This makes generators faster and more personalized than starting from a blank template.' },
  { question: 'Are these generators free to use?', answer: 'Yes! Our AI generators are free to use to get started. You can browse generators, create your site, and preview it without entering any payment information. When you\'re ready to publish with your own domain or remove Strikingly branding, you can choose a paid plan.' },
  { question: 'What kinds of sites can I build?', answer: 'You can build almost any type of website with our AI generators. Popular options include personal portfolios, business websites, blogs, online stores, landing pages, wedding websites, restaurant sites, and link-in-bio pages for social media. Each generator is optimized for its specific purpose, so you get a site that\'s designed to work for your goals.' },
  { question: 'Can I customize what the generator produces?', answer: 'Absolutely. The AI creates a starting point based on your input, but you can customize everything afterward. Change colors, fonts, images, text, and layout in our drag-and-drop editor. The generated site is fully yours to modify however you like—no locked sections or required elements.' },
  { question: 'Do generated sites work on mobile?', answer: 'Yes, all sites created with our generators are fully responsive. They look and work great on smartphones, tablets, and desktop computers. Mobile optimization is built into every design, so your visitors get a polished experience regardless of how they access your site.' },
];