import React, { useState, useMemo } from 'react'
import './GeneratorsHub.css'

// i18n strings object - English
const strings = {
  en: {
    pageTitle: 'AI Website Generators - Build Any Site in Seconds | Strikingly',
    pageDescription: 'Browse Strikingly\'s AI-powered website generators. Choose one for your industry, goal, or site type and create a website in seconds, no code required.',
    breadcrumbHome: 'Strikingly',
    breadcrumbCurrent: 'AI Generators',
    heroH1Line1: 'BUILD ANY KIND OF SITE',
    heroH1Line2: 'WITH AI, IN AN INSTANT',
    heroSubheadline: 'Browse the right generator for what you\'re building, or jump straight into our AI site builder.',
    heroCtaPrimary: 'START BUILDING - IT\'S FREE',
    heroCtaSecondary: 'BROWSE GENERATORS',
    featuredHeading: 'FEATURED GENERATORS',
    featuredSubheading: 'A few common starting points.',
    browseHeading: 'BROWSE BY CATEGORY',
    allGeneratorsHeading: 'ALL GENERATORS',
    allGeneratorsSubheading: 'Sixty-plus generators, organized by what you\'re building.',
    searchPlaceholder: 'Search generators...',
    searchAriaLabel: 'Search generators',
    resultsCount: '{count} generators match',
    noResults: 'No generators found.',
    clearSearch: 'Clear search',
    cantFindIt: 'Can\'t find it? Start with our AI builder.',
    howItWorksHeading: 'HOW IT WORKS',
    step1Title: 'PICK A GENERATOR',
    step1Desc: 'Browse by category or search to find one that fits your goal.',
    step2Title: 'DESCRIBE YOUR SITE',
    step2Desc: 'Tell our AI builder about your business in a sentence or two.',
    step3Title: 'GENERATE AND PUBLISH',
    step3Desc: 'Get a fully built site in seconds. Customize anything, then go live.',
    whyHeading: 'WHY STRIKINGLY',
    why1Title: 'LIVE IN SECONDS',
    why1Desc: 'Describe your site, we build it. No setup, no learning curve.',
    why2Title: 'MOBILE BY DEFAULT',
    why2Desc: 'Every generator produces responsive sites that work on any device.',
    why3Title: 'FREE TO START',
    why3Desc: 'Generate, customize, and publish without a credit card.',
    faqHeading: 'FREQUENTLY ASKED QUESTIONS',
    faq1Question: 'What is an AI site generator?',
    faq1Answer: 'An AI site generator is a tool that creates a complete website from a short description. Instead of picking a template and dragging blocks around, you describe your business or project, and the AI produces a full, styled site in seconds.',
    faq2Question: 'How is a generator different from a template?',
    faq2Answer: 'A template gives you a static layout that you fill in manually. A generator creates a custom site tailored to what you describe. You can still edit everything afterwards, but the generator gives you a complete first draft in seconds.',
    faq3Question: 'Are these generators free to use?',
    faq3Answer: 'Yes—you can generate, customize, and publish a site for free. Some advanced features and custom domains require a paid plan, but you can get started and go live without a credit card.',
    faq4Question: 'What kinds of sites can I build?',
    faq4Answer: 'You can build business sites, portfolios, landing pages, blogs, online stores, and link-in-bio pages. Each generator is tuned to the kind of site you\'re creating, so the result looks appropriate from the start.',
    faq5Question: 'Can I customize what the generator produces?',
    faq5Answer: 'Absolutely. After the AI generates your site, you can change any text, image, color, or layout. The generator gives you a strong starting point; you stay in control of the final result.',
    faq6Question: 'Do generated sites work on mobile?',
    faq6Answer: 'Yes. Every site generated by Strikingly is responsive by default. Your site will look and work great on phones, tablets, and desktops without extra work.',
    closingHeading: 'READY TO BUILD?',
    closingSub: 'Pick a generator above, or jump straight into our AI builder.',
    closingCta: 'START WITH AI BUILDER',
    footerAbout: 'ABOUT',
    footerSupport: 'SUPPORT',
    footerLegal: 'LEGAL',
    footerSocial: 'FOLLOW US',
    footerCopyright: `© ${new Date().getFullYear()} Strikingly. All rights reserved.`,
  }
}

// Sample data
const featuredGenerators = [
  { name: 'AI Website Generator', description: 'Describe your business, get a full site', category: 'Website', slug: 'ai-website-generator' },
  { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', category: 'Portfolio', slug: 'free-portfolio-generator' },
  { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', category: 'Landing Page', slug: 'ai-landing-page-maker' },
  { name: 'Online Store Builder', description: 'Start selling without writing code', category: 'Store', slug: 'online-store-builder' },
  { name: 'Link-in-Bio Generator', description: 'One link for all your channels', category: 'Link-in-Bio', slug: 'link-in-bio-generator' },
  { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', category: 'Website', slug: 'one-page-website-builder' },
  { name: 'Wedding Website Generator', description: 'Share your day with guests', category: 'Website', slug: 'wedding-website-generator' },
  { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', category: 'Website', slug: 'restaurant-website-builder' },
  { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', category: 'Blog', slug: 'blog-generator-for-beginners' },
]

const categories = [
  { name: 'Websites', slug: 'websites', description: 'AI-built business and personal sites for any goal.' },
  { name: 'Landing Pages', slug: 'landing-pages', description: 'Single-page sites built to convert visitors fast.' },
  { name: 'Portfolios', slug: 'portfolios', description: 'Showcase your work with a clean, focused site.' },
  { name: 'Blogs', slug: 'blogs', description: 'Publish-ready blogs with built-in SEO basics.' },
  { name: 'Online Stores', slug: 'stores', description: 'Sell products online with payments built in.' },
  { name: 'Link-in-Bio', slug: 'link-in-bio', description: 'One link, all your places. Made for creators.' },
]

const allGenerators = {
  websites: {
    heading: 'WEBSITES',
    description: 'Business and personal sites for any goal.',
    generators: [
      { name: 'AI Website Generator', description: 'Describe your business, get a full site', slug: 'ai-website-generator' },
      { name: 'Free Website Builder for Photographers', description: 'Portfolio + contact form, ready to share', slug: 'free-website-builder-photographers' },
      { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', slug: 'one-page-website-builder' },
      { name: 'Wedding Website Generator', description: 'Share your day with guests', slug: 'wedding-website-generator' },
      { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', slug: 'restaurant-website-builder' },
      { name: 'Yoga Instructor Website Generator', description: 'Class schedule, bio, and booking', slug: 'yoga-instructor-website-generator' },
      { name: 'Real Estate Agent Website Builder', description: 'Listings, bio, and lead capture', slug: 'real-estate-agent-website-builder' },
      { name: 'Consultant Website Generator', description: 'Services, testimonials, contact', slug: 'consultant-website-generator' },
      { name: 'Nonprofit Website Builder', description: 'Mission, donate button, events', slug: 'nonprofit-website-builder' },
      { name: 'Musician Website Generator', description: 'Bio, tour dates, and music', slug: 'musician-website-generator' },
    ]
  },
  'landing-pages': {
    heading: 'LANDING PAGES',
    description: 'Single-page sites built to convert visitors fast.',
    generators: [
      { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', slug: 'ai-landing-page-maker' },
      { name: 'Product Launch Landing Page', description: 'Waitlist, countdown, and signup', slug: 'product-launch-landing-page' },
      { name: 'Lead Generation Landing Page', description: 'Form-first, built to capture leads', slug: 'lead-generation-landing-page' },
      { name: 'Event Registration Landing Page', description: 'RSVP, details, and calendar', slug: 'event-registration-landing-page' },
      { name: 'Webinar Registration Page', description: 'Signup form and speaker bio', slug: 'webinar-registration-page' },
      { name: 'App Download Landing Page', description: 'Store badges and feature list', slug: 'app-download-landing-page' },
      { name: 'Course Sales Landing Page', description: 'Curriculum, testimonials, and CTA', slug: 'course-sales-landing-page' },
      { name: 'Coming Soon Page Generator', description: 'Teaser, email capture, and social', slug: 'coming-soon-page-generator' },
    ]
  },
  portfolios: {
    heading: 'PORTFOLIOS',
    description: 'Showcase your work with a clean, focused site.',
    generators: [
      { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', slug: 'free-portfolio-generator' },
      { name: 'Portfolio Generator for Designers', description: 'Projects, case studies, and resume', slug: 'portfolio-generator-designers' },
      { name: 'Photography Portfolio Website', description: 'Galleries, prints, and inquiries', slug: 'photography-portfolio-website' },
      { name: 'Artist Portfolio Generator', description: 'Work samples and artist statement', slug: 'artist-portfolio-generator' },
      { name: 'Writer Portfolio and Blog', description: 'Clips, about, and contact', slug: 'writer-portfolio-and-blog' },
      { name: 'Developer Portfolio Generator', description: 'Projects, skills, and resume', slug: 'developer-portfolio-generator' },
      { name: 'Model Portfolio Website', description: 'Digitals, comp card, and contact', slug: 'model-portfolio-website' },
      { name: 'Architect Portfolio Generator', description: 'Projects, drawings, and bio', slug: 'architect-portfolio-generator' },
    ]
  },
  blogs: {
    heading: 'BLOGS',
    description: 'Publish-ready blogs with built-in SEO basics.',
    generators: [
      { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', slug: 'blog-generator-for-beginners' },
      { name: 'Travel Blog Website Generator', description: 'Maps, posts, and newsletter', slug: 'travel-blog-website-generator' },
      { name: 'Food Blog Generator', description: 'Recipes, photos, and categories', slug: 'food-blog-generator' },
      { name: 'Fashion Blog Website Builder', description: 'Lookbooks, posts, and shop', slug: 'fashion-blog-website-builder' },
      { name: 'Personal Blog Generator', description: 'Simple, focused on your writing', slug: 'personal-blog-generator' },
      { name: 'Newsletter Blog Builder', description: 'Posts plus email signup', slug: 'newsletter-blog-builder' },
      { name: 'Parenting Blog Generator', description: 'Posts, categories, and community', slug: 'parenting-blog-generator' },
      { name: 'Tech Blog Website Builder', description: 'Code snippets, tutorials, and RSS', slug: 'tech-blog-website-builder' },
    ]
  },
  stores: {
    heading: 'ONLINE STORES',
    description: 'Sell products online with payments built in.',
    generators: [
      { name: 'Online Store Builder', description: 'Start selling without writing code', slug: 'online-store-builder' },
      { name: 'Online Store Builder for Restaurants', description: 'Menu items, pickup, and delivery', slug: 'online-store-builder-restaurants' },
      { name: 'Clothing Store Generator', description: 'Collections, sizes, and checkout', slug: 'clothing-store-generator' },
      { name: 'Digital Products Store Builder', description: 'Downloads, licenses, and payments', slug: 'digital-products-store-builder' },
      { name: 'Art Store and Portfolio', description: 'Prints, originals, and inquiries', slug: 'art-store-and-portfolio' },
      { name: 'Beauty Products Store Generator', description: 'Products, reviews, and cart', slug: 'beauty-products-store-generator' },
      { name: 'Handmade Shop Website Builder', description: 'Listings, story, and shop', slug: 'handmade-shop-website-builder' },
      { name: 'Subscription Box Store Builder', description: 'Plans, checkout, and manage', slug: 'subscription-box-store-builder' },
    ]
  },
  'link-in-bio': {
    heading: 'LINK-IN-BIO',
    description: 'One link, all your places. Made for creators.',
    generators: [
      { name: 'Link-in-Bio Generator', description: 'One link for all your channels', slug: 'link-in-bio-generator' },
      { name: 'Creator Link-in-Bio Builder', description: 'Links, social, and analytics', slug: 'creator-link-in-bio-builder' },
      { name: 'Musician Link-in-Bio Page', description: 'Streaming, tour, and merch', slug: 'musician-link-in-bio-page' },
      { name: 'Influencer Link-in-Bio Generator', description: 'Links, media kit, and contact', slug: 'influencer-link-in-bio-generator' },
      { name: 'Podcaster Link-in-Bio Page', description: 'Episodes, subscribe, and support', slug: 'podcaster-link-in-bio-page' },
      { name: 'Artist Link-in-Bio Builder', description: 'Portfolio, shop, and social', slug: 'artist-link-in-bio-builder' },
    ]
  }
}

// Icon component
const Icon = ({ name, className }) => {
  const icons = {
    search: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>,
    'arrow-right': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>,
    'chevron-down': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><polyline points="6 9 12 15 18 9"/></svg>,
    globe: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>,
    layout: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg>,
    image: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>,
    edit: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>,
    'shopping-bag': <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>,
    link: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className} aria-hidden="true"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>,
  }
  return icons[name] || null
}

// Category Illustration
const CategoryIllustration = ({ category }) => (
  <svg viewBox="0 0 120 80" fill="none" className="category-illustration" aria-hidden="true">
    <rect x="10" y="10" width="100" height="60" rx="4" stroke="#8159BB" strokeWidth="1.5" fill="none"/>
    <line x1="10" y1="25" x2="110" y2="25" stroke="#8159BB" strokeWidth="1"/>
    <circle cx="20" cy="17.5" r="3" fill="#8159BB" opacity="0.3"/>
    <circle cx="30" cy="17.5" r="3" fill="#8159BB" opacity="0.3"/>
    <circle cx="40" cy="17.5" r="3" fill="#8159BB" opacity="0.3"/>
  </svg>
)

// FAQ Item
const FAQItem = ({ question, answer, isOpen, onClick, index }) => (
  <div className="faq-item">
    <h3>
      <button
        className="faq-question"
        aria-expanded={isOpen}
        aria-controls={`faq-answer-${index}`}
        onClick={onClick}
      >
        {question}
        <span className="faq-icon" aria-hidden="true">
          <Icon name="chevron-down" />
        </span>
      </button>
    </h3>
    <div
      id={`faq-answer-${index}`}
      className="faq-answer"
      style={{ display: isOpen ? 'block' : 'none' }}
    >
      <p>{answer}</p>
    </div>
  </div>
)

// Generator Card
const GeneratorCard = ({ name, description, slug, showCategory, category }) => (
  <article className="generator-card">
    <a href={`/generators/${slug}`} className="generator-card-link">
      <div className="generator-card-content">
        <h4 className="generator-card-name">{name}</h4>
        <p className="generator-card-desc">{description}</p>
        {showCategory && category && (
          <span className="generator-card-tag">{category}</span>
        )}
      </div>
    </a>
  </article>
)

// Category Card
const CategoryCard = ({ name, slug, description }) => (
  <a href={`/generators#${slug}`} className="category-card">
    <div className="category-card-illustration">
      <CategoryIllustration category={slug} />
    </div>
    <div className="category-card-content">
      <h3 className="category-card-name">{name.toUpperCase()}</h3>
      <p className="category-card-desc">{description}</p>
    </div>
    <div className="category-card-arrow" aria-hidden="true">
      <Icon name="arrow-right" />
    </div>
  </a>
)

// Main Component
export default function GeneratorsHub() {
  const [searchQuery, setSearchQuery] = useState('')
  const [expandedFaq, setExpandedFaq] = useState(0)
  const [expandedSections, setExpandedSections] = useState({})
  const s = strings.en

  const filteredGenerators = useMemo(() => {
    if (!searchQuery.trim()) return allGenerators

    const query = searchQuery.toLowerCase()
    const filtered = {}

    Object.entries(allGenerators).forEach(([categorySlug, category]) => {
      const matchingGens = category.generators.filter(gen =>
        gen.name.toLowerCase().includes(query) ||
        gen.description.toLowerCase().includes(query) ||
        category.heading.toLowerCase().includes(query)
      )

      if (matchingGens.length > 0) {
        filtered[categorySlug] = { ...category, generators: matchingGens }
      }
    })

    return filtered
  }, [searchQuery])

  const totalMatches = Object.values(filteredGenerators).reduce(
    (sum, cat) => sum + cat.generators.length, 0
  )

  const toggleFaq = (index) => {
    setExpandedFaq(expandedFaq === index ? -1 : index)
  }

  const toggleSection = (slug) => {
    setExpandedSections(prev => ({ ...prev, [slug]: !prev[slug] }))
  }

  const heroIllustration = (
    <svg viewBox="0 0 500 400" fill="none" className="hero-illustration" aria-hidden="true">
      <rect x="50" y="50" width="400" height="300" rx="8" stroke="#8159BB" strokeWidth="2" fill="none" strokeDasharray="8 4"/>
      <rect x="70" y="70" width="360" height="260" rx="4" fill="#F4F6F8"/>
      <line x1="70" y1="100" x2="430" y2="100" stroke="#8159BB" strokeWidth="1.5"/>
      <circle cx="85" cy="85" r="6" fill="#8159BB" opacity="0.3"/>
      <circle cx="105" cy="85" r="6" fill="#8159BB" opacity="0.3"/>
      <circle cx="125" cy="85" r="6" fill="#8159BB" opacity="0.3"/>
      <rect x="90" y="120" width="120" height="12" rx="6" fill="#8159BB" opacity="0.2"/>
      <rect x="90" y="145" width="280" height="8" rx="4" fill="#8159BB" opacity="0.15"/>
      <rect x="90" y="165" width="240" height="8" rx="4" fill="#8159BB" opacity="0.15"/>
      <rect x="90" y="185" width="200" height="8" rx="4" fill="#8159BB" opacity="0.15"/>
      <rect x="90" y="220" width="100" height="35" rx="4" fill="url(#hero-gradient)" opacity="0.8"/>
      <rect x="200" y="220" width="100" height="35" rx="4" fill="none" stroke="#8159BB" strokeWidth="1.5"/>
      <defs>
        <linearGradient id="hero-gradient" x1="0" y1="0" x2="100" y2="0" gradientUnits="userSpaceOnUse">
          <stop offset="0" stopColor="#7671FF"/>
          <stop offset="1" stopColor="#CB0C9F"/>
        </linearGradient>
      </defs>
    </svg>
  )

  return (
    <div className="generators-hub">
        {/* Section 0: Top Bar */}
        <header className="top-bar" role="banner">
          <div className="container">
            <a href="/" className="logo" aria-label="Strikingly AI">
              <span className="logo-text">strikingly</span>
              <span className="logo-ai">AI</span>
            </a>
          </div>
        </header>

        {/* Section 1: Breadcrumb */}
        <nav className="breadcrumb" aria-label="Breadcrumb">
          <div className="container">
            <ol itemScope itemType="https://schema.org/BreadcrumbList">
              <li itemProp="itemListElement" itemScope itemType="https://schema.org/ListItem">
                <a href="/" itemProp="item">
                  <span itemProp="name">{s.breadcrumbHome}</span>
                </a>
                <meta itemProp="position" content="1"/>
              </li>
              <li className="breadcrumb-separator" aria-hidden="true">{'>'}</li>
              <li itemProp="itemListElement" itemScope itemType="https://schema.org/ListItem">
                <span itemProp="name">{s.breadcrumbCurrent}</span>
                <meta itemProp="position" content="2"/>
              </li>
            </ol>
          </div>
        </nav>

        {/* Section 2: Hero */}
        <section className="hero" aria-labelledby="hero-heading">
          <div className="container hero-container">
            <div className="hero-content">
              <h1 id="hero-heading" className="hero-heading">
                <span className="hero-h1-line1">{s.heroH1Line1}</span>
                <span className="hero-h1-line2">{s.heroH1Line2}</span>
              </h1>
              <p className="hero-subheadline">{s.heroSubheadline}</p>
              <div className="hero-ctas">
                <a href="/s/ai_site_builder" className="btn btn-primary btn-large">
                  {s.heroCtaPrimary}
                </a>
                <a href="#all-generators" className="btn btn-ghost">
                  {s.heroCtaSecondary}
                </a>
              </div>
            </div>
            <div className="hero-illustration-wrapper">
              {heroIllustration}
            </div>
          </div>
        </section>

        {/* Section 3: Featured Generators */}
        <section className="featured-generators" aria-labelledby="featured-heading">
          <div className="container">
            <h2 id="featured-heading" className="section-heading">{s.featuredHeading}</h2>
            <p className="section-subheading">{s.featuredSubheading}</p>
            <div className="featured-grid">
              {featuredGenerators.map((gen, index) => (
                <GeneratorCard
                  key={index}
                  name={gen.name}
                  description={gen.description}
                  slug={gen.slug}
                  showCategory={true}
                  category={gen.category}
                />
              ))}
            </div>
          </div>
        </section>

        {/* Section 4: Browse by Category */}
        <section className="browse-categories" aria-labelledby="browse-heading">
          <div className="container">
            <h2 id="browse-heading" className="section-heading">{s.browseHeading}</h2>
            <div className="categories-grid">
              {categories.map((cat, index) => (
                <CategoryCard
                  key={index}
                  name={cat.name}
                  slug={cat.slug}
                  description={cat.description}
                />
              ))}
            </div>
          </div>
        </section>

        {/* Section 5: All Generators */}
        <section className="all-generators" id="all-generators" aria-labelledby="all-generators-heading">
          <div className="container">
            <h2 id="all-generators-heading" className="section-heading">{s.allGeneratorsHeading}</h2>
            <p className="section-subheading">{s.allGeneratorsSubheading}</p>

            <div className="search-container">
              <div className="search-input-wrapper">
                <span className="search-icon" aria-hidden="true">
                  <Icon name="search" />
                </span>
                <input
                  type="text"
                  className="search-input"
                  placeholder={s.searchPlaceholder}
                  aria-label={s.searchAriaLabel}
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>
              {searchQuery && (
                <p className="search-results-count">
                  {s.resultsCount.replace('{count}', totalMatches)}
                </p>
              )}
            </div>

            {Object.entries(filteredGenerators).map(([slug, category]) => {
              const isExpanded = expandedSections[slug]
              const showToggle = category.generators.length > 6
              const visibleGens = isExpanded ? category.generators : category.generators.slice(0, 6)

              return (
                <div key={slug} className="generator-category" id={slug}>
                  <h3 className="category-heading">{category.heading}</h3>
                  <p className="category-description">{category.description}</p>
                  <div className="generators-grid">
                    {visibleGens.map((gen, index) => (
                      <GeneratorCard
                        key={index}
                        name={gen.name}
                        description={gen.description}
                        slug={gen.slug}
                        showCategory={false}
                      />
                    ))}
                  </div>
                  {showToggle && (
                    <button
                      className="btn-show-more"
                      aria-expanded={isExpanded}
                      aria-controls={`generators-${slug}`}
                      onClick={() => toggleSection(slug)}
                    >
                      {isExpanded
                        ? `Show fewer generators`
                        : `Show all ${category.generators.length} generators`
                      }
                    </button>
                  )}
                </div>
              )
            })}

            {searchQuery && totalMatches === 0 && (
              <div className="search-no-results">
                <p>{s.noResults}</p>
                <button className="btn btn-ghost" onClick={() => setSearchQuery('')}>
                  {s.clearSearch}
                </button>
                <p>
                  <a href="/s/ai_site_builder">{s.cantFindIt}</a>
                </p>
              </div>
            )}
          </div>
        </section>

        {/* Section 6: How It Works */}
        <section className="how-it-works" aria-labelledby="how-heading">
          <div className="container">
            <h2 id="how-heading" className="section-heading">{s.howItWorksHeading}</h2>
            <div className="steps-grid">
              <div className="step">
                <div className="step-number" aria-hidden="true">1</div>
                <h3 className="step-title">{s.step1Title}</h3>
                <p className="step-desc">{s.step1Desc}</p>
              </div>
              <div className="step">
                <div className="step-number" aria-hidden="true">2</div>
                <h3 className="step-title">{s.step2Title}</h3>
                <p className="step-desc">{s.step2Desc}</p>
              </div>
              <div className="step">
                <div className="step-number" aria-hidden="true">3</div>
                <h3 className="step-title">{s.step3Title}</h3>
                <p className="step-desc">{s.step3Desc}</p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 7: Why Strikingly */}
        <section className="why-strikingly" aria-labelledby="why-heading">
          <div className="container">
            <h2 id="why-heading" className="section-heading">{s.whyHeading}</h2>
            <div className="why-grid">
              <div className="why-item">
                <div className="why-icon" aria-hidden="true">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
                  </svg>
                </div>
                <h3 className="why-title">{s.why1Title}</h3>
                <p className="why-desc">{s.why1Desc}</p>
              </div>
              <div className="why-item">
                <div className="why-icon" aria-hidden="true">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="5" y="2" width="14" height="20" rx="2" ry="2"/>
                    <line x1="12" y1="18" x2="12.01" y2="18"/>
                  </svg>
                </div>
                <h3 className="why-title">{s.why2Title}</h3>
                <p className="why-desc">{s.why2Desc}</p>
              </div>
              <div className="why-item">
                <div className="why-icon" aria-hidden="true">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M12 2L2 7l10 5 10-5-10-5z"/>
                    <path d="M2 17l10 5 10-5"/>
                    <path d="M2 12l10 5 10-5"/>
                  </svg>
                </div>
                <h3 className="why-title">{s.why3Title}</h3>
                <p className="why-desc">{s.why3Desc}</p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 8: FAQ */}
        <section className="faq" aria-labelledby="faq-heading">
          <div className="container">
            <h2 id="faq-heading" className="section-heading">{s.faqHeading}</h2>
            <div className="faq-list">
              <FAQItem
                question={s.faq1Question}
                answer={s.faq1Answer}
                isOpen={expandedFaq === 0}
                onClick={() => toggleFaq(0)}
                index={0}
              />
              <FAQItem
                question={s.faq2Question}
                answer={s.faq2Answer}
                isOpen={expandedFaq === 1}
                onClick={() => toggleFaq(1)}
                index={1}
              />
              <FAQItem
                question={s.faq3Question}
                answer={s.faq3Answer}
                isOpen={expandedFaq === 2}
                onClick={() => toggleFaq(2)}
                index={2}
              />
              <FAQItem
                question={s.faq4Question}
                answer={s.faq4Answer}
                isOpen={expandedFaq === 3}
                onClick={() => toggleFaq(3)}
                index={3}
              />
              <FAQItem
                question={s.faq5Question}
                answer={s.faq5Answer}
                isOpen={expandedFaq === 4}
                onClick={() => toggleFaq(4)}
                index={4}
              />
              <FAQItem
                question={s.faq6Question}
                answer={s.faq6Answer}
                isOpen={expandedFaq === 5}
                onClick={() => toggleFaq(5)}
                index={5}
              />
            </div>
          </div>
        </section>

        {/* Section 9: Closing CTA */}
        <section className="closing-cta" aria-labelledby="closing-heading">
          <div className="container">
            <h2 id="closing-heading" className="closing-heading">{s.closingHeading}</h2>
            <p className="closing-sub">{s.closingSub}</p>
            <a href="/s/ai_site_builder" className="btn btn-primary btn-large">
              {s.closingCta}
            </a>
          </div>
        </section>

        {/* Section 10: Footer */}
        <footer className="footer" role="contentinfo">
          <div className="container">
            <div className="footer-grid">
              <div className="footer-column">
                <h3 className="footer-heading">{s.footerAbout}</h3>
                <ul className="footer-links">
                  <li><a href="/about">About Us</a></li>
                  <li><a href="/careers">Careers</a></li>
                  <li><a href="/press">Press</a></li>
                </ul>
              </div>
              <div className="footer-column">
                <h3 className="footer-heading">{s.footerSupport}</h3>
                <ul className="footer-links">
                  <li><a href="/support">Help Center</a></li>
                  <li><a href="/templates">Templates</a></li>
                  <li><a href="/blog">Blog</a></li>
                </ul>
              </div>
              <div className="footer-column">
                <h3 className="footer-heading">{s.footerLegal}</h3>
                <ul className="footer-links">
                  <li><a href="/terms">Terms of Service</a></li>
                  <li><a href="/privacy">Privacy Policy</a></li>
                  <li><a href="/cookies">Cookie Policy</a></li>
                </ul>
              </div>
              <div className="footer-column">
                <h3 className="footer-heading">{s.footerSocial}</h3>
                <ul className="footer-links">
                  <li><a href="https://twitter.com/strikingly" target="_blank" rel="noopener noreferrer">Twitter</a></li>
                  <li><a href="https://facebook.com/strikingly" target="_blank" rel="noopener noreferrer">Facebook</a></li>
                  <li><a href="https://instagram.com/strikingly" target="_blank" rel="noopener noreferrer">Instagram</a></li>
                </ul>
              </div>
            </div>
            <div className="footer-bottom">
              <p className="footer-copyright">{s.footerCopyright}</p>
            </div>
          </div>
        </footer>
      </div>
  )
}
