export const products = [
  {
    id: "vivid-aura-jewels",
    title: "Vivid Aura Jewels",
    description: "Gold ear cuff with crystal accent. Crafted in 18K gold plated brass with premium cubic zirconia.",
    price: 42,
    category: "Earrings",
    tags: ["Gold", "Ear Cuff", "Crystal"],
    images: ["vivid-aura-1", "vivid-aura-2"],
    material: "18K Gold Plated Brass",
  },
  {
    id: "majestic-flora-nectar",
    title: "Majestic Flora Nectar",
    description: "Multicolor floral crystal necklace. A vibrant piece inspired by wild flower meadows.",
    price: 68,
    category: "Necklaces",
    tags: ["Multicolor", "Floral", "Crystal"],
    images: ["flora-nectar-1", "flora-nectar-2"],
    material: "18K Gold Plated Brass",
  },
  {
    id: "golden-sphere-huggies",
    title: "Golden Sphere Huggies",
    description: "Chunky gold dome huggie earrings. A classic silhouette for effortless elegance.",
    price: 38,
    category: "Earrings",
    tags: ["Gold", "Huggies", "Dome"],
    images: ["sphere-huggies-1", "sphere-huggies-2"],
    material: "18K Gold Plated Brass",
  },
  {
    id: "amber-lace-earrings",
    title: "Amber Lace Earrings",
    description: "Textured gold filigree drop earrings. Intricate design reflecting timeless craftsmanship.",
    price: 54,
    category: "Earrings",
    tags: ["Gold", "Filigree", "Drop"],
    images: ["amber-lace-1", "amber-lace-2"],
    material: "18K Gold Plated Brass",
  },
  {
    id: "royal-heirloom-set",
    title: "Royal Heirloom Set",
    description: "Gift-boxed earring + necklace set. The perfect start to any fine jewelry collection.",
    price: 95,
    category: "Sets",
    tags: ["Gold", "Set", "Gift Box"],
    images: ["heirloom-set-1", "heirloom-set-2"],
    material: "18K Gold Plated Brass",
  }
];
