export const products = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    price: 42,
    category: 'Earrings',
    description: 'Gold ear cuff with crystal accent. A delicate piece that adds a touch of sparkle to any ensemble.',
    details: '18K Gold Plated over Brass. Cubic Zirconia crystals. Lead and nickel free.',
    image: 'vivid-aura-1',
    image2: 'vivid-aura-2',
    isBestseller: true,
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    price: 68,
    category: 'Necklaces',
    description: 'Multicolor floral crystal necklace. An editorial piece inspired by the blooming gardens of the Mediterranean.',
    details: '18K Gold Plated. Hand-set multicolored crystals. 16-18 inch adjustable chain.',
    image: 'majestic-flora-1',
    image2: 'majestic-flora-2',
    isBestseller: true,
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    price: 38,
    category: 'Huggies',
    description: 'Chunky gold dome huggie earrings. Modern minimalism meets timeless elegance.',
    details: '18K Gold Plated. Hypoallergenic posts. Comfortable click closure.',
    image: 'golden-sphere-1',
    image2: 'golden-sphere-2',
    isBestseller: true,
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    price: 54,
    category: 'Earrings',
    description: 'Textured gold filigree drop earrings. Intricate lace-like patterns that dance with the light.',
    details: '18K Gold Plated. Lightweight design for all-day wear.',
    image: 'amber-lace-1',
    image2: 'amber-lace-2',
    isBestseller: true,
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    price: 95,
    category: 'Collections',
    description: 'Gift-boxed earring + necklace set. The ultimate expression of luxury, beautifully packaged for someone special.',
    details: 'Includes Majestic Flora Nectar and Golden Sphere Huggies. Premium velvet gift box included.',
    image: 'royal-heirloom-1',
    image2: 'royal-heirloom-2',
    isBestseller: true,
  },
  {
    id: 'ethereal-pearl-drop',
    name: 'Ethereal Pearl Drop',
    price: 48,
    category: 'Earrings',
    description: 'Freshwater pearl drop earrings with a modern gold twist.',
    details: 'Natural freshwater pearls. 18K Gold Plated.',
    image: 'ethereal-pearl-1',
    image2: 'ethereal-pearl-2',
    isBestseller: false,
  },
  {
    id: 'luna-crescent-necklace',
    name: 'Luna Crescent Necklace',
    price: 52,
    category: 'Necklaces',
    description: 'A delicate crescent moon pendant on a shimmering gold chain.',
    details: '18K Gold Plated. 14 inch choker length with 2 inch extender.',
    image: 'luna-crescent-1',
    image2: 'luna-crescent-2',
    isBestseller: false,
  }
];

export const categories = ['All', 'Earrings', 'Necklaces', 'Huggies', 'Collections'];
