export const PRODUCTS = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    description: 'A delicate gold ear cuff featuring a shimmering crystal accent. Designed for effortless elegance, it sits comfortably without needing a piercing.',
    price: 42,
    category: 'Earrings',
    subCategory: 'Cuffs',
    images: ['vivid-aura-1', 'vivid-aura-2'],
    imgId: 'vivid-aura-jewels',
    titleId: 'title-vivid-aura-jewels',
    colors: ['Gold'],
    materials: '18K Gold Plated Brass, Cubic Zirconia',
    rating: 4.8,
    reviews: 24,
    tags: ['Bestseller', 'Crystal']
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    description: 'An exquisite multicolor floral crystal necklace that captures the vibrant essence of spring. Perfect for adding a botanical statement to any ensemble.',
    price: 68,
    category: 'Necklaces',
    subCategory: 'Floral',
    images: ['majestic-flora-1', 'majestic-flora-2'],
    imgId: 'majestic-flora-nectar',
    titleId: 'title-majestic-flora-nectar',
    colors: ['Gold'],
    materials: '18K Gold Plated, Mixed Crystals',
    rating: 4.9,
    reviews: 18,
    tags: ['Statement', 'Colorful']
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    description: 'Chunky gold dome huggie earrings that offer a modern, voluminous look. A staple piece that transitions seamlessly from day to night.',
    price: 38,
    category: 'Earrings',
    subCategory: 'Huggies',
    images: ['golden-sphere-1', 'golden-sphere-2'],
    imgId: 'golden-sphere-huggies',
    titleId: 'title-golden-sphere-huggies',
    colors: ['Gold', 'Silver'],
    materials: '18K Gold Plated or Sterling Silver Plated Brass',
    rating: 4.7,
    reviews: 56,
    tags: ['Bestseller', 'Minimalist']
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    description: 'Detailed gold filigree drop earrings with an intricate texture reminiscent of delicate lace. Lightweight yet visually captivating.',
    price: 54,
    category: 'Earrings',
    subCategory: 'Drops',
    images: ['amber-lace-1', 'amber-lace-2'],
    imgId: 'amber-lace-earrings',
    titleId: 'title-amber-lace-earrings',
    colors: ['Gold'],
    materials: '18K Gold Plated Brass',
    rating: 4.6,
    reviews: 32,
    tags: ['Vintage-Inspired', 'Lace']
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    description: 'A curated gift set featuring our signature drop earrings and matching pendant necklace. Presented in a premium velvet-lined gift box.',
    price: 95,
    category: 'Sets',
    subCategory: 'Gift Sets',
    images: ['royal-heirloom-1', 'royal-heirloom-2'],
    imgId: 'royal-heirloom-set',
    titleId: 'title-royal-heirloom-set',
    colors: ['Gold'],
    materials: '18K Gold Plated, Luxury Gift Box included',
    rating: 5.0,
    reviews: 12,
    tags: ['Gifting', 'Set']
  }
];
