import React from 'react'
import { Link } from 'react-router-dom'
import { Star } from 'lucide-react'
import { categories, products, ugcCards } from '@/data/products.js'
import ProductCard from '@/components/product/ProductCard.jsx'
import JewelryVisual from '@/components/product/JewelryVisual.jsx'

export default function HomeSections({ onAddToCart }) {
  return (
    <main id="top" className="bg-porcelain text-ink">
      <section className="relative min-h-screen overflow-hidden bg-ink text-porcelain">
        <JewelryVisual label="Crafted to be Treasured" description="Warm demi-fine gold jewelry worn in editorial light" className="absolute inset-0 opacity-80" variant="hero" />
        <div className="absolute inset-0 bg-gradient-to-b from-ink/45 via-ink/30 to-ink/82" />
        <div className="relative mx-auto flex min-h-screen max-w-7xl items-end px-4 pb-24 pt-32 sm:px-6 lg:px-8 lg:pb-28">
          <div className="max-w-3xl">
            <p className="mb-5 text-xs font-bold uppercase tracking-[0.32em] text-champagne">Demi-fine gold jewelry</p>
            <h1 id="hero-title" className="font-serif text-6xl leading-[0.9] tracking-tight text-porcelain sm:text-7xl lg:text-8xl">Crafted to be Treasured</h1>
            <p id="hero-subtitle" className="mt-6 max-w-xl text-base leading-8 text-porcelain/82 sm:text-lg">Warm, luminous pieces made for gifting, self-purchase, and the everyday rituals that deserve a little gold.</p>
            <Link to="/shop" className="mt-9 inline-flex bg-champagne px-7 py-4 text-sm font-bold uppercase tracking-[0.24em] text-ink transition hover:-translate-y-0.5 hover:bg-antique hover:text-porcelain">Shop the Collection</Link>
          </div>
        </div>
      </section>

      <section className="border-y border-sand bg-pearl text-ink"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-px px-4 py-4 text-center text-[11px] font-bold uppercase tracking-[0.2em] text-stone sm:px-6 md:grid-cols-4 lg:px-8">{['Free Worldwide Shipping', '30-Day Returns', '18K Gold Plated', 'Hypoallergenic'].map((item) => <p key={item} className="px-2 py-2">{item}</p>)}</div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28">
        <div className="mb-10 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-antique">Most loved</p><h2 className="mt-3 font-serif text-5xl text-ink md:text-6xl">Bestsellers</h2></div><Link to="/shop" className="text-sm font-bold uppercase tracking-[0.22em] text-antique underline decoration-sand underline-offset-8 transition hover:text-ink">View all pieces</Link></div>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-5">{products.map((product) => <ProductCard key={product.id} product={product} onAddToCart={onAddToCart} />)}</div>
      </section>

      <section id="journal" className="bg-espresso py-20 text-porcelain lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-8 flex items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-champagne">Seen in the wild</p><h2 className="mt-3 font-serif text-5xl text-porcelain">Velmora Reels</h2></div><p className="hidden max-w-sm text-sm leading-6 text-porcelain/72 md:block">A soft-scroll edit of gifted moments, neckline layers, and close-up golden stacks.</p></div><div className="flex gap-5 overflow-x-auto pb-4 [scrollbar-width:thin]">{ugcCards.map((card) => <article key={card.id} className="group relative h-[440px] min-w-[245px] overflow-hidden border border-porcelain/15 bg-ink shadow-[0_24px_60px_rgba(0,0,0,0.25)] sm:min-w-[280px]"><JewelryVisual label={card.caption} description="Worn gold jewelry reel" className="h-full w-full opacity-90 transition duration-700 group-hover:scale-105" variant="ugc" /><div className="absolute inset-0 bg-gradient-to-t from-ink/80 via-ink/10 to-transparent" /><h3 id={card.titleId} className="absolute bottom-5 left-5 right-5 font-serif text-3xl leading-none text-porcelain">{card.caption}</h3></article>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mb-10 text-center"><p className="text-xs font-bold uppercase tracking-[0.3em] text-antique">Find your glow</p><h2 className="mt-3 font-serif text-5xl text-ink md:text-6xl">Shop by Category</h2></div><div className="grid gap-5 md:grid-cols-3">{categories.map((category) => <Link to={`/shop?category=${category.name}`} key={category.name} className="group relative aspect-[4/5] overflow-hidden bg-ink text-porcelain"><JewelryVisual label={category.name} description={category.description} className="h-full w-full opacity-90 transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-ink/80 via-ink/10 to-transparent" /><div className="absolute bottom-0 left-0 right-0 translate-y-2 p-7 transition duration-500 group-hover:translate-y-0"><h3 id={category.titleId} className="font-serif text-5xl text-porcelain">{category.name}</h3><p id={category.descId} className="mt-3 max-w-xs text-sm leading-6 text-porcelain/78 opacity-0 transition duration-500 group-hover:opacity-100">{category.description}</p></div></Link>)}</div></section>

      <section id="story" className="bg-sand/45 py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="relative min-h-[420px] overflow-hidden bg-ink"><JewelryVisual label="Velmora Atelier" description="Quiet luxury gold jewelry story" className="h-full min-h-[420px] w-full" variant="worn" /></div><div className="flex items-center bg-pearl p-8 text-ink shadow-[0_18px_60px_rgba(42,33,27,0.08)] sm:p-12"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-antique">Our story</p><h2 id="story-title" className="mt-4 font-serif text-5xl leading-tight text-ink md:text-6xl">Jewelry for the moments you keep close.</h2><p id="story-copy" className="mt-6 max-w-xl text-base leading-8 text-stone">Velmora creates demi-fine gold pieces that feel personal from the first wear. Each design balances modern polish with heirloom warmth, made to slip into everyday routines and meaningful gifts.</p><a href="#top" className="mt-8 inline-flex border border-champagne px-6 py-3 text-sm font-bold uppercase tracking-[0.22em] text-antique transition hover:bg-champagne hover:text-ink">Our Story</a></div></div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="grid gap-5 md:grid-cols-3">{[['It feels expensive without being precious. I wear the huggies almost every day.', 'Maya R.'], ['The necklace arrived beautifully boxed and made the perfect birthday gift.', 'Elena K.'], ['Quiet, warm, and polished. Exactly the kind of gold jewelry I was looking for.', 'Sophie L.']].map(([quote, name]) => <figure key={name} className="border border-sand bg-pearl p-7 text-ink shadow-[0_16px_45px_rgba(42,33,27,0.06)]"><div className="mb-5 flex gap-1 text-champagne" aria-label="5 star review">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className="h-4 w-4 fill-current" />)}</div><blockquote className="font-serif text-2xl leading-snug text-ink">“{quote}”</blockquote><figcaption className="mt-6 text-xs font-bold uppercase tracking-[0.26em] text-stone">{name}</figcaption></figure>)}</div></section>

      <section className="bg-espresso px-4 py-16 text-porcelain sm:px-6 lg:px-8"><div className="mx-auto grid max-w-5xl gap-8 border border-champagne/30 bg-ink/50 p-7 sm:p-10 md:grid-cols-[1.1fr_1fr] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-champagne">Velmora list</p><h2 className="mt-3 font-serif text-4xl text-porcelain md:text-5xl">Join for 10% off your first order</h2><p className="mt-4 text-sm leading-6 text-porcelain/75">Receive styling notes, gifting edits, and early access to new demi-fine drops.</p></div><form className="flex flex-col gap-3 sm:flex-row" onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" required placeholder="you@example.com" className="min-h-12 flex-1 border border-porcelain/20 bg-pearl px-4 text-sm text-ink outline-none transition placeholder:text-stone focus:border-champagne focus:ring-2 focus:ring-champagne/35" /><button type="submit" className="min-h-12 bg-champagne px-6 text-sm font-bold uppercase tracking-[0.22em] text-ink transition hover:bg-antique hover:text-porcelain">Join</button></form></div></section>
    </main>
  )
}
