export const PRODUCTS = [
  {
    id: "double-folding-machine",
    title: "Double Folding Machine",
    subtitle: "Two-sided precision in a single pass",
    desc: "Our flagship series folds both edges of a panel simultaneously, halving cycle time for enclosures, cabinets, and architectural panels.",
    features: ["Up to 6 m folding length", "±0.1° repeatability", "120-ton hydraulic pressure"],
    image: "Industrial double folding machine forming sheet metal panel in factory",
  },
  {
    id: "double-folder",
    title: "Double Folder",
    subtitle: "Compact dual-edge folder",
    desc: "A compact dual-action folder built for high-mix job shops that demand production flexibility without sacrificing precision.",
    features: ["3.2 m working length", "Quick-change tooling", "Foot-pedal & CNC modes"],
    image: "Compact double folder machine bending sheet metal in workshop",
  },
  {
    id: "sheet-metal-folder",
    title: "Sheet Metal Folder",
    subtitle: "Versatile sheet forming",
    desc: "An everyday workhorse for general fabrication. Handles mild steel, stainless, and aluminium with consistent bend angles.",
    features: ["Up to 4 mm mild steel", "20+ programmable sequences", "Energy-efficient hybrid drive"],
    image: "Sheet metal folder machine operator forming metal panel",
  },
  {
    id: "sheet-metal-folding-machine",
    title: "Sheet Metal Folding Machine",
    subtitle: "Heavy-duty industrial folder",
    desc: "Engineered for continuous three-shift production of large-format sheet metal components used in rail and architectural cladding.",
    features: ["8 m folding length", "220-ton beam pressure", "Automatic crowning system"],
    image: "Large industrial sheet metal folding machine in heavy production line",
  },
  {
    id: "metal-folder",
    title: "Metal Folder",
    subtitle: "Precision in mild steel and aluminium",
    desc: "A precision folder purpose-built for thin-gauge aluminium and stainless work — ideal for HVAC, signage, and electronics enclosures.",
    features: ["0.4–3 mm capacity", "Pneumatic clamping", "Tool-less setup under 90 seconds"],
    image: "Metal folder machine bending aluminum sheet on production floor",
  },
  {
    id: "metal-folder-machine",
    title: "Metal Folder Machine",
    subtitle: "Automated CNC folding centre",
    desc: "A full CNC metal folder machine with robotic loading, in-line gauging, and offline programming for lights-out manufacturing.",
    features: ["6-axis backgauge", "Robotic load/unload ready", "Industry 4.0 telemetry"],
    image: "Automated CNC metal folder machine with robotic arm in modern factory",
  },
  {
    id: "metal-folding-machine",
    title: "Metal Folding Machine",
    subtitle: "Bending & folding redefined",
    desc: "Our top-of-line metal folding machine for fabricators who need press-brake versatility with folder repeatability and speed.",
    features: ["Adaptive bending control", "Up to 14 m folding length", "Laser angle measurement"],
    image: "High precision metal folding machine bending thick steel plate",
  },
];
