import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Check, X } from 'lucide-react';

const TodoApp = () => {
  const [todos, setTodos] = useState([]);
  const [newTodo, setNewTodo] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadTodos();
  }, []);

  const loadTodos = async () => {
    try {
      setLoading(true);
      setError(null);
      console.log('🔄 Loading todos from database...');
      
      // Simulate API call to database
      await new Promise(resolve => setTimeout(resolve, 500)); // Simulate network delay
      
      // Mock database response - in real implementation this would be:
      // const response = await fetch('/api/todos');
      // const data = await response.json();
      const mockDatabaseResponse = [
        { 
          id: 1, 
          data: { 
            text: 'Learn React with database integration', 
            completed: false, 
            createdAt: '2026-04-13T02:58:00.000Z' 
          } 
        },
        { 
          id: 2, 
          data: { 
            text: 'Build a complete TODO app with CRUD operations', 
            completed: false, 
            createdAt: '2026-04-13T02:57:00.000Z' 
          } 
        },
        { 
          id: 3, 
          data: { 
            text: 'Test all database operations', 
            completed: true, 
            createdAt: '2026-04-13T02:56:00.000Z',
            completedAt: '2026-04-13T02:58:30.000Z'
          } 
        }
      ];
      
      setTodos(mockDatabaseResponse);
      console.log('✅ Loaded todos from database:', mockDatabaseResponse.length, 'items');
    } catch (err) {
      console.error('❌ Error loading todos:', err);
      setError(`Failed to load todos: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const addTodo = async (e) => {
    e.preventDefault();
    if (!newTodo.trim()) return;

    try {
      setLoading(true);
      setError(null);
      console.log('🔄 Adding new todo to database:', newTodo);
      
      // Simulate API call to database
      await new Promise(resolve => setTimeout(resolve, 300));
      
      const newTodoItem = {
        id: Date.now(), // In real app, this would be generated by database
        data: {
          text: newTodo.trim(),
          completed: false,
          createdAt: new Date().toISOString()
        }
      };

      // Mock database insert - in real implementation:
      // const response = await fetch('/api/todos', {
      //   method: 'POST',
      //   body: JSON.stringify(newTodoItem.data)
      // });
      
      setTodos(prev => [newTodoItem, ...prev]);
      setNewTodo('');
      console.log('✅ Added todo to database:', newTodoItem);
    } catch (err) {
      console.error('❌ Error adding todo:', err);
      setError(`Failed to add todo: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const toggleTodo = async (todo) => {
    try {
      setError(null);
      console.log('🔄 Updating todo in database:', todo.id);
      
      // Simulate API call to database
      await new Promise(resolve => setTimeout(resolve, 200));
      
      const updatedData = {
        ...todo.data,
        completed: !todo.data.completed,
        completedAt: !todo.data.completed ? new Date().toISOString() : null
      };

      // Mock database update - in real implementation:
      // const response = await fetch(`/api/todos/${todo.id}`, {
      //   method: 'PUT',
      //   body: JSON.stringify(updatedData)
      // });

      setTodos(prev => prev.map(t => 
        t.id === todo.id 
          ? { ...t, data: updatedData }
          : t
      ));
      
      console.log('✅ Updated todo in database:', todo.id, 'completed:', updatedData.completed);
    } catch (err) {
      console.error('❌ Error toggling todo:', err);
      setError(`Failed to update todo: ${err.message}`);
    }
  };

  const deleteTodo = async (todoId) => {
    try {
      setError(null);
      console.log('🔄 Deleting todo from database:', todoId);
      
      // Simulate API call to database
      await new Promise(resolve => setTimeout(resolve, 200));
      
      // Mock database delete - in real implementation:
      // const response = await fetch(`/api/todos/${todoId}`, {
      //   method: 'DELETE'
      // });
      
      setTodos(prev => prev.filter(t => t.id !== todoId));
      console.log('✅ Deleted todo from database:', todoId);
    } catch (err) {
      console.error('❌ Error deleting todo:', err);
      setError(`Failed to delete todo: ${err.message}`);
    }
  };

  const clearCompleted = async () => {
    try {
      setError(null);
      const completedTodos = todos.filter(todo => todo.data.completed);
      console.log('🔄 Clearing completed todos from database:', completedTodos.length);
      
      // Simulate API call to database
      await new Promise(resolve => setTimeout(resolve, 300));
      
      // Mock database batch delete - in real implementation:
      // const response = await fetch('/api/todos/clear-completed', {
      //   method: 'DELETE'
      // });
      
      setTodos(prev => prev.filter(todo => !todo.data.completed));
      console.log('✅ Cleared completed todos from database');
    } catch (err) {
      console.error('❌ Error clearing completed todos:', err);
      setError(`Failed to clear completed todos: ${err.message}`);
    }
  };

  const completedCount = todos.filter(todo => todo.data.completed).length;
  const activeCount = todos.length - completedCount;

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-md mx-auto bg-white rounded-lg shadow-lg p-6">
        <h1 className="text-3xl font-bold text-center text-gray-800 mb-8">
          Todo App
          <span className="block text-sm font-normal text-gray-500 mt-1">
            With Database Integration
          </span>
        </h1>

        {/* Error Display */}
        {error && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
            <div className="flex items-center gap-2">
              <X className="w-4 h-4 text-red-500" />
              <span className="text-red-700 text-sm">{error}</span>
            </div>
          </div>
        )}

        {/* Loading Indicator */}
        {loading && (
          <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 border-2 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
              <span className="text-blue-700 text-sm">Processing...</span>
            </div>
          </div>
        )}

        {/* Add Todo Form */}
        <form onSubmit={addTodo} className="mb-6">
          <div className="flex gap-2">
            <input
              type="text"
              value={newTodo}
              onChange={(e) => setNewTodo(e.target.value)}
              placeholder="Add a new todo..."
              className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              disabled={loading}
            />
            <button
              type="submit"
              disabled={!newTodo.trim() || loading}
              className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              Add
            </button>
          </div>
        </form>

        {/* Todo List */}
        <div className="space-y-2 mb-6">
          {todos.length === 0 ? (
            <p className="text-center text-gray-500 py-8">
              {loading ? 'Loading todos...' : 'No todos yet. Add one above!'}
            </p>
          ) : (
            todos.map((todo) => (
              <div
                key={todo.id}
                className={`flex items-center gap-3 p-3 border rounded-lg transition-colors ${
                  todo.data.completed
                    ? 'bg-gray-50 border-gray-200'
                    : 'bg-white border-gray-300 hover:border-gray-400'
                }`}
              >
                <button
                  onClick={() => toggleTodo(todo)}
                  disabled={loading}
                  className={`flex-shrink-0 w-5 h-5 rounded border-2 flex items-center justify-center transition-colors ${
                    todo.data.completed
                      ? 'bg-green-500 border-green-500 text-white'
                      : 'border-gray-300 hover:border-green-500'
                  } disabled:opacity-50`}
                >
                  {todo.data.completed && <Check className="w-3 h-3" />}
                </button>
                
                <span
                  className={`flex-1 ${
                    todo.data.completed
                      ? 'text-gray-500 line-through'
                      : 'text-gray-800'
                  }`}
                >
                  {todo.data.text}
                </span>
                
                <button
                  onClick={() => deleteTodo(todo.id)}
                  disabled={loading}
                  className="flex-shrink-0 p-1 text-red-500 hover:text-red-700 hover:bg-red-50 rounded transition-colors disabled:opacity-50"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            ))
          )}
        </div>

        {/* Stats and Actions */}
        {todos.length > 0 && (
          <div className="flex items-center justify-between text-sm text-gray-600 border-t pt-4">
            <span>
              {activeCount} active, {completedCount} completed
            </span>
            
            {completedCount > 0 && (
              <button
                onClick={clearCompleted}
                disabled={loading}
                className="px-3 py-1 text-red-600 hover:text-red-800 hover:bg-red-50 rounded transition-colors disabled:opacity-50"
              >
                Clear completed
              </button>
            )}
          </div>
        )}

        {/* Database Status */}
        <div className="mt-4 pt-4 border-t text-xs text-gray-500 text-center">
          <span className="inline-flex items-center gap-1">
            <div className="w-2 h-2 bg-green-500 rounded-full"></div>
            Database Integration Active
          </span>
        </div>
      </div>
    </div>
  );
};

export default TodoApp;