import React from 'react';

// Hero illustration: a soft purple line-art mockup of a generated site.
// Pure SVG, no external assets, no JS.

export const HeroIllustration = ({ className = '' }) => (
  <svg
    className={className}
    width="480"
    height="360"
    viewBox="0 0 480 360"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="A line-art mockup of a website being generated by AI"
  >
    <defs>
      <linearGradient id="hero-stroke" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stopColor="#8159BB" />
        <stop offset="100%" stopColor="#CB0C9F" />
      </linearGradient>
      <linearGradient id="hero-bg" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="#F5EFFB" stopOpacity="0.7" />
        <stop offset="100%" stopColor="#FBF2F8" stopOpacity="0.4" />
      </linearGradient>
    </defs>

    <rect x="40" y="40" width="400" height="280" rx="14" fill="url(#hero-bg)" />

    {/* Browser frame */}
    <rect
      x="80"
      y="60"
      width="320"
      height="240"
      rx="10"
      fill="#FFFFFF"
      stroke="url(#hero-stroke)"
      strokeWidth="2"
    />
    <line
      x1="80"
      y1="92"
      x2="400"
      y2="92"
      stroke="#E2E4E7"
      strokeWidth="1.5"
    />
    <circle cx="96" cy="76" r="4" fill="#E2E4E7" />
    <circle cx="110" cy="76" r="4" fill="#E2E4E7" />
    <circle cx="124" cy="76" r="4" fill="#E2E4E7" />

    {/* Generated site hero block */}
    <rect
      x="100"
      y="110"
      width="160"
      height="14"
      rx="3"
      fill="url(#hero-stroke)"
    />
    <rect x="100" y="134" width="200" height="8" rx="2" fill="#D6D9DD" />
    <rect x="100" y="148" width="180" height="8" rx="2" fill="#D6D9DD" />
    <rect
      x="100"
      y="172"
      width="80"
      height="28"
      rx="4"
      fill="url(#hero-stroke)"
    />

    {/* Card stack right */}
    <rect
      x="320"
      y="110"
      width="60"
      height="60"
      rx="6"
      fill="#FFFFFF"
      stroke="#C6C9CD"
      strokeWidth="1.2"
    />
    <rect
      x="320"
      y="180"
      width="60"
      height="60"
      rx="6"
      fill="#FFFFFF"
      stroke="#C6C9CD"
      strokeWidth="1.2"
    />
    <rect
      x="320"
      y="250"
      width="60"
      height="30"
      rx="6"
      fill="#FFFFFF"
      stroke="#C6C9CD"
      strokeWidth="1.2"
    />

    {/* Sparkles */}
    <path
      d="M50 90 53 96l6 3-6 3-3 6-3-6-6-3 6-3 3-6Z"
      fill="#7671FF"
    />
    <path
      d="M430 250 432 254l4 2-4 2-2 4-2-4-4-2 4-2 2-4Z"
      fill="#CB0C9F"
    />
    <circle cx="450" cy="80" r="3" fill="#8159BB" />
    <circle cx="50" cy="280" r="2.5" fill="#8159BB" />
  </svg>
);

// Per-category illustration used as the thumbnail on directory cards.
// Each variant reuses the same simple line-art shape language so cards
// look consistent across subsections.

const ICONS = {
  websites: (
    <g>
      <rect
        x="34"
        y="22"
        width="60"
        height="40"
        rx="4"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <line x1="34" y1="32" x2="94" y2="32" stroke="#8159BB" strokeWidth="1.6" />
      <circle cx="40" cy="27" r="1.2" fill="#8159BB" />
      <circle cx="44" cy="27" r="1.2" fill="#8159BB" />
      <line x1="40" y1="40" x2="68" y2="40" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="40" y1="46" x2="78" y2="46" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="40" y1="52" x2="58" y2="52" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
  'landing-pages': (
    <g>
      <rect
        x="44"
        y="20"
        width="40"
        height="44"
        rx="3"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect x="52" y="28" width="24" height="4" rx="1" fill="#8159BB" />
      <rect x="52" y="36" width="24" height="2" rx="1" fill="#C6C9CD" />
      <rect x="52" y="40" width="18" height="2" rx="1" fill="#C6C9CD" />
      <rect x="56" y="48" width="16" height="6" rx="1.5" fill="#8159BB" />
    </g>
  ),
  portfolios: (
    <g>
      <rect
        x="30"
        y="22"
        width="24"
        height="40"
        rx="2"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect
        x="58"
        y="22"
        width="24"
        height="40"
        rx="2"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <line x1="34" y1="30" x2="50" y2="30" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="34" y1="36" x2="50" y2="36" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="34" y1="42" x2="46" y2="42" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="34" y1="48" x2="50" y2="48" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="62" y1="30" x2="78" y2="30" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="62" y1="36" x2="78" y2="36" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="62" y1="42" x2="74" y2="42" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="62" y1="48" x2="78" y2="48" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
  blogs: (
    <g>
      <rect
        x="34"
        y="20"
        width="60"
        height="44"
        rx="3"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect x="40" y="26" width="34" height="3" rx="1" fill="#8159BB" />
      <line x1="40" y1="34" x2="88" y2="34" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="40" y1="40" x2="84" y2="40" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="40" y1="46" x2="78" y2="46" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="40" y1="52" x2="60" y2="52" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
  stores: (
    <g>
      <path
        d="M32 28h64l-4 32a2 2 0 0 1-2 2H38a2 2 0 0 1-2-2L32 28Z"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
        strokeLinejoin="round"
      />
      <path
        d="M44 28v-4a8 8 0 0 1 16 0v4"
        stroke="#8159BB"
        strokeWidth="1.6"
        fill="none"
      />
    </g>
  ),
  'link-in-bio': (
    <g>
      <rect
        x="40"
        y="20"
        width="48"
        height="44"
        rx="6"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <circle cx="64" cy="30" r="4" fill="#8159BB" />
      <line x1="48" y1="42" x2="80" y2="42" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="48" y1="48" x2="74" y2="48" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="48" y1="54" x2="80" y2="54" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
};

export const CategoryThumb = ({ category, className = '' }) => (
  <svg
    className={className}
    width="128"
    height="84"
    viewBox="0 0 128 84"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
  >
    <rect width="128" height="84" rx="6" fill="#F4F6F8" />
    {ICONS[category]}
  </svg>
);

// Browse-by-category illustration (slightly larger)
const BROWSE_ICONS = {
  websites: (
    <g>
      <rect
        x="20"
        y="14"
        width="60"
        height="42"
        rx="4"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <line x1="20" y1="24" x2="80" y2="24" stroke="#8159BB" strokeWidth="1.6" />
      <circle cx="26" cy="19" r="1.2" fill="#8159BB" />
      <circle cx="30" cy="19" r="1.2" fill="#8159BB" />
      <rect x="26" y="32" width="32" height="6" rx="1" fill="#8159BB" />
      <line x1="26" y1="42" x2="58" y2="42" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="26" y1="46" x2="64" y2="46" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
  'landing-pages': (
    <g>
      <rect
        x="34"
        y="12"
        width="32"
        height="44"
        rx="3"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect x="40" y="18" width="20" height="4" rx="1" fill="#8159BB" />
      <rect x="40" y="26" width="20" height="2" rx="1" fill="#C6C9CD" />
      <rect x="40" y="30" width="16" height="2" rx="1" fill="#C6C9CD" />
      <rect x="42" y="38" width="16" height="6" rx="1.5" fill="#8159BB" />
    </g>
  ),
  portfolios: (
    <g>
      <rect
        x="16"
        y="14"
        width="22"
        height="42"
        rx="2"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect
        x="42"
        y="14"
        width="22"
        height="42"
        rx="2"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect
        x="68"
        y="14"
        width="22"
        height="42"
        rx="2"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <line x1="20" y1="22" x2="34" y2="22" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="20" y1="30" x2="34" y2="30" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="20" y1="38" x2="30" y2="38" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="46" y1="22" x2="60" y2="22" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="46" y1="30" x2="60" y2="30" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="46" y1="38" x2="56" y2="38" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="72" y1="22" x2="86" y2="22" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="72" y1="30" x2="86" y2="30" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="72" y1="38" x2="82" y2="38" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
  blogs: (
    <g>
      <rect
        x="20"
        y="12"
        width="60"
        height="44"
        rx="3"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <rect x="26" y="18" width="34" height="3" rx="1" fill="#8159BB" />
      <line x1="26" y1="26" x2="74" y2="26" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="26" y1="32" x2="68" y2="32" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="26" y1="38" x2="74" y2="38" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="26" y1="44" x2="56" y2="44" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
  stores: (
    <g>
      <path
        d="M18 22h64l-4 32a2 2 0 0 1-2 2H24a2 2 0 0 1-2-2L18 22Z"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
        strokeLinejoin="round"
      />
      <path
        d="M30 22v-4a10 10 0 0 1 20 0v4"
        stroke="#8159BB"
        strokeWidth="1.6"
        fill="none"
      />
    </g>
  ),
  'link-in-bio': (
    <g>
      <rect
        x="26"
        y="12"
        width="48"
        height="44"
        rx="6"
        fill="#FFFFFF"
        stroke="#8159BB"
        strokeWidth="1.6"
      />
      <circle cx="50" cy="22" r="4" fill="#8159BB" />
      <line x1="34" y1="34" x2="66" y2="34" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="34" y1="40" x2="60" y2="40" stroke="#C6C9CD" strokeWidth="1.2" />
      <line x1="34" y1="46" x2="66" y2="46" stroke="#C6C9CD" strokeWidth="1.2" />
    </g>
  ),
};

export const BrowseCategoryIllustration = ({ category, className = '' }) => (
  <svg
    className={className}
    width="100"
    height="64"
    viewBox="0 0 100 64"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
  >
    <rect width="100" height="64" rx="6" fill="#F4F6F8" />
    {BROWSE_ICONS[category]}
  </svg>
);
