export const STRK_PROJECT_URL = 'xxx'
export const STRK_PROJECT_ANON_KEY = 'xx'
export const SITE_ID = 'xxx'
export const REQUEST_DOMAIN = 'https://www.uat.strikingly.com'
export const S3_DOMAIN = 'https://strikingly-user-asset-images-dev.s3.ap-northeast-1.amazonaws.com'
