export const categories = [
  {
    id: 'websites',
    name: 'Websites',
    description: 'AI-built business and personal sites for any goal.',
    href: '#websites',
  },
  {
    id: 'landing-pages',
    name: 'Landing Pages',
    description: 'Single-page sites built to convert visitors fast.',
    href: '#landing-pages',
  },
  {
    id: 'portfolios',
    name: 'Portfolios',
    description: 'Showcase your work with a clean, focused site.',
    href: '#portfolios',
  },
  {
    id: 'blogs',
    name: 'Blogs',
    description: 'Publish-ready blogs with built-in SEO basics.',
    href: '#blogs',
  },
  {
    id: 'stores',
    name: 'Online Stores',
    description: 'Sell products online with payments built in.',
    href: '#stores',
  },
  {
    id: 'link-in-bio',
    name: 'Link-in-Bio',
    description: 'One link, all your places. Made for creators.',
    href: '#link-in-bio',
  },
];

export const featuredGenerators = [
  { name: 'AI Website Generator', description: 'Describe your business, get a full site', category: 'Website', slug: 'ai-website-generator' },
  { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', category: 'Portfolio', slug: 'free-portfolio-generator' },
  { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', category: 'Landing Page', slug: 'ai-landing-page-maker' },
  { name: 'Online Store Builder', description: 'Start selling without writing code', category: 'Store', slug: 'online-store-builder' },
  { name: 'Link-in-Bio Generator', description: 'One link for all your channels', category: 'Link-in-Bio', slug: 'link-in-bio-generator' },
  { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', category: 'Website', slug: 'one-page-website-builder' },
  { name: 'Wedding Website Generator', description: 'Share your day with guests', category: 'Website', slug: 'wedding-website-generator' },
  { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', category: 'Website', slug: 'restaurant-website-builder' },
  { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', category: 'Blog', slug: 'blog-generator-for-beginners' },
];

export const allGenerators = {
  websites: [
    { name: 'AI Website Generator', description: 'Describe your business, get a full site', slug: 'ai-website-generator' },
    { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', slug: 'one-page-website-builder' },
    { name: 'Wedding Website Generator', description: 'Share your day with guests', slug: 'wedding-website-generator' },
    { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', slug: 'restaurant-website-builder' },
    { name: 'Free Website Builder for Photographers', description: 'Stunning photo galleries, zero cost', slug: 'free-website-builder-for-photographers' },
    { name: 'Small Business Website Generator', description: 'Professional sites for local businesses', slug: 'small-business-website-generator' },
    { name: 'Real Estate Website Builder', description: 'Listings, tours, and contact forms', slug: 'real-estate-website-builder' },
    { name: 'Nonprofit Website Generator', description: 'Tell your mission, accept donations', slug: 'nonprofit-website-generator' },
    { name: 'Fitness Website Builder', description: 'Class schedules, bookings, and more', slug: 'fitness-website-builder' },
    { name: 'AI Website Builder for Yoga Instructors', description: 'Calm design for wellness professionals', slug: 'ai-website-builder-for-yoga-instructors' },
    { name: 'Beautiful Website Generator', description: 'Design-forward sites that impress', slug: 'beautiful-website-generator' },
  ],
  'landing-pages': [
    { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', slug: 'ai-landing-page-maker' },
    { name: 'Free Landing Page Generator', description: 'No-cost pages that capture leads', slug: 'free-landing-page-generator' },
    { name: 'SaaS Landing Page Builder', description: 'Feature highlights and signup flows', slug: 'saas-landing-page-builder' },
    { name: 'Event Landing Page Generator', description: 'Countdown, speakers, and registration', slug: 'event-landing-page-generator' },
    { name: 'Product Launch Page Builder', description: 'Build buzz before you ship', slug: 'product-launch-page-builder' },
    { name: 'App Download Landing Page', description: 'Drive installs with a focused page', slug: 'app-download-landing-page' },
    { name: 'Lead Capture Page Generator', description: 'Forms and CTAs that convert', slug: 'lead-capture-page-generator' },
    { name: 'Webinar Registration Page Builder', description: 'Signups, reminders, and replays', slug: 'webinar-registration-page-builder' },
    { name: 'No-Code Landing Page Generator', description: 'Drag, drop, publish — no dev needed', slug: 'no-code-landing-page-generator' },
    { name: 'Coming Soon Page Builder', description: 'Tease your next big thing', slug: 'coming-soon-page-builder' },
  ],
  portfolios: [
    { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', slug: 'free-portfolio-generator' },
    { name: 'Portfolio Generator for Designers', description: 'Showcase UI, branding, and illustration', slug: 'portfolio-generator-for-designers' },
    { name: 'Photography Portfolio Builder', description: 'Full-bleed images, minimal UI', slug: 'photography-portfolio-builder' },
    { name: 'Artist Portfolio Generator', description: 'Gallery layouts for fine art and mixed media', slug: 'artist-portfolio-generator' },
    { name: 'Writer Portfolio Builder', description: 'Clippings, publications, and bio', slug: 'writer-portfolio-builder' },
    { name: 'Architecture Portfolio Generator', description: 'Project showcases with drawings and renders', slug: 'architecture-portfolio-generator' },
    { name: 'Student Portfolio Builder', description: 'Academic work, clean and professional', slug: 'student-portfolio-builder' },
    { name: 'Freelancer Portfolio Generator', description: 'Case studies, testimonials, and rates', slug: 'freelancer-portfolio-generator' },
    { name: 'Video Portfolio Builder', description: 'Embedded reels and project pages', slug: 'video-portfolio-builder' },
  ],
  blogs: [
    { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', slug: 'blog-generator-for-beginners' },
    { name: 'AI Blog Builder', description: 'AI writes your first posts with you', slug: 'ai-blog-builder' },
    { name: 'Personal Blog Generator', description: 'Share stories, your way', slug: 'personal-blog-generator' },
    { name: 'Travel Blog Builder', description: 'Maps, photo essays, and itineraries', slug: 'travel-blog-builder' },
    { name: 'Food Blog Generator', description: 'Recipes, reviews, and mouth-watering photos', slug: 'food-blog-generator' },
    { name: 'Tech Blog Builder', description: 'Code snippets, tutorials, and deep dives', slug: 'tech-blog-builder' },
    { name: 'Lifestyle Blog Generator', description: 'Topics that inspire your audience', slug: 'lifestyle-blog-generator' },
    { name: 'Free Blog Generator', description: 'Start writing without spending a cent', slug: 'free-blog-generator' },
    { name: 'News Blog Builder', description: 'Timely posts with categories and tags', slug: 'news-blog-builder' },
    { name: 'Niche Blog Generator', description: 'Focused content for focused readers', slug: 'niche-blog-generator' },
  ],
  stores: [
    { name: 'Online Store Builder', description: 'Start selling without writing code', slug: 'online-store-builder' },
    { name: 'Online Store Builder for Restaurants', description: 'Menus, ordering, and delivery setup', slug: 'online-store-builder-for-restaurants' },
    { name: 'Fashion Store Generator', description: 'Lookbooks, sizes, and quick checkout', slug: 'fashion-store-generator' },
    { name: 'Handmade Shop Builder', description: 'Craft-focused storefronts with story', slug: 'handmade-shop-builder' },
    { name: 'Digital Product Store Generator', description: 'Sell downloads, courses, and templates', slug: 'digital-product-store-generator' },
    { name: 'Subscription Box Store Builder', description: 'Recurring billing and unboxing pages', slug: 'subscription-box-store-builder' },
    { name: 'Free Online Store Generator', description: 'No fees to get your first sale', slug: 'free-online-store-generator' },
    { name: 'Print-on-Demand Store Builder', description: 'Design it, we print and ship', slug: 'print-on-demand-store-builder' },
    { name: 'Art Store Generator', description: 'Sell prints and originals with style', slug: 'art-store-generator' },
    { name: 'AI Store Builder', description: 'Describe your products, get a shop', slug: 'ai-store-builder' },
  ],
  'link-in-bio': [
    { name: 'Link-in-Bio Generator', description: 'One link for all your channels', slug: 'link-in-bio-generator' },
    { name: 'Linktree Alternative Builder', description: 'More design control, same simplicity', slug: 'linktree-alternative-builder' },
    { name: 'Creator Link Page Generator', description: 'Tips, merch, and social links in one place', slug: 'creator-link-page-generator' },
    { name: 'Musician Link-in-Bio Builder', description: 'Streaming links, tour dates, and merch', slug: 'musician-link-in-bio-builder' },
    { name: 'Influencer Bio Link Generator', description: 'Sponsored links, collabs, and content hubs', slug: 'influencer-bio-link-generator' },
    { name: 'Podcast Link Page Builder', description: 'Episodes, subscribe buttons, and show notes', slug: 'podcast-link-page-builder' },
    { name: 'Free Link-in-Bio Generator', description: 'All your links, zero cost', slug: 'free-link-in-bio-generator' },
    { name: 'AI Link Page Generator', description: 'Describe yourself, get a link page', slug: 'ai-link-page-generator' },
  ],
};

export const categorySlugMap = {
  websites: 'Website',
  'landing-pages': 'Landing Page',
  portfolios: 'Portfolio',
  blogs: 'Blog',
  stores: 'Store',
  'link-in-bio': 'Link-in-Bio',
};
