export const featuredGenerators = [
  { name: "AI Website Generator", description: "Describe your business, get a full site", slug: "ai-website-generator", category: "Websites" },
  { name: "Free Portfolio Generator", description: "For creatives, in minutes, no fee", slug: "free-portfolio-generator", category: "Portfolios" },
  { name: "AI Landing Page Maker", description: "One-page sites built to convert", slug: "ai-landing-page-maker", category: "Landing Pages" },
  { name: "Online Store Builder", description: "Start selling without writing code", slug: "online-store-builder", category: "Stores" },
  { name: "Link-in-Bio Generator", description: "One link for all your channels", slug: "link-in-bio-generator", category: "Link-in-Bio" },
  { name: "One-Page Website Builder", description: "Simple sites, single scroll", slug: "one-page-website-builder", category: "Websites" },
  { name: "Wedding Website Generator", description: "Share your day with guests", slug: "wedding-website-generator", category: "Websites" },
  { name: "Restaurant Website Builder", description: "Menu, hours, reservations, done", slug: "restaurant-website-builder", category: "Websites" },
  { name: "Blog Generator for Beginners", description: "Publish-ready in minutes", slug: "blog-generator-for-beginners", category: "Blogs" },
];

export const categories = [
  {
    id: "websites",
    name: "Websites",
    description: "AI-built business and personal sites for any goal.",
    icon: "globe",
  },
  {
    id: "landing-pages",
    name: "Landing Pages",
    description: "Single-page sites built to convert visitors fast.",
    icon: "megaphone",
  },
  {
    id: "portfolios",
    name: "Portfolios",
    description: "Showcase your work with a clean, focused site.",
    icon: "briefcase",
  },
  {
    id: "blogs",
    name: "Blogs",
    description: "Publish-ready blogs with built-in SEO basics.",
    icon: "pencil",
  },
  {
    id: "stores",
    name: "Online Stores",
    description: "Sell products online with payments built in.",
    icon: "shoppingBag",
  },
  {
    id: "link-in-bio",
    name: "Link-in-Bio",
    description: "One link, all your places. Made for creators.",
    icon: "link",
  },
];

export const allGenerators = {
  websites: {
    title: "Websites",
    description: "AI-built business and personal sites for any goal.",
    generators: [
      { name: "AI Website Generator", description: "Describe your business, get a full site in seconds.", slug: "ai-website-generator" },
      { name: "Free Website Builder", description: "Create a website at no cost, no coding needed.", slug: "free-website-builder" },
      { name: "One-Page Website Builder", description: "Simple sites, single scroll, zero complexity.", slug: "one-page-website-builder" },
      { name: "Wedding Website Generator", description: "Share your wedding day details with guests.", slug: "wedding-website-generator" },
      { name: "Restaurant Website Builder", description: "Menu, hours, reservations — all built in.", slug: "restaurant-website-builder" },
      { name: "Small Business Website Generator", description: "Get online fast with a professional site.", slug: "small-business-website-generator" },
      { name: "Website Builder for Photographers", description: "Showcase your photography with style.", slug: "website-builder-for-photographers" },
      { name: "Church Website Generator", description: "Announcements, events, and community in one place.", slug: "church-website-generator" },
      { name: "Real Estate Website Builder", description: "Listings, contact forms, and virtual tours.", slug: "real-estate-website-builder" },
      { name: "Gym Website Generator", description: "Classes, schedules, and sign-ups for your fitness studio.", slug: "gym-website-generator" },
      { name: "No-Code Website Builder", description: "Build a full site without writing a single line.", slug: "no-code-website-builder" },
      { name: "Beautiful Website Generator", description: "Polished designs that look like a pro made them.", slug: "beautiful-website-generator" },
    ],
  },
  "landing-pages": {
    title: "Landing Pages",
    description: "Single-page sites built to convert visitors fast.",
    generators: [
      { name: "AI Landing Page Maker", description: "One-page sites built to convert visitors.", slug: "ai-landing-page-maker" },
      { name: "Free Landing Page Builder", description: "Create high-converting pages at no cost.", slug: "free-landing-page-builder" },
      { name: "SaaS Landing Page Generator", description: "Feature sections, pricing, and sign-up flows.", slug: "saas-landing-page-generator" },
      { name: "Product Launch Page Builder", description: "Announce your product with a stunning page.", slug: "product-launch-page-builder" },
      { name: "Event Landing Page Generator", description: "Promote your event and capture registrations.", slug: "event-landing-page-generator" },
      { name: "App Landing Page Builder", description: "Showcase your app with screenshots and download links.", slug: "app-landing-page-builder" },
      { name: "Lead Capture Page Generator", description: "Collect emails with a focused, distraction-free page.", slug: "lead-capture-page-generator" },
      { name: "Startup Landing Page Builder", description: "Pitch your startup and gather early interest.", slug: "startup-landing-page-builder" },
      { name: "Coming Soon Page Generator", description: "Build hype before your launch goes live.", slug: "coming-soon-page-generator" },
      { name: "Webinar Landing Page Builder", description: "Drive sign-ups for your next online event.", slug: "webinar-landing-page-builder" },
    ],
  },
  portfolios: {
    title: "Portfolios",
    description: "Showcase your work with a clean, focused site.",
    generators: [
      { name: "Free Portfolio Generator", description: "For creatives, in minutes, no fee.", slug: "free-portfolio-generator" },
      { name: "Portfolio Generator for Designers", description: "Showcase design work with clean layouts.", slug: "portfolio-generator-for-designers" },
      { name: "Photography Portfolio Builder", description: "Let your photos do the talking.", slug: "photography-portfolio-builder" },
      { name: "Freelancer Portfolio Generator", description: "Highlight projects and attract new clients.", slug: "freelancer-portfolio-generator" },
      { name: "Video Portfolio Builder", description: "Display reels and video projects beautifully.", slug: "video-portfolio-builder" },
      { name: "Artist Portfolio Generator", description: "A gallery-style site for your artwork.", slug: "artist-portfolio-generator" },
      { name: "Writer Portfolio Builder", description: "Publish clips and writing samples with ease.", slug: "writer-portfolio-builder" },
      { name: "Architecture Portfolio Generator", description: "Present projects with immersive layouts.", slug: "architecture-portfolio-generator" },
      { name: "AI Portfolio Generator", description: "Describe your work, get a polished portfolio.", slug: "ai-portfolio-generator" },
      { name: "No-Code Portfolio Builder", description: "Build a portfolio without any coding skills.", slug: "no-code-portfolio-builder" },
    ],
  },
  blogs: {
    title: "Blogs",
    description: "Publish-ready blogs with built-in SEO basics.",
    generators: [
      { name: "Blog Generator for Beginners", description: "Publish-ready in minutes, no experience needed.", slug: "blog-generator-for-beginners" },
      { name: "AI Blog Builder", description: "Generate a blog with posts and categories instantly.", slug: "ai-blog-builder" },
      { name: "Free Blog Generator", description: "Start blogging at zero cost.", slug: "free-blog-generator" },
      { name: "Travel Blog Generator", description: "Share your adventures with beautiful layouts.", slug: "travel-blog-generator" },
      { name: "Food Blog Builder", description: "Recipes, photos, and stories in one place.", slug: "food-blog-builder" },
      { name: "Personal Blog Generator", description: "Your thoughts, your style, your blog.", slug: "personal-blog-generator" },
      { name: "Fashion Blog Builder", description: "Style posts with gallery-friendly layouts.", slug: "fashion-blog-builder" },
      { name: "Tech Blog Generator", description: "Tutorials, reviews, and tech news — styled right.", slug: "tech-blog-generator" },
      { name: "Lifestyle Blog Builder", description: "Wellness, beauty, and daily life content.", slug: "lifestyle-blog-builder" },
      { name: "SEO Blog Generator", description: "Blog posts optimized for search from day one.", slug: "seo-blog-generator" },
    ],
  },
  stores: {
    title: "Online Stores",
    description: "Sell products online with payments built in.",
    generators: [
      { name: "Online Store Builder", description: "Start selling without writing code.", slug: "online-store-builder" },
      { name: "AI Store Generator", description: "Describe your products, get a ready store.", slug: "ai-store-generator" },
      { name: "Free Online Store Builder", description: "Launch your store at no cost.", slug: "free-online-store-builder" },
      { name: "Clothing Store Generator", description: "Fashion e-commerce with size guides and lookbooks.", slug: "clothing-store-generator" },
      { name: "Restaurant Online Ordering Builder", description: "Take orders online with a simple menu.", slug: "restaurant-online-ordering-builder" },
      { name: "Digital Products Store Generator", description: "Sell downloads, courses, and memberships.", slug: "digital-products-store-generator" },
      { name: "Jewelry Store Builder", description: "Elegant layouts for handcrafted pieces.", slug: "jewelry-store-builder" },
      { name: "Print-on-Demand Store Generator", description: "Sell custom merch with no inventory.", slug: "print-on-demand-store-generator" },
      { name: "Handmade Goods Store Builder", description: "Perfect for Etsy sellers expanding to their own site.", slug: "handmade-goods-store-builder" },
      { name: "No-Code Store Builder", description: "Full e-commerce without touching code.", slug: "no-code-store-builder" },
    ],
  },
  "link-in-bio": {
    title: "Link-in-Bio",
    description: "One link, all your places. Made for creators.",
    generators: [
      { name: "Link-in-Bio Generator", description: "One link for all your channels.", slug: "link-in-bio-generator" },
      { name: "AI Link-in-Bio Builder", description: "Describe yourself, get a ready bio page.", slug: "ai-link-in-bio-builder" },
      { name: "Free Link-in-Bio Page", description: "A bio page at no cost, ready in seconds.", slug: "free-link-in-bio-page" },
      { name: "Creator Link-in-Bio Generator", description: "Built for YouTubers, streamers, and influencers.", slug: "creator-link-in-bio-generator" },
      { name: "Musician Link-in-Bio Builder", description: "Link your music, merch, and tour dates.", slug: "musician-link-in-bio-builder" },
      { name: "Podcast Link-in-Bio Generator", description: "All your episodes and platforms in one link.", slug: "podcast-link-in-bio-generator" },
      { name: "Small Business Link-in-Bio Builder", description: "Hours, contact, and social links for local businesses.", slug: "small-business-link-in-bio-builder" },
      { name: "Influencer Link-in-Bio Generator", description: "Brand collabs, affiliate links, and content hubs.", slug: "influencer-link-in-bio-generator" },
      { name: "Resume Link-in-Bio Builder", description: "Your professional links and portfolio in one place.", slug: "resume-link-in-bio-builder" },
      { name: "Event Link-in-Bio Generator", description: "Tickets, schedule, and social links for events.", slug: "event-link-in-bio-generator" },
    ],
  },
};
