const products = [
  {
    id: 'vivid-aura-jewels',
    name: 'Vivid Aura Jewels',
    slug: 'vivid-aura-jewels',
    price: 42,
    category: 'earrings',
    subcategory: 'ear-cuffs',
    description: 'A luminous gold ear cuff with a delicate crystal accent. Designed to wrap elegantly around the ear for a modern, editorial finish. Plated in 18K gold over brass with a single cubic zirconia stone.',
    rating: 4.8,
    reviewCount: 124,
    materials: '18K gold plated brass, cubic zirconia',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold', 'silver'],
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'majestic-flora-nectar',
    name: 'Majestic Flora Nectar',
    slug: 'majestic-flora-nectar',
    price: 68,
    category: 'necklaces',
    subcategory: 'statement',
    description: 'A blooming floral necklace featuring multicolor crystal accents. The pendant captures light from every angle, suspended on a fine gold chain. An heirloom-inspired piece for day-to-evening elegance.',
    rating: 4.9,
    reviewCount: 89,
    materials: '18K gold plated brass, multicolor crystals',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold', 'silver'],
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'golden-sphere-huggies',
    name: 'Golden Sphere Huggies',
    slug: 'golden-sphere-huggies',
    price: 38,
    category: 'earrings',
    subcategory: 'huggies',
    description: 'Chunky gold dome huggie earrings with a sculptural rounded profile. The perfect everyday staple — substantial enough to wear alone, sleek enough to stack. Available in gold and silver tones.',
    rating: 4.7,
    reviewCount: 210,
    materials: '18K gold plated brass',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold', 'silver'],
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'amber-lace-earrings',
    name: 'Amber Lace Earrings',
    slug: 'amber-lace-earrings',
    price: 54,
    category: 'earrings',
    subcategory: 'drop',
    description: 'Intricately textured gold filigree drop earrings inspired by vintage lacework. Each earring is meticulously crafted with an openwork pattern that catches the light with every movement. Lightweight and eye-catching.',
    rating: 4.6,
    reviewCount: 67,
    materials: '18K gold plated brass',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold', 'silver'],
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'royal-heirloom-set',
    name: 'Royal Heirloom Set',
    slug: 'royal-heirloom-set',
    price: 95,
    category: 'sets',
    subcategory: 'gift-sets',
    description: 'A curated gift-boxed set pairing our signature earrings with a matching necklace. Presented in a velvet-lined Velmora keepsake box, ready for gifting. The ultimate demi-fine ensemble for someone special.',
    rating: 5.0,
    reviewCount: 43,
    materials: '18K gold plated brass, cubic zirconia',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold', 'silver'],
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'luminous-pearl-stud',
    name: 'Luminous Pearl Stud',
    slug: 'luminous-pearl-stud',
    price: 48,
    category: 'earrings',
    subcategory: 'studs',
    description: 'Classic freshwater pearl studs set in 18K gold plated brass. Timeless, refined, and effortlessly chic. The pearl\'s natural iridescence pairs beautifully with the warm gold setting.',
    rating: 4.9,
    reviewCount: 156,
    materials: '18K gold plated brass, freshwater pearl',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold'],
    bestseller: false,
    newArrival: true,
  },
  {
    id: 'petite-chain-necklace',
    name: 'Petite Chain Necklace',
    slug: 'petite-chain-necklace',
    price: 36,
    category: 'necklaces',
    subcategory: 'chains',
    description: 'A delicate 18K gold plated chain necklace with a subtle shimmer. Wear it solo for a whisper of gold or layer it with other Velmora pieces for a curated look. Adjustable length.',
    rating: 4.7,
    reviewCount: 98,
    materials: '18K gold plated brass',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold', 'silver'],
    bestseller: false,
    newArrival: true,
  },
  {
    id: 'celestial-drop-earrings',
    name: 'Celestial Drop Earrings',
    slug: 'celestial-drop-earrings',
    price: 58,
    category: 'earrings',
    subcategory: 'drop',
    description: 'Sculptural drop earrings with a celestial-inspired arc. The brushed gold finish creates a soft, satin-like glow. Modern and architectural — a conversation piece for any occasion.',
    rating: 4.5,
    reviewCount: 34,
    materials: '18K gold plated brass',
    care: 'Avoid contact with water, perfume, and lotions. Store in the provided Velmora pouch. Clean gently with a soft cloth.',
    shipping: 'Free worldwide shipping on all orders. Estimated delivery: 5–10 business days.',
    returns: '30-day returns. Items must be unworn and in original packaging.',
    colors: ['gold'],
    bestseller: false,
    newArrival: true,
  },
]

export const categories = [
  { id: 'earrings', name: 'Earrings', query: 'gold earrings editorial display warm neutral' },
  { id: 'necklaces', name: 'Necklaces', query: 'gold necklace editorial display warm neutral' },
  { id: 'huggies', name: 'Huggies', query: 'gold huggie earrings editorial display warm' },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sarah M.',
    text: 'Absolutely stunning quality. The gold finish is flawless and the pieces feel substantial. I get compliments every time I wear my Velmora earrings.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Emily R.',
    text: 'The packaging alone is an experience. I bought the Royal Heirloom Set for my sister\'s birthday and she was blown away. Will definitely be back for more.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Jessica K.',
    text: 'I\'ve been searching for demi-fine jewelry that doesn\'t look cheap and Velmora delivers. The Golden Sphere Huggies are my everyday go-to. Worth every penny.',
    rating: 5,
  },
]

export const ugcItems = [
  { id: 'ugc-1', caption: 'Everyday gold stacking', query: 'woman wearing gold earrings huggies selfie warm' },
  { id: 'ugc-2', caption: 'Date night shimmer', query: 'woman wearing gold necklace closeup neck warm' },
  { id: 'ugc-3', caption: 'Morning light details', query: 'gold ear cuff on ear selfie editorial warm' },
  { id: 'ugc-4', caption: 'Layered & loved', query: 'gold necklace layering on woman fashion editorial' },
  { id: 'ugc-5', caption: 'Brunch in bloom', query: 'woman wearing crystal floral necklace casual warm' },
  { id: 'ugc-6', caption: 'Gift that glows', query: 'unboxing gold jewelry gift box hands warm' },
]

export default products