// Generator data organized by category
// Each generator: { name, description, slug, category }

export const generators = {
  websites: [
    { name: 'AI Website Generator', description: 'Describe your business, get a full site', slug: 'ai-website-generator', category: 'Website' },
    { name: 'Free Website Builder for Photographers', description: 'Portfolio-ready sites for your lens work', slug: 'free-website-builder-photographers', category: 'Website' },
    { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', slug: 'one-page-website-builder', category: 'Website' },
    { name: 'Wedding Website Generator', description: 'Share your day with guests', slug: 'wedding-website-generator', category: 'Website' },
    { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', slug: 'restaurant-website-builder', category: 'Website' },
    { name: 'AI Business Website Creator', description: 'Professional sites for startups and SMBs', slug: 'ai-business-website-creator', category: 'Website' },
    { name: 'Free Website Builder for Yoga Instructors', description: 'Class schedules and bookings built in', slug: 'free-website-builder-yoga-instructors', category: 'Website' },
    { name: 'No-Code Website Builder for Coaches', description: 'Book clients without writing code', slug: 'no-code-website-builder-coaches', category: 'Website' },
    { name: 'Beautiful Website Generator for Artists', description: 'Showcase your art with style', slug: 'beautiful-website-generator-artists', category: 'Website' },
    { name: 'AI Website Builder for Real Estate', description: 'Listings, agents, and leads in one site', slug: 'ai-website-builder-real-estate', category: 'Website' },
    { name: 'Free Website Builder for Musicians', description: 'Tour dates, music, and merch in one place', slug: 'free-website-builder-musicians', category: 'Website' },
    { name: 'Small Business Website Generator', description: 'Get online fast with a professional site', slug: 'small-business-website-generator', category: 'Website' },
  ],
  'landing-pages': [
    { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', slug: 'ai-landing-page-maker', category: 'Landing Page' },
    { name: 'Free Landing Page Generator for SaaS', description: 'Launch your product page in minutes', slug: 'free-landing-page-generator-saas', category: 'Landing Page' },
    { name: 'Lead Capture Landing Page Builder', description: 'Collect emails with a focused page', slug: 'lead-capture-landing-page-builder', category: 'Landing Page' },
    { name: 'AI Landing Page for Webinars', description: 'Register attendees with a high-converting page', slug: 'ai-landing-page-webinars', category: 'Landing Page' },
    { name: 'Product Launch Landing Page Generator', description: 'Announce your launch with impact', slug: 'product-launch-landing-page-generator', category: 'Landing Page' },
    { name: 'Free Landing Page Builder for Apps', description: 'Drive downloads with a sleek app page', slug: 'free-landing-page-builder-apps', category: 'Landing Page' },
    { name: 'Event Landing Page Creator', description: 'Promote your event and sell tickets', slug: 'event-landing-page-creator', category: 'Landing Page' },
    { name: 'AI Landing Page for Ebooks', description: 'Grow your list with a lead magnet page', slug: 'ai-landing-page-ebooks', category: 'Landing Page' },
    { name: 'Coming Soon Landing Page Generator', description: 'Build hype before you launch', slug: 'coming-soon-landing-page-generator', category: 'Landing Page' },
    { name: 'Free Landing Page for Consultants', description: 'Book calls with a focused page', slug: 'free-landing-page-consultants', category: 'Landing Page' },
  ],
  portfolios: [
    { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', slug: 'free-portfolio-generator', category: 'Portfolio' },
    { name: 'Portfolio Generator for Designers', description: 'Showcase your work with clean layouts', slug: 'portfolio-generator-designers', category: 'Portfolio' },
    { name: 'AI Portfolio Builder for Developers', description: 'Code projects and skills, beautifully presented', slug: 'ai-portfolio-builder-developers', category: 'Portfolio' },
    { name: 'Photography Portfolio Generator', description: 'Full-screen galleries for your best shots', slug: 'photography-portfolio-generator', category: 'Portfolio' },
    { name: 'Free Portfolio for Writers', description: 'Publish your clips and attract clients', slug: 'free-portfolio-writers', category: 'Portfolio' },
    { name: 'AI Portfolio for Architects', description: 'Project showcases with visual impact', slug: 'ai-portfolio-architects', category: 'Portfolio' },
    { name: 'Model Portfolio Generator', description: 'Comp cards and galleries in one site', slug: 'model-portfolio-generator', category: 'Portfolio' },
    { name: 'Free Portfolio Builder for Filmmakers', description: 'Reels, credits, and contact in one place', slug: 'free-portfolio-builder-filmmakers', category: 'Portfolio' },
    { name: 'AI Portfolio for Illustrators', description: 'Show your art with minimal distraction', slug: 'ai-portfolio-illustrators', category: 'Portfolio' },
    { name: 'Student Portfolio Generator', description: 'Land internships with a polished site', slug: 'student-portfolio-generator', category: 'Portfolio' },
  ],
  blogs: [
    { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', slug: 'blog-generator-beginners', category: 'Blog' },
    { name: 'AI Blog Builder for Travelers', description: 'Share your journeys with built-in SEO', slug: 'ai-blog-builder-travelers', category: 'Blog' },
    { name: 'Free Blog Generator for Foodies', description: 'Recipe cards and photos, ready to post', slug: 'free-blog-generator-foodies', category: 'Blog' },
    { name: 'Personal Blog Generator', description: 'Your thoughts, your voice, your site', slug: 'personal-blog-generator', category: 'Blog' },
    { name: 'AI Blog Builder for Tech Writers', description: 'Code snippets and tutorials, beautifully formatted', slug: 'ai-blog-builder-tech-writers', category: 'Blog' },
    { name: 'Free Blog for Lifestyle Creators', description: 'Fashion, wellness, and daily inspiration', slug: 'free-blog-lifestyle-creators', category: 'Blog' },
    { name: 'Niche Blog Generator', description: 'Focus on one topic, grow an audience', slug: 'niche-blog-generator', category: 'Blog' },
    { name: 'AI Blog Builder for Marketers', description: 'Content marketing sites with analytics built in', slug: 'ai-blog-builder-marketers', category: 'Blog' },
    { name: 'Free Blog Generator for Students', description: 'Share your research and ideas', slug: 'free-blog-generator-students', category: 'Blog' },
    { name: 'AI Blog for Small Business Owners', description: 'Build authority with regular posts', slug: 'ai-blog-small-business-owners', category: 'Blog' },
  ],
  stores: [
    { name: 'Online Store Builder', description: 'Start selling without writing code', slug: 'online-store-builder', category: 'Store' },
    { name: 'AI Store Builder for Restaurants', description: 'Menus, orders, and delivery in one site', slug: 'ai-store-builder-restaurants', category: 'Store' },
    { name: 'Free Ecommerce Generator for Artists', description: 'Sell prints and originals online', slug: 'free-ecommerce-generator-artists', category: 'Store' },
    { name: 'AI Store Builder for Fashion', description: 'Lookbooks, sizes, and checkout built in', slug: 'ai-store-builder-fashion', category: 'Store' },
    { name: 'Digital Product Store Generator', description: 'Sell downloads, courses, and templates', slug: 'digital-product-store-generator', category: 'Store' },
    { name: 'Free Store Builder for Makers', description: 'Handmade goods, easy checkout', slug: 'free-store-builder-makers', category: 'Store' },
    { name: 'AI Store for Subscription Boxes', description: 'Recurring billing and member portals', slug: 'ai-store-subscription-boxes', category: 'Store' },
    { name: 'Free Online Store for Bakers', description: 'Custom cakes and treats, ordered online', slug: 'free-online-store-bakers', category: 'Store' },
    { name: 'AI Store Builder for Pet Products', description: 'Food, toys, and accessories in one shop', slug: 'ai-store-builder-pet-products', category: 'Store' },
    { name: 'Pop-Up Store Generator', description: 'Temporary shops for limited drops', slug: 'pop-up-store-generator', category: 'Store' },
  ],
  'link-in-bio': [
    { name: 'Link-in-Bio Generator', description: 'One link for all your channels', slug: 'link-in-bio-generator', category: 'Link-in-Bio' },
    { name: 'Free Link-in-Bio for Instagram Creators', description: 'All your links, one beautiful page', slug: 'free-link-in-bio-instagram-creators', category: 'Link-in-Bio' },
    { name: 'AI Link-in-Bio for Musicians', description: 'Streaming, merch, and tour dates in one link', slug: 'ai-link-in-bio-musicians', category: 'Link-in-Bio' },
    { name: 'Link-in-Bio for Podcasters', description: 'Episodes, sponsors, and subscribe links', slug: 'link-in-bio-podcasters', category: 'Link-in-Bio' },
    { name: 'Free Link-in-Bio for Fitness Coaches', description: 'Programs, bookings, and social in one place', slug: 'free-link-in-bio-fitness-coaches', category: 'Link-in-Bio' },
    { name: 'AI Link-in-Bio for YouTubers', description: 'Videos, merch, and community links', slug: 'ai-link-in-bio-youtubers', category: 'Link-in-Bio' },
    { name: 'Link-in-Bio for Photographers', description: 'Galleries, bookings, and prints in one link', slug: 'link-in-bio-photographers', category: 'Link-in-Bio' },
    { name: 'Free Link-in-Bio for Authors', description: 'Books, events, and newsletter signup', slug: 'free-link-in-bio-authors', category: 'Link-in-Bio' },
    { name: 'AI Link-in-Bio for Chefs', description: 'Recipes, reservations, and catering links', slug: 'ai-link-in-bio-chefs', category: 'Link-in-Bio' },
    { name: 'Link-in-Bio for Nonprofits', description: 'Donate, volunteer, and learn more in one link', slug: 'link-in-bio-nonprofits', category: 'Link-in-Bio' },
  ],
}

// Featured generators (9 tiles mixing categories)
export const featuredGenerators = [
  { name: 'AI Website Generator', description: 'Describe your business, get a full site', slug: 'ai-website-generator', category: 'Website' },
  { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', slug: 'free-portfolio-generator', category: 'Portfolio' },
  { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', slug: 'ai-landing-page-maker', category: 'Landing Page' },
  { name: 'Online Store Builder', description: 'Start selling without writing code', slug: 'online-store-builder', category: 'Store' },
  { name: 'Link-in-Bio Generator', description: 'One link for all your channels', slug: 'link-in-bio-generator', category: 'Link-in-Bio' },
  { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', slug: 'one-page-website-builder', category: 'Website' },
  { name: 'Wedding Website Generator', description: 'Share your day with guests', slug: 'wedding-website-generator', category: 'Website' },
  { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', slug: 'restaurant-website-builder', category: 'Website' },
  { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', slug: 'blog-generator-beginners', category: 'Blog' },
]
