export const categories = [
  {
    slug: 'websites',
    nameKey: 'websites',
    sectionDescription: 'Full websites for business, personal, and everything in between.',
  },
  {
    slug: 'landing-pages',
    nameKey: 'landingPages',
    sectionDescription: 'High-converting single-page sites for campaigns and launches.',
  },
  {
    slug: 'portfolios',
    nameKey: 'portfolios',
    sectionDescription: 'Clean, focused sites to showcase creative and professional work.',
  },
  {
    slug: 'blogs',
    nameKey: 'blogs',
    sectionDescription: 'Publish-ready blogs with built-in SEO and clean reading layouts.',
  },
  {
    slug: 'stores',
    nameKey: 'stores',
    sectionDescription: 'Online stores with product pages, carts, and payments ready.',
  },
  {
    slug: 'link-in-bio',
    nameKey: 'linkInBio',
    sectionDescription: 'One link that connects all your channels and content.',
  },
];

export const featuredGenerators = [
  { name: 'AI Website Generator', description: 'Describe your business, get a full site', category: 'Website', slug: 'ai-website-generator' },
  { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', category: 'Portfolio', slug: 'free-portfolio-generator' },
  { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', category: 'Landing Page', slug: 'ai-landing-page-maker' },
  { name: 'Online Store Builder', description: 'Start selling without writing code', category: 'Store', slug: 'online-store-builder' },
  { name: 'Link-in-Bio Generator', description: 'One link for all your channels', category: 'Link-in-Bio', slug: 'link-in-bio-generator' },
  { name: 'One-Page Website Builder', description: 'Simple sites, single scroll', category: 'Website', slug: 'one-page-website-builder' },
  { name: 'Wedding Website Generator', description: 'Share your day with guests', category: 'Website', slug: 'wedding-website-generator' },
  { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', category: 'Website', slug: 'restaurant-website-builder' },
  { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', category: 'Blog', slug: 'blog-generator-for-beginners' },
];

export const allGeneratorsByCategory = {
  websites: [
    { name: 'AI Website Generator', description: 'Describe your business, get a full site', slug: 'ai-website-generator' },
    { name: 'Free Website Builder for Photographers', description: 'Gallery-first layouts for visual portfolios', slug: 'free-website-builder-for-photographers' },
    { name: 'One-Page Wedding Website Builder', description: 'Share your story and RSVPs in one scroll', slug: 'one-page-wedding-website-builder' },
    { name: 'Restaurant Website Builder', description: 'Menu, hours, reservations, done', slug: 'restaurant-website-builder' },
    { name: 'No-Code Website Builder for Coaches', description: 'Booking and services without code', slug: 'no-code-website-builder-for-coaches' },
    { name: 'AI Website Builder for Yoga Instructors', description: 'Schedules, classes, and branding', slug: 'ai-website-builder-for-yoga-instructors' },
    { name: 'Small Business Website Generator', description: 'Home, services, and contact in minutes', slug: 'small-business-website-generator' },
    { name: 'Beautiful Website Builder for Artists', description: 'Visual-first layouts that feel like galleries', slug: 'beautiful-website-builder-for-artists' },
    { name: 'Personal Website Generator', description: 'Introduce yourself with style', slug: 'personal-website-generator' },
    { name: 'Event Website Builder', description: 'Dates, locations, and RSVP built in', slug: 'event-website-builder' },
    { name: 'Nonprofit Website Generator', description: 'Mission, donate, and volunteer pages', slug: 'nonprofit-website-generator' },
    { name: 'Real Estate Website Builder', description: 'Listings, contact forms, and maps', slug: 'real-estate-website-builder' },
  ],
  'landing-pages': [
    { name: 'AI Landing Page Maker', description: 'One-page sites built to convert', slug: 'ai-landing-page-maker' },
    { name: 'Free Landing Page Generator', description: 'No credit card to launch a campaign page', slug: 'free-landing-page-generator' },
    { name: 'Product Launch Landing Page Builder', description: 'Announce features and collect signups', slug: 'product-launch-landing-page-builder' },
    { name: 'Webinar Landing Page Generator', description: 'Registration and reminders in one page', slug: 'webinar-landing-page-generator' },
    { name: 'SaaS Landing Page Builder', description: 'Features, pricing, and demo CTAs', slug: 'saas-landing-page-builder' },
    { name: 'Ebook Landing Page Generator', description: 'Download form and social proof ready', slug: 'ebook-landing-page-generator' },
    { name: 'App Launch Landing Page Builder', description: 'Screenshots, stores, and install links', slug: 'app-launch-landing-page-builder' },
    { name: 'Consulting Landing Page Generator', description: 'Trust signals and booking forms', slug: 'consulting-landing-page-generator' },
    { name: 'Course Landing Page Builder', description: 'Syllabus, instructor, and enroll button', slug: 'course-landing-page-builder' },
    { name: 'Waitlist Landing Page Generator', description: 'Collect emails before you launch', slug: 'waitlist-landing-page-generator' },
  ],
  portfolios: [
    { name: 'Free Portfolio Generator', description: 'For creatives, in minutes, no fee', slug: 'free-portfolio-generator' },
    { name: 'Portfolio Generator for Designers', description: 'Case studies and visual storytelling', slug: 'portfolio-generator-for-designers' },
    { name: 'Photography Portfolio Builder', description: 'Full-bleed galleries and contact forms', slug: 'photography-portfolio-builder' },
    { name: 'Writer Portfolio Generator', description: 'Articles, clips, and bylines in one place', slug: 'writer-portfolio-generator' },
    { name: 'Developer Portfolio Builder', description: 'Projects, repos, and skills displayed cleanly', slug: 'developer-portfolio-builder' },
    { name: 'Music Portfolio Generator', description: 'Tracks, videos, and tour dates', slug: 'music-portfolio-generator' },
    { name: 'Model Portfolio Builder', description: 'Comp cards and booking contact forms', slug: 'model-portfolio-builder' },
    { name: 'Architect Portfolio Generator', description: 'Projects, renders, and firm details', slug: 'architect-portfolio-generator' },
    { name: 'Videographer Portfolio Builder', description: 'Reels, credits, and client list', slug: 'videographer-portfolio-builder' },
    { name: 'UX Portfolio Generator', description: 'Case studies and process walkthroughs', slug: 'ux-portfolio-generator' },
  ],
  blogs: [
    { name: 'Blog Generator for Beginners', description: 'Publish-ready in minutes', slug: 'blog-generator-for-beginners' },
    { name: 'AI Blog Builder', description: 'Structure, categories, and first posts ready', slug: 'ai-blog-builder' },
    { name: 'Food Blog Generator', description: 'Recipes, photos, and reading layouts', slug: 'food-blog-generator' },
    { name: 'Travel Blog Builder', description: 'Maps, itineraries, and photo stories', slug: 'travel-blog-builder' },
    { name: 'Fashion Blog Generator', description: 'Editorial layouts and lookbook support', slug: 'fashion-blog-generator' },
    { name: 'Tech Blog Builder', description: 'Code blocks, categories, and reading modes', slug: 'tech-blog-builder' },
    { name: 'Lifestyle Blog Generator', description: 'Clean typography and photo-first layouts', slug: 'lifestyle-blog-generator' },
    { name: 'Parenting Blog Builder', description: 'Tips, resources, and community feel', slug: 'parenting-blog-builder' },
    { name: 'Fitness Blog Generator', description: 'Workouts, nutrition, and progress posts', slug: 'fitness-blog-generator' },
    { name: 'Finance Blog Builder', description: 'Guides, calculators, and clean reading', slug: 'finance-blog-builder' },
  ],
  stores: [
    { name: 'Online Store Builder', description: 'Start selling without writing code', slug: 'online-store-builder' },
    { name: 'Online Store Builder for Restaurants', description: 'Menu items, orders, and delivery ready', slug: 'online-store-builder-for-restaurants' },
    { name: 'Handmade Shop Generator', description: 'Product stories and craft-focused layouts', slug: 'handmade-shop-generator' },
    { name: 'Digital Product Store Builder', description: 'Downloads, licenses, and delivery', slug: 'digital-product-store-builder' },
    { name: 'Clothing Store Generator', description: 'Collections, sizing, and checkout flow', slug: 'clothing-store-generator' },
    { name: 'Beauty Store Builder', description: 'Products, reviews, and tutorials', slug: 'beauty-store-builder' },
    { name: 'Furniture Store Generator', description: 'Catalog, variants, and delivery info', slug: 'furniture-store-generator' },
    { name: 'Art Print Store Builder', description: 'Galleries, editions, and shipping', slug: 'art-print-store-builder' },
    { name: 'Subscription Box Generator', description: 'Plans, previews, and recurring billing', slug: 'subscription-box-generator' },
    { name: 'Coffee Shop Store Builder', description: 'Beans, subscriptions, and local pickup', slug: 'coffee-shop-store-builder' },
  ],
  'link-in-bio': [
    { name: 'Link-in-Bio Generator', description: 'One link for all your channels', slug: 'link-in-bio-generator' },
    { name: 'Creator Link Page Builder', description: 'Social links, content, and tips', slug: 'creator-link-page-builder' },
    { name: 'Musician Link-in-Bio Generator', description: 'Streaming, merch, and tour dates', slug: 'musician-link-in-bio-generator' },
    { name: 'Influencer Link Page Builder', description: 'Brands, content, and contact', slug: 'influencer-link-page-builder' },
    { name: 'Podcaster Link-in-Bio Generator', description: 'Episodes, platforms, and sponsors', slug: 'podcaster-link-in-bio-generator' },
    { name: 'TikTok Creator Link Builder', description: 'Videos, shops, and collab links', slug: 'tiktok-creator-link-builder' },
    { name: 'YouTuber Link-in-Bio Generator', description: 'Latest uploads, merch, and community', slug: 'youtuber-link-in-bio-generator' },
    { name: 'Coach Link Page Builder', description: 'Bookings, programs, and testimonials', slug: 'coach-link-page-builder' },
    { name: 'Artist Link-in-Bio Generator', description: 'Portfolio, shop, and commission info', slug: 'artist-link-in-bio-generator' },
    { name: 'Freelancer Link Page Builder', description: 'Services, rates, and contact form', slug: 'freelancer-link-page-builder' },
  ],
};
