// i18n strings for the Generators hub page
// Add strings.es, strings.ja, etc. for other locales.

export const strings = {
  // Top bar
  logoText: 'strikingly AI',

  // Breadcrumb
  breadcrumbRoot: 'Strikingly',
  breadcrumbCurrent: 'AI Generators',

  // Hero
  heroLine1: 'BUILD ANY KIND OF SITE',
  heroLine2: 'WITH AI, IN AN INSTANT',
  heroSubheadline:
    'Browse the right generator for what you\'re building, or jump straight into our AI site builder.',
  ctaPrimary: 'START BUILDING - IT\'S FREE',
  ctaSecondary: 'BROWSE GENERATORS',

  // Featured Generators
  featuredHeading: 'FEATURED GENERATORS',
  featuredSubheading: 'A few common starting points.',

  // Browse by Category
  browseHeading: 'BROWSE BY CATEGORY',

  // All Generators
  allGeneratorsHeading: 'ALL GENERATORS',
  allGeneratorsSubheading: 'Sixty-plus generators, organized by what you\'re building.',
  searchPlaceholder: 'Search generators...',
  searchAriaLabel: 'Search generators',
  searchResultCount: '{count} generators match',
  searchNoResults: 'No generators match your search.',
  searchClearButton: 'Clear search',
  searchNoResultsLink: "Can't find it? Start with our AI builder.",
  showAllButton: 'Show all {count} generators',
  showLessButton: 'Show less',

  // Category descriptions
  catWebsites: 'AI-built business and personal sites for any goal.',
  catLandingPages: 'Single-page sites built to convert visitors fast.',
  catPortfolios: 'Showcase your work with a clean, focused site.',
  catBlogs: 'Publish-ready blogs with built-in SEO basics.',
  catStores: 'Sell products online with payments built in.',
  catLinkInBio: 'One link, all your places. Made for creators.',

  // How It Works
  howItWorksHeading: 'HOW IT WORKS',
  step1Title: 'PICK A GENERATOR',
  step1Body: 'Browse by category or search to find one that fits your goal.',
  step2Title: 'DESCRIBE YOUR SITE',
  step2Body: 'Tell our AI builder about your business in a sentence or two.',
  step3Title: 'GENERATE AND PUBLISH',
  step3Body: 'Get a fully built site in seconds. Customize anything, then go live.',

  // Why Strikingly
  whyHeading: 'WHY STRIKINGLY',
  why1Title: 'LIVE IN SECONDS',
  why1Body: 'Describe your site, we build it. No setup, no learning curve.',
  why2Title: 'MOBILE BY DEFAULT',
  why2Body: 'Every generator produces responsive sites that work on any device.',
  why3Title: 'FREE TO START',
  why3Body: 'Generate, customize, and publish without a credit card.',

  // FAQ
  faqHeading: 'FREQUENTLY ASKED QUESTIONS',
  faq1Q: 'What is an AI site generator?',
  faq1A:
    'An AI site generator is a tool that uses artificial intelligence to build a complete website based on your description. Instead of choosing templates and dragging elements into place, you simply tell the AI what kind of site you need, and it generates the layout, content, and design for you.',
  faq2Q: 'How is a generator different from a template?',
  faq2A:
    'A template is a static starting point that you customize manually. A generator is dynamic: it builds a unique site tailored to your specific business, industry, or goal. Generators can produce different results every time, while templates look the same for everyone who uses them.',
  faq3Q: 'Are these generators free to use?',
  faq3A:
    'Yes. You can browse generators and generate a site for free. No credit card is required to get started. Strikingly offers free hosting so you can publish and share your site right away.',
  faq4Q: 'What kinds of sites can I build?',
  faq4A:
    'You can build business websites, landing pages, portfolios, blogs, online stores, and link-in-bio pages. Each generator is optimized for its specific use case, so you get the right features and layout from the start.',
  faq5Q: 'Can I customize what the generator produces?',
  faq5A:
    'Absolutely. After the AI generates your site, you can edit every part of it — text, images, colors, layout, and more. The generator gives you a strong starting point, and you have full control to make it yours.',
  faq6Q: 'Do generated sites work on mobile?',
  faq6A:
    'Yes. Every site generated by Strikingly is responsive by default. It automatically adapts to look great on phones, tablets, and desktops without any extra work from you.',

  // Closing CTA
  closingHeading: 'READY TO BUILD?',
  closingSub: 'Pick a generator above, or jump straight into our AI builder.',
  closingCta: 'START WITH AI BUILDER',

  // Footer
  footerAbout: 'About',
  footerPricing: 'Pricing',
  footerTemplates: 'Templates',
  footerSupport: 'Support',
  footerBlog: 'Blog',
  footerTerms: 'Terms',
  footerPrivacy: 'Privacy',
  footerCopyright: '© {year} Strikingly. All rights reserved.',
};
