// Internationalization strings for Generators Hub Page
// To add a new language, create strings.{locale}.js and add to the locale switcher

export const strings = {
  en: {
    // Meta
    siteName: 'Strikingly AI',
    pageTitle: 'AI Website Generators - Build Any Site in Seconds | Strikingly',

    // Top Bar
    logo: 'Strikingly AI',

    // Breadcrumb
    breadcrumbHome: 'Strikingly',
    breadcrumbCurrent: 'AI Generators',

    // Hero
    heroLine1: 'BUILD ANY KIND OF SITE',
    heroLine2: 'WITH AI, IN AN INSTANT',
    heroSubheadline: "Browse the right generator for what you're building, or jump straight into our AI site builder.",
    heroPrimaryCta: "START BUILDING - IT'S FREE",
    heroSecondaryCta: 'BROWSE GENERATORS',

    // Featured Generators
    featuredHeading: 'FEATURED GENERATORS',
    featuredSubheading: 'A few common starting points.',

    // Browse by Category
    browseHeading: 'BROWSE BY CATEGORY',
    categoryWebsites: 'Websites',
    categoryWebsitesDesc: 'AI-built business and personal sites for any goal.',
    categoryLandingPages: 'Landing Pages',
    categoryLandingPagesDesc: 'Single-page sites built to convert visitors fast.',
    categoryPortfolios: 'Portfolios',
    categoryPortfoliosDesc: 'Showcase your work with a clean, focused site.',
    categoryBlogs: 'Blogs',
    categoryBlogsDesc: 'Publish-ready blogs with built-in SEO basics.',
    categoryStores: 'Online Stores',
    categoryStoresDesc: 'Sell products online with payments built in.',
    categoryLinkInBio: 'Link-in-Bio',
    categoryLinkInBioDesc: 'One link, all your places. Made for creators.',

    // All Generators
    allGeneratorsHeading: 'ALL GENERATORS',
    allGeneratorsSubheading: 'Sixty-plus generators, organized by what you\'re building.',
    searchPlaceholder: 'Search generators...',
    searchAriaLabel: 'Search generators',
    resultCount: '{count} generators match',
    noResults: 'No generators match your search.',
    clearSearch: 'Clear search',
    cantFindIt: "Can't find it?",
    startWithAi: 'Start with our AI builder.',
    showAll: 'Show all {count} generators',
    showLess: 'Show less',

    // How It Works
    howItWorksHeading: 'HOW IT WORKS',
    howItWorksStep1Title: 'PICK A GENERATOR',
    howItWorksStep1Desc: 'Browse by category or search to find one that fits your goal.',
    howItWorksStep2Title: 'DESCRIBE YOUR SITE',
    howItWorksStep2Desc: 'Tell our AI builder about your business in a sentence or two.',
    howItWorksStep3Title: 'GENERATE AND PUBLISH',
    howItWorksStep3Desc: 'Get a fully built site in seconds. Customize anything, then go live.',

    // Why Strikingly
    whyHeading: 'WHY STRIKINGLY',
    whyLiveTitle: 'LIVE IN SECONDS',
    whyLiveDesc: "Describe your site, we build it. No setup, no learning curve.",
    whyMobileTitle: 'MOBILE BY DEFAULT',
    whyMobileDesc: 'Every generator produces responsive sites that work on any device.',
    whyFreeTitle: 'FREE TO START',
    whyFreeDesc: 'Generate, customize, and publish without a credit card.',

    // FAQ
    faqHeading: 'FREQUENTLY ASKED QUESTIONS',
    faqQ1: 'What is an AI site generator?',
    faqA1: 'An AI site generator is a tool that uses artificial intelligence to help you create a website. Instead of starting from scratch with a blank page, you describe what you need, and the AI builds a complete, functional website based on your description. Strikingly\'s generators cover everything from personal portfolios to online stores.',
    faqQ2: 'How is a generator different from a template?',
    faqA2: 'A template is a pre-designed layout that you fill with your own content. A generator creates a customized site based on your specific needs and description. While templates require you to move and style elements yourself, generators do the heavy lifting by producing a ready-to-use site that matches your goals.',
    faqQ3: 'Are these generators free to use?',
    faqA3: 'Yes! Strikingly\'s AI generators are free to use. You can generate, customize, and publish your site without entering a credit card. Premium features and custom domains are available when you\'re ready to upgrade.',
    faqQ4: 'What kinds of sites can I build?',
    faqA4: 'You can build almost any type of website with Strikingly\'s generators. Business websites, portfolios, blogs, online stores, landing pages, wedding sites, restaurant sites, and link-in-bio pages are just a few examples. Each generator is optimized for its specific use case.',
    faqQ5: 'Can I customize what the generator produces?',
    faqA5: 'Absolutely. The generator creates a starting point based on your description, but you have full control to customize everything. Change colors, fonts, images, text, and layout. The generated site is yours to modify however you like.',
    faqQ6: 'Do generated sites work on mobile?',
    faqA6: 'Yes, every site generated by Strikingly is fully responsive and works beautifully on mobile devices, tablets, and desktops. Mobile optimization is built into every template and generated site by default.',

    // Closing CTA
    closingHeading: 'READY TO BUILD?',
    closingSub: 'Pick a generator above, or jump straight into our AI builder.',
    closingCta: 'START WITH AI BUILDER',

    // Footer
    footerAbout: 'About',
    footerPricing: 'Pricing',
    footerTemplates: 'Templates',
    footerSupport: 'Support',
    footerBlog: 'Blog',
    footerTerms: 'Terms',
    footerPrivacy: 'Privacy',
    footerCopyright: '© 2026 Strikingly, Inc. All rights reserved.',
  }
};

export default strings;
