export const strings = {
  en: {
    breadcrumb: "Strikingly > AI Generators",
    hero: {
      headlinePart1: "BUILD ANY KIND OF SITE",
      headlinePart2: "WITH AI, IN AN INSTANT",
      subheadline: "Browse the right generator for what you're building, or jump straight into our AI site builder.",
      primaryCTA: "START BUILDING - IT'S FREE",
      secondaryCTA: "BROWSE GENERATORS"
    },
    featuredGenerators: {
      heading: "FEATURED GENERATORS",
      subheading: "A few common starting points."
    },
    browseByCategory: {
      heading: "BROWSE BY CATEGORY",
      categories: [
        { id: "websites", name: "Websites", label: "WEBSITES", desc: "AI-built business and personal sites for any goal." },
        { id: "landing-pages", name: "Landing Pages", label: "LANDING PAGES", desc: "Single-page sites built to convert visitors fast." },
        { id: "portfolios", name: "Portfolios", label: "PORTFOLIOS", desc: "Showcase your work with a clean, focused site." },
        { id: "blogs", name: "Blogs", label: "BLOGS", desc: "Publish-ready blogs with built-in SEO basics." },
        { id: "stores", name: "Online Stores", label: "ONLINE STORES", desc: "Sell products online with payments built in." },
        { id: "link-in-bio", name: "Link-in-Bio", label: "LINK-IN-BIO", desc: "One link, all your places. Made for creators." }
      ]
    },
    allGenerators: {
      heading: "ALL GENERATORS",
      subheading: "Sixty-plus generators, organized by what you're building.",
      searchPlaceholder: "Search generators...",
      searchAriaLabel: "Search generators",
      noResults: "Can't find it?",
      noResultsCTA: "Start with our AI builder."
    },
    howItWorks: {
      heading: "HOW IT WORKS",
      steps: [
        { title: "PICK A GENERATOR", desc: "Browse by category or search to find one that fits your goal." },
        { title: "DESCRIBE YOUR SITE", desc: "Tell our AI builder about your business in a sentence or two." },
        { title: "GENERATE AND PUBLISH", desc: "Get a fully built site in seconds. Customize anything, then go live." }
      ]
    },
    whyStrikingly: {
      heading: "WHY STRIKINGLY",
      claims: [
        { title: "LIVE IN SECONDS", desc: "Describe your site, we build it. No setup, no learning curve." },
        { title: "MOBILE BY DEFAULT", desc: "Every generator produces responsive sites that work on any device." },
        { title: "FREE TO START", desc: "Generate, customize, and publish without a credit card." }
      ]
    },
    faq: {
      heading: "FREQUENTLY ASKED QUESTIONS",
      questions: [
        {
          q: "What is an AI site generator?",
          a: "An AI site generator is a tool that automatically builds a complete website for you based on a short description. Instead of picking a template and filling in the blanks yourself, you tell the AI about your business, and it generates the layout, images, and text optimized for your specific goal."
        },
        {
          q: "How is a generator different from a template?",
          a: "A template gives you an empty shell that you have to write content for and find images for. A generator builds the finished product immediately using AI, including relevant placeholder copy and imagery, saving you hours of initial layout work."
        },
        {
          q: "Are these generators free to use?",
          a: "Yes. You can use any of our AI generators to build your layout for free. You only pay if you decide to upgrade to a premium plan later to attach a custom domain or unlock advanced e-commerce features."
        },
        {
          q: "What kinds of sites can I build?",
          a: "You can build almost anything. We support portfolios, online stores, landing pages, business websites, blogs, and link-in-bio pages. Whether you're a restaurant sharing menus or a designer showing work, there's a generator for you."
        },
        {
          q: "Can I customize what the generator produces?",
          a: "Absolutely. The generator gives you a massive head start by building the first version, but you have full control over the final site. You can edit text, swap images, change colors, and add new sections using our intuitive drag-and-drop editor."
        },
        {
          q: "Do generated sites work on mobile?",
          a: "Yes, every site generated by Strikingly is fully responsive. It will automatically adapt to look great on desktop computers, tablets, and smartphones without any extra work on your part."
        }
      ]
    },
    closingCta: {
      heading: "READY TO BUILD?",
      subheading: "Pick a generator above, or jump straight into our AI builder.",
      cta: "START WITH AI BUILDER"
    }
  }
};

export const sampleData = {
  featured: [
    { name: "AI Website Generator", desc: "Describe your business, get a full site", category: "Website" },
    { name: "Free Portfolio Generator", desc: "For creatives, in minutes, no fee", category: "Portfolio" },
    { name: "AI Landing Page Maker", desc: "One-page sites built to convert", category: "Landing Page" },
    { name: "Online Store Builder", desc: "Start selling without writing code", category: "Store" },
    { name: "Link-in-Bio Generator", desc: "One link for all your channels", category: "Link-in-Bio" },
    { name: "One-Page Website Builder", desc: "Simple sites, single scroll", category: "Website" },
    { name: "Wedding Website Generator", desc: "Share your day with guests", category: "Website" },
    { name: "Restaurant Website Builder", desc: "Menu, hours, reservations, done", category: "Website" },
    { name: "Blog Generator for Beginners", desc: "Publish-ready in minutes", category: "Blog" }
  ],
  generators: {
    websites: [
      { name: "AI Website Generator", desc: "Describe your business, get a full site" },
      { name: "One-Page Website Builder", desc: "Simple sites, single scroll" },
      { name: "Wedding Website Generator", desc: "Share your day with guests" },
      { name: "Restaurant Website Builder", desc: "Menu, hours, reservations, done" },
      { name: "Free Website Builder for Photographers", desc: "Start your photography business online" },
      { name: "Yoga Studio Website Builder", desc: "Class schedules and beautiful design" },
      { name: "Real Estate Website Generator", desc: "Listings and agent profiles made easy" },
      { name: "Church Website Builder", desc: "Keep your congregation connected" },
      { name: "Small Business Website Generator", desc: "The perfect start for local shops" }
    ],
    "landing-pages": [
      { name: "AI Landing Page Maker", desc: "One-page sites built to convert" },
      { name: "App Landing Page Builder", desc: "Showcase your new mobile app" },
      { name: "Event Landing Page Generator", desc: "Sell tickets and share details" },
      { name: "Book Launch Landing Page", desc: "Promote your new publication" },
      { name: "Product Waitlist Builder", desc: "Capture emails before launch" },
      { name: "Webinar Registration Page", desc: "Get signups for your next event" },
      { name: "Real Estate Lead Page", desc: "Capture buyer and seller info" },
      { name: "Course Sales Page Generator", desc: "Sell your online education" }
    ],
    portfolios: [
      { name: "Free Portfolio Generator", desc: "For creatives, in minutes, no fee" },
      { name: "Portfolio Generator for Designers", desc: "Showcase your UI/UX work" },
      { name: "Photography Portfolio Builder", desc: "High-resolution image galleries" },
      { name: "Copywriter Portfolio Maker", desc: "Display your words beautifully" },
      { name: "Video Production Portfolio", desc: "Embed your reels and clips" },
      { name: "Actor Portfolio Generator", desc: "Headshots and resumes online" },
      { name: "Artist Portfolio Builder", desc: "A clean frame for your art" },
      { name: "Student Portfolio Generator", desc: "Start your career right" },
      { name: "Architecture Portfolio Maker", desc: "Display your projects and plans" }
    ],
    blogs: [
      { name: "Blog Generator for Beginners", desc: "Publish-ready in minutes" },
      { name: "Travel Blog Builder", desc: "Share your journeys and photos" },
      { name: "Food Blog Generator", desc: "Publish recipes and reviews" },
      { name: "Tech Blog Maker", desc: "Share your code and thoughts" },
      { name: "Fashion Blog Builder", desc: "Style tips and daily outfits" },
      { name: "Lifestyle Blog Generator", desc: "Your life, beautifully documented" },
      { name: "Business Blog Maker", desc: "Content marketing made easy" },
      { name: "Personal Blog Builder", desc: "A simple space for your ideas" }
    ],
    stores: [
      { name: "Online Store Builder", desc: "Start selling without writing code" },
      { name: "Online Store Builder for Restaurants", desc: "Take takeout orders online" },
      { name: "Boutique Clothing Store Generator", desc: "Sell fashion online fast" },
      { name: "Digital Products Store Builder", desc: "Sell downloads automatically" },
      { name: "Handmade Crafts Store Maker", desc: "Share your creations with the world" },
      { name: "Subscription Box Store Builder", desc: "Recurring revenue made simple" },
      { name: "Merch Store Generator", desc: "Sell branded gear easily" },
      { name: "Art Print Store Builder", desc: "Sell physical prints of your art" },
      { name: "Ebook Store Maker", desc: "Sell your writing directly" }
    ],
    "link-in-bio": [
      { name: "Link-in-Bio Generator", desc: "One link for all your channels" },
      { name: "Creator Link Page Builder", desc: "Consolidate your social presence" },
      { name: "Musician Link-in-Bio Maker", desc: "Tour dates, merch, and streams" },
      { name: "Twitch Streamer Link Page", desc: "Schedules, tips, and socials" },
      { name: "Podcast Link Builder", desc: "All your listening platforms in one place" },
      { name: "TikToker Link-in-Bio", desc: "Push traffic where it matters" },
      { name: "Fitness Coach Link Page", desc: "Programs, YouTube, and Insta" },
      { name: "Author Link-in-Bio", desc: "Books, newsletter, and appearances" }
    ]
  }
};
