import { Sparkles, Star } from 'lucide-react'
import ProductCard from './ProductCard.jsx'
import { categories, products, ugcCards } from '../../data/products.js'
import { getStrkImageUrl } from '../../lib/image-url.js'
const testimonials = [
  { name: 'Maya R.', text: 'The huggies feel weighty and elegant, but I wear them every single day.' },
  { name: 'Claire W.', text: 'Beautiful packaging, warm gold tone, and the necklace looked far more expensive than it was.' },
  { name: 'Nina S.', text: 'Finally jewelry that feels special without being precious. Perfect self-gift.' },
]

export default function HomePage({ onNavigate, onOpenProduct, onAddToCart }) {
  return (
    <main>
      <section className="relative flex min-h-screen items-end overflow-hidden bg-velmora-ink text-velmora-ivory">
        <div className="absolute inset-0 bg-velmora-espresso" data-strk-bg-id="hero-jewelry-model-bg-bf14c8" data-strk-bg="[hero-image-context] [hero-subtitle] [hero-title]" data-strk-bg-ratio="16x9" data-strk-bg-width="1800" />
        <div className="absolute inset-0 bg-velmora-ink/75" />
        <div className="absolute inset-0 bg-gradient-to-t from-velmora-ink via-velmora-ink/70 to-velmora-ink/40" />
        <div className="relative mx-auto grid w-full max-w-7xl gap-10 px-4 pb-20 pt-36 sm:px-6 md:grid-cols-[1.1fr_0.9fr] md:pb-28 lg:px-8">
          <div className="velmora-hero-copy max-w-3xl animate-fade-up">
            <p className="mb-5 text-xs font-bold uppercase tracking-[0.32em] text-velmora-champagne">Demi-fine essentials for luminous days</p>
            <h1 id="hero-title" className="font-serif text-6xl leading-[0.92] tracking-tight text-velmora-ivory sm:text-7xl lg:text-8xl">Crafted to be Treasured</h1>
            <p id="hero-subtitle" className="mt-6 max-w-xl text-base leading-8 text-velmora-sand sm:text-lg">Warm gold jewelry designed for the rituals of gifting, self-purchase, and every quietly unforgettable moment between.</p>
            <span id="hero-image-context" className="sr-only">Warm-lit close-up of gold jewelry worn on a woman model, quiet luxury editorial photography</span>
            <button type="button" onClick={() => onNavigate('shop')} className="mt-9 rounded-full bg-velmora-champagne px-8 py-4 text-sm font-bold uppercase tracking-[0.24em] text-velmora-ink shadow-soft transition hover:-translate-y-0.5 hover:bg-velmora-gold hover:text-velmora-ivory focus:outline-none focus:ring-2 focus:ring-velmora-ivory focus:ring-offset-2 focus:ring-offset-velmora-ink">Shop the Collection</button>
          </div>
          <div className="hidden items-end justify-end md:flex"><div className="velmora-hero-note max-w-xs rounded-3xl border border-velmora-ivory/20 bg-velmora-ink/55 p-6 text-sm leading-7 text-velmora-sand shadow-soft backdrop-blur-sm"><Sparkles className="mb-4 h-5 w-5 text-velmora-champagne" />Jewelry made to layer softly, catch warm light, and move from ordinary days to meaningful evenings.</div></div>
        </div>
      </section>
      <section className="border-y border-velmora-sand bg-velmora-mist text-velmora-ink"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-8 gap-y-3 px-4 py-4 text-center text-[0.68rem] font-bold uppercase tracking-[0.24em] text-velmora-espresso sm:px-6 lg:px-8"><span>Free Worldwide Shipping</span><span className="hidden h-1 w-1 rounded-full bg-velmora-champagne sm:block" /><span>30-Day Returns</span><span className="hidden h-1 w-1 rounded-full bg-velmora-champagne sm:block" /><span>18K Gold Plated</span><span className="hidden h-1 w-1 rounded-full bg-velmora-champagne sm:block" /><span>Hypoallergenic</span></div></section>
      <SectionHeader id="bestsellers" eyebrow="Bestsellers" title="Most-Loved in Gold" copy="The five pieces customers reach for first: effortless, giftable, and made to glow against skin." />
      <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 lg:px-8"><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-5">{products.map((product) => <ProductCard key={product.id} product={product} onOpenProduct={onOpenProduct} onAddToCart={onAddToCart} />)}</div></section>
      <section id="journal" className="bg-velmora-ink py-20 text-velmora-ivory"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-velmora-champagne">Velmora reels</p><h2 className="mt-3 font-serif text-4xl text-velmora-ivory md:text-6xl">Seen in Soft Light</h2></div><p className="max-w-md text-sm leading-7 text-velmora-sand">A reel-style strip of real-life styling moments: ear stacks, golden necklines, and pieces in motion.</p></div><div className="no-scrollbar flex gap-5 overflow-x-auto pb-3">{ugcCards.map((card) => <article key={card.id} className="group relative h-[430px] min-w-[240px] overflow-hidden rounded-[2rem] bg-velmora-espresso shadow-soft md:min-w-[280px]"><img alt={card.caption} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" src={getStrkImageUrl(card.imageId)} /><div className="absolute inset-0 bg-gradient-to-t from-velmora-ink/75 via-transparent to-transparent" /><h3 id={card.titleId} className="absolute bottom-5 left-5 right-5 font-serif text-2xl leading-7 text-velmora-ivory">{card.caption}</h3></article>)}</div><span id="journal-title" className="sr-only">warm gold jewelry worn by women editorial close up</span></div></section>
      <section id="collections" className="bg-velmora-ivory py-20 text-velmora-ink"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-velmora-clay">Shop by category</p><h2 className="mt-3 font-serif text-5xl text-velmora-ink md:text-6xl">Find Your Signature</h2></div><button type="button" onClick={() => onNavigate('shop')} className="self-start rounded-full border border-velmora-ink px-6 py-3 text-xs font-bold uppercase tracking-[0.22em] text-velmora-ink transition hover:bg-velmora-ink hover:text-velmora-ivory md:self-auto">View All</button></div><div className="grid gap-5 md:grid-cols-3">{categories.map((category) => <button key={category.id} type="button" onClick={() => onNavigate('shop')} className="group relative aspect-[4/5] overflow-hidden rounded-t-full bg-velmora-mist p-0 text-left"><img alt={category.label} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" src={getStrkImageUrl(category.imageId)} /><div className="absolute inset-0 bg-gradient-to-t from-velmora-ink/70 via-velmora-ink/10 to-transparent opacity-80 transition group-hover:opacity-100" /><span id={category.titleId} className="absolute bottom-7 left-7 font-serif text-4xl text-velmora-ivory">{category.label}</span></button>)}</div><span id="category-section-title" className="sr-only">demi-fine gold jewelry categories</span></div></section>
      <section id="story" className="bg-velmora-mist py-20 text-velmora-ink"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 md:grid-cols-2 md:items-center lg:px-8"><div className="relative overflow-hidden rounded-t-full bg-velmora-sand"><img alt="Velmora jewelry styling" className="aspect-[4/5] w-full object-cover" src={getStrkImageUrl('story-jewelry-styling-img-4f9a21')} /></div><div className="md:pl-8"><p className="text-xs font-bold uppercase tracking-[0.28em] text-velmora-clay">Our Story</p><h2 id="story-title" className="mt-3 font-serif text-5xl leading-tight text-velmora-ink md:text-7xl">Gold that feels personal, never precious.</h2><p id="story-copy" className="mt-6 text-base leading-8 text-velmora-clay">Velmora creates demi-fine jewelry with the warmth of heirlooms and the ease of everyday pieces. We design in small, intentional silhouettes for women who choose beauty as a ritual.</p><button type="button" className="mt-8 border-b border-velmora-gold bg-transparent p-0 pb-1 text-sm font-bold uppercase tracking-[0.24em] text-velmora-gold transition hover:text-velmora-ink">Our Story</button></div></div></section>
      <section className="bg-velmora-ivory py-20 text-velmora-ink"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{testimonials.map((review) => <article key={review.name} className="border border-velmora-sand bg-velmora-mist p-7 text-velmora-ink shadow-card"><div className="mb-5 flex gap-1 text-velmora-champagne">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className="h-4 w-4 fill-current" />)}</div><p className="font-serif text-2xl leading-8 text-velmora-ink">“{review.text}”</p><p className="mt-5 text-xs font-bold uppercase tracking-[0.24em] text-velmora-clay">{review.name}</p></article>)}</div></div></section>
      <section className="bg-velmora-espresso px-4 py-16 text-velmora-ivory sm:px-6 lg:px-8"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-[1fr_0.9fr] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-velmora-champagne">Private list</p><h2 className="mt-3 font-serif text-4xl text-velmora-ivory md:text-6xl">Join for 10% off your first order.</h2></div><form className="flex flex-col gap-3 sm:flex-row" onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" placeholder="you@example.com" className="min-h-14 flex-1 rounded-full border border-velmora-ivory/20 bg-velmora-ivory px-5 text-sm text-velmora-ink placeholder:text-velmora-clay focus:outline-none focus:ring-2 focus:ring-velmora-champagne" /><button type="submit" className="rounded-full bg-velmora-champagne px-7 py-4 text-sm font-bold uppercase tracking-[0.22em] text-velmora-ink transition hover:bg-velmora-gold hover:text-velmora-ivory">Join</button></form></div></section>
    </main>
  )
}

function SectionHeader({ id, eyebrow, title, copy }) {
  return <section id={id} className="mx-auto max-w-7xl px-4 pb-10 pt-20 text-velmora-ink sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.28em] text-velmora-clay">{eyebrow}</p><h2 className="mt-3 font-serif text-5xl leading-tight text-velmora-ink md:text-6xl">{title}</h2><p className="mt-4 text-base leading-8 text-velmora-clay">{copy}</p></div></section>
}
